### ISSUE TITLE
Is there a way...?

### ISSUE THREAD

**Issue by jochim-van-dijck** [scout-app/scout-app#100]
Is there a way Scout can turn this: "@include box-sizing(border-box);" into this: "-webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"?

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing ticket. Download latest version of Scout-App.

* [Scout-App 2](http://scout-app.io) (2016)
