### ISSUE TITLE
Scout Crash on startup

### ISSUE THREAD

**Issue by greg-fox** [scout-app/scout-app#101]
I am trying to use Scout on a brand new VM, and every time I try to compile my scss file I get the following.

Errno::ENOENT on line 102 of org/jruby/RubyFileTest.java: No such file or directory - //psf/Home
org/jruby/RubyFileTest.java:87:in `directory?'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass.rb:19:in `shared_extension_paths'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:112:in `discover_extensions!'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:27:in `configure!'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:15:in `initialize'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/update_project.rb:37:in `initialize'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
C:\Program Files (x86)\Scout\bin\compass:12:in `(root)'

Now I fully expect that I have missed something in my install on this system. Are there any prerequisites for running Scout? (other than Air that is). Do I need to install ruby? I've used Scout on an previous computer and didn't have any issues with it. The main difference that I can think of is that I am running Win 7 under a VM instead of on direct hardware.

Any help would be appreciated.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing ticket. Download latest version of Scout-App.

* [Scout-App 2](http://scout-app.io) (2016)
