### ISSUE TITLE
Error in typographic measurements

### ISSUE THREAD

**Issue by hugoassuncao** [scout-app/scout-app#103]
I got this message in my scout app:

>Dear developers making use of FSSM in your projects, be taking place in the new shared
>guard/listen project. Please let us know if you need help transitioning! ^_^b - Travis Tilley

then, I updated my scout to latest version (0.7.1), my ruby to version 2.0.0 and installed the listen gem.
since then I'm having an annoying problem: scout is ignoring every mesurement in which there is a . (dot).
Ex.: if my font-size is 1.25em, it's rendering 1em; if the size is 0.85em, it renders 0em.

What is that about? How can I solve this?

I'm running Windows 7 Professional SP1 64bit

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing ticket. Download latest version of Scout-App.

* [Scout-App 2](http://scout-app.io) (2016)
