### ISSUE TITLE
Problem with rgba, very important if you can fix

### ISSUE THREAD

**Issue by LazYann** [scout-app/scout-app#105]
Hey! I've been using Scout App for a long time and one thing is very annoying to me. Everytime I use the rgba css rule, it seems like it have a bug. It doesnt makes it every single time, but after a few save, it's acting like it doesnt understand the number after the dot (for example, background-color: rgba(0, 0, 0, 0.6) will be transformed by scout app in the css file as rgba(0, 0, 0, 0) and that makes the color completely transparent (of course) ). Like I said, it doesnt do it every single times, but it happens at least 10 to 20 times per project to me which is very annoying because I use RGBA alot... I know my english isnt perfect but I hope you understood my main point.

Sincerely,

Yann

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing ticket. Download latest version of Scout-App. If problem still exists, create a new issue.

* [Scout-App 2](http://scout-app.io) (2016)
