### ISSUE TITLE
ArgumentError in RubyKernel.java

### ISSUE THREAD

**Issue by nlswtlr** [scout-app/scout-app#107]
Hi guys,

when I started scout this morning (mac os) I received the following error message: 
"ArgumentError on line 2104 of org/jruby/RubyKernel.java: wrong number of arguments (4 for 3)"
Beside that there were a bunch of other error messages, but I'm not sure if I should post them all here.

Any suggestions how to solve this problem? Reinstall or update jruby or java?

Regards,
Nils

**Comment by edvinicombe** [comment]
King amoungst men Nils! This saved me!!!

**Comment by gildniy** [comment]
Wow thanks @NilsWe you save me too!
