### ISSUE TITLE
Enable Sass's :debug_info

### ISSUE THREAD

**Issue by morewings** [scout-app/scout-app#108]
Is there any way to enable Sass's :debug_info? As described here https://addons.mozilla.org/en-us/firefox/addon/firesass-for-firebug/
Thanks.

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 supports "Development" environment mode that will output a Sass map. This should be equivalent to what you're requesting, since FireSass for Firebug no longer exists.

Closing this ticket as resolved.

* [Scout-App 2](http://scout-app.io) (2016)
