### ISSUE TITLE
HTML5 Boilerplate Reset

### ISSUE THREAD

**Issue by brianyuen** [scout-app/scout-app#11]
Hi,
I've been searching around and can't find the answer to this.  I'm very new to Compass/Sass and would like to know how to use the HTML5 Boilerplate's reset as an @import, possibly this one https://github.com/sporkd/compass-html5-boilerplate

Should I follow the instructions on the link, or should I treat it differently since Scout is a stand-alone application?

Any help would be great

**Comment by TheJaredWilcurt** [comment]
The latest version of Scout-App no longer relies on Ruby. Which means we cannot support Ruby-specific Gems anymore. Also this repo hasn't been updated in 4 years. There do not seem to be any Sass files/mixins/partials that I can see in H5BP.

Closing this issue as 'will not fix'.

* [Scout-App.io](http://scout-app.io)
