### ISSUE TITLE
Possible to use config/compass.rb?

### ISSUE THREAD

**Issue by ronlussier** [scout-app/scout-app#110]
I've got a fairly complex compass.rb file.  Is it possible to tell Scout to use this file rather than specifying all of the directories manually?

**Comment by MortimerNeuss** [comment]
That was very helpfull Darkwing371, thank you!

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 is Node-based, and no longer relies on Ruby. Since Compass only runs on Ruby, we now only support Compass Mixins and not full Compass support.

Closing this issue as "will not fix".

* [Scout-App 2](http://scout-app.io) (2016)
