### ISSUE TITLE
Sass doesn’t like foating point decimals.

### ISSUE THREAD

**Issue by Darkwing371** [scout-app/scout-app#111]
First: this issue has nothing to do with the Sass::Script::Number.Precision. That is fine!

Second: This is a re-post of my formerly opened issue in the https://github.com/nex3/sass/issues/694 since the problem is assumed to be Scout-related.
_____________________________________________________

The past three hours I was going nuts seeing Sass 3.2.1 (Scout 0.7.1, Win 7 x64) calculating the same math operation with two different outcomes between two compilings. It’s insane!

I simply tried to convert centimeters to inches by doing:

      $cm: 1;
      $in: $cm / 2.54;

After saving (compiling), the outcome was: 0.3937, as one would expect.
After saving again, however the outcome was: 0.5. My boy, my boy!

And so Sass seems to choose the result at random, at every saving (compiling); but most of the time the wrong result as far as I could see.

It took me tree hours to narrow the problem down inside of my mixins.
What is going on now is pretty clear to see in my minified examples: sometimes Sass forgets, that there are some numbers present behind the decimal point. It calculates 1 / 2 = 0.5.

I wonder that so few people have this problem – am I the only one who noticed this?
It was hard to google for this.
I only found some related problems, also concerning floting points (maybe theres the same underlying problem):

https://github.com/mhs/scout-app/issues/22
https://github.com/mhs/scout-app/issues/41
https://github.com/mhs/scout-app/issues/44
https://github.com/mhs/scout-app/issues/103
https://github.com/mhs/scout-app/issues/105

So far by the comments it seems to be narrowed down to that it is no promlem with Compass or Scout, it must be Sass itself. Although Sass-People were quick to say otherwise: https://github.com/nex3/sass/issues/694#issuecomment-15276612.Maybe they’re right …?

______________________________________________

For the moment I found out that to abstain from typing floating points will solve this problem! Like so:

    $cm: 1;
    $factor: 254;
    $factor: $factor / 100;
    $in: $cm / $factor;

Luckily at least this is possible. Or shorter:

    $cm: 1;
    $in: $cm / 254 / 100;

So when a floating point occurs via "hidden calculation" inside of variables, this problem seems not to happen  – so no one needs to be scared. Only when typed directly, then this weired loss of decimals occurs.

And notice whats also a problem:

    $cm: 1;
    $factor: 2.54;
    $in: $cm / $factor;

Makes 0.5.
Almost all the time.
It seams that the first time Sass gets it right, all the other times Sass cancels the decimals.

Btw: this also occurs when multiplying, oder adding, or subtracting:

     $in: 1 + 2.54;

Makes 3. This is just ridiculous.

_______

So: do not type floating point decimals until this is fixed.
       
______________

For everyone whos encountering this error too, I wrote a little workaround-function to fix this.

      @function floatfix($value: 100, $decimals: 2) {
          @for $i from 1 through $decimals { $value: $value / 10; }
      @return $value;
      }

Usage:

    $var: floatfix(12345, 3);

is like $var: 12.345;

Maybe it’s of some use for someone.
Maybe less annoying than typing $var: 12345 / 1000;

Remember you can rename that function if "floatfix" seems too long for practical use.

**Comment by pisciottaf10** [comment]
Any news?

**Comment by hugobqd** [comment]
allways the same problem

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Download the latest version of Scout-App. If the problem still exists create a new issue.

* [Scout-App.io](http://scout-app.io)
