### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by adam-lynch** [scout-app/scout-app#112]
I'm on Windows 8 and I don't know if it's just me but I find it hard to read text in Scout, especially text in the console.
![Capture](https://f.cloud.github.com/assets/1427241/322413/0c3762fa-9a4a-11e2-933c-4bb443d0904b.PNG)

That thumbnail is very readable to me but open up the image to its full size to maybe get an idea of what I mean. 

Compare the two following screenshots:
![Capture2](https://f.cloud.github.com/assets/1427241/322415/59a5124e-9a4a-11e2-9f57-8a9f5ed438a1.PNG)
cmd:
![Capture4](https://f.cloud.github.com/assets/1427241/322419/85f633c8-9a4a-11e2-931c-ef709ff9ad88.PNG)

**Comment by fjacot** [comment]
Hi,

I have exactly the same issue. Did you find out how to change colors and background color of the console ?

**Comment by adam-lynch** [comment]
No @fjacot, haven't used it since.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing ticket. Download the latest version of Scout-App which comes with many different built in themes.

* [Scout-App 2](http://scout-app.io) (2016)
