### ISSUE TITLE
Creating sprites

### ISSUE THREAD

**Issue by anthonyartese** [scout-app/scout-app#113]
I've been trying to find documentation on this. In scout can you do "@import "*.png";"   once you have specified your images folder?

I'm getting this error:
error screen.scss (Line 5: File to import not found or unreadable: *.png.
Load paths: C:/wamp/www/compass/scss C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/frameworks/blueprint/stylesheets C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/frameworks/compass/stylesheets C:/Program Files (x86)/Scout/vendor/gems/gems/compass-960-plugin-0.10.4/stylesheets C:/Program Files (x86)/Scout/vendor/gems/gems/yui-compass-plugin-0.3/stylesheets C:/Program Files (x86)/Scout/vendor/gems/gems/compass-h5bp-0.0.5/stylesheets C:/Program Files (x86)/Scout/vendor/gems/gems/zen-grids-1.2/stylesheets Compass::SpriteImporter) overwrite screen.css

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 is Node based and since Compass only runs on Ruby, the new version only supports Compass Mixins. Sprite mapping is no longer available.

* [Scout-App.io](http://Scout-App.io)

Closing issue as "will not fix".
