### ISSUE TITLE
LoadError - How to Troubleshoot?

### ISSUE THREAD

**Issue by watermelonkid** [scout-app/scout-app#114]
When trying to add a custom mixin to my project (https://github.com/heygrady/compass-photoshop-drop-shadow), I simply cannot avoid this error in the Scout log:

LoadError on line 1038 of org/jruby/RubyKernel.java: no such file to load -- compass-photoshop-drop-shadow

When I check my gem list, it's there. I've required it in the config.rb and pointed Scout to it in the configuration pane. Finally, I've imported the mixin to my .scss file, but when I try to use the mixin, I get a LoadError. I've googled all over and spent a few hours tonight trying different things with nothing to show for it.

Perhaps someone could suggest to me if it's Scout-related, environment-related, etc.? Just looking for a little traction!

![Screen Shot 2013-04-03 at 12 22 09 AM](https://f.cloud.github.com/assets/1494060/332397/dcfc52fa-9c26-11e2-9163-de99e7a7c346.png)

**Comment by TheJaredWilcurt** [comment]
Issure Resolved. Closing issue. Scout-App 2 no longer relies on Ruby, Java, or Adobe Air. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://scout-app.io)
