### ISSUE TITLE
background-image : image-url doesn't work

### ISSUE THREAD

**Issue by Gozuu** [scout-app/scout-app#115]
Hello,

I'm discovering Scout and Compass so I hope you can help me about my issue. 
After installing Adobe Air App, I configured my projects, I changed in Scout, Images Folder : /Users/Gozuu/workspace/compass/img.

Therefore, in my SCSS, I have : 

#bg
{    
   background-image : image-url("test.jpg");
}

It's converted in my CSS : 

#bg 
{
  background-image: url('/images/test.jpg');
}

I did not understand so I tried to create a file called config.rb, I configured it in in Scout, Config File :

images_dir = "../img"
result in CSS : background-image: url('/../img/test.jpg');

I'm closer but what I have a "/" ? 

Could you bring me an answer because I'm lost. Thx

Gozzu

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://scout-app.io)
