### ISSUE TITLE
no config file scout

### ISSUE THREAD

**Issue by DR-Design-Development** [scout-app/scout-app#116]
I've just downloaded Scout.app and I've just began to compile with this application instead than with the terminal. Its much more simple and more organized. But I some doubts. 

1. I have the option to place my config file with my Scout. The issue is that if I press this button nothing happens. So I cannot place a config file. Any ideas why not?
![SCOUT](https://f.cloud.github.com/assets/4056520/337912/e45bc300-9cf8-11e2-9137-587f684f0f54.png)

2. I want to have a config file for sharing purposes. Do I need a config file for sharing purposes? What is the course to follow? As I think if I don't have this config file I cannot share it, or am I wrong?

Thanks!

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
