### ISSUE TITLE
i shall return to linux

### ISSUE THREAD

**Issue by nousename** [scout-app/scout-app#117]
Fill in all the configure parts, nothing happens, can press nothing.

Restart the app, and get the error [app:/views/production.html#][09:39:14] ArgumentError: Error #3214 - which tells me, basically to uninstall this and ssh to my box instead

**Comment by ArtbyArjan** [comment]
You need Java installed (and if you do, you need a different version)
Search the other issues for #3214 to find the proper solution

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 officially supports several popular Linux distros. See the website for more details

* [Scout-App.io](http://scout-app.io/#minreqs)

Issue resolved. Closing this issue. Download the latest version of Scout-App.
