### ISSUE TITLE
Growl messages for errors

### ISSUE THREAD

**Issue by timmfin** [scout-app/scout-app#12]
Is there any way that Scout could show growl notifications on errors? It is much nicer to realize that you typed a syntax error immediately, rather than wait until you've reloaded the browser.

**Comment by TheJaredWilcurt** [comment]
@timmfin @blackfalcon 

Added this to the [Project Road Map](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance) for future versions of Scout-App.

* [Scout-App.io](http://scout-app.io)

**Comment by timmfin** [comment]
While it is impressive that you are returning to issues from 5 years ago, I haven't been using scout app for a long while now. So I'm going to close this (it looks like there are plenty of other issues that  requested the same thing).

**Comment by TheJaredWilcurt** [comment]
Desktop notification settings for success and error messages have been added to the master branch. This will be in the next release of Scout-App.

**Comment by TheJaredWilcurt** [comment]
@timmfin @blackfalcon @zdennis 

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
