### ISSUE TITLE
effects and animations don't work with cached files

### ISSUE THREAD

**Issue by amanda--** [scout-app/scout-app#121]
While working in multiple sass files the caching of files stops effects like shadows from displaying and all animations stop working as well.

It makes the workflow a hassle: I've got to manually delete de cache files and change something in a sass file to compile new css files to see the site the way it's supossed to work.

Is there another way to prevent this from happening?

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this issue. Download the latest version of Scout-App. If the problem still exists create a new issue.

* [Scout-App.io](http://scout-app.io)
