### ISSUE TITLE
scss filenames starting with _ not found by Scout

### ISSUE THREAD

**Issue by majimekun** [scout-app/scout-app#122]
I just stumbled upon it today and replicated the bug before posting.
Removing the underscore makes it work fine.

If your scss filenames start with an underscore, you get the "Nothing to compile. If you're trying to start a new project, you have left off the directory argument." error message.

**Comment by TheJaredWilcurt** [comment]
This is intended functionality. Closing this issue.

* [Scout-App 2](http://scout-app.io) (2016)
