### ISSUE TITLE
Scout does not recognize non-Scout installed gems

### ISSUE THREAD

**Issue by mrzeph** [scout-app/scout-app#126]
Is it possible to make it so that scout can recognize external gems, or have gems installed? I'm trying to use a framework called Gumby, which makes use of modular-scale and sassy-math. I'm sure that most people would want to be able to import or link to their own gems. I've never developed with any of the tools, AIR, Rails, Compass, etc, but if it's merely a matter of editing a line in a config file to have Scout's local version of compass recognize them, I'm be good to go.

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 no longer relies on Ruby, Java, or Adobe Air. As such no gems will be recognized or used by Scout-App.

* [Scout-App.io](http://scout-app.io)

Closing this issue as "will not fix".
