### ISSUE TITLE
You must compile individual stylesheets from the project directory

### ISSUE THREAD

**Issue by Kamilius** [scout-app/scout-app#127]
Hi. After installing update for Scout, it doesn't want to compile scss in my current project anymore. I've didn't changed any paths and such. Only thing i did - updated compass.
Would be very appriciated for helping me out in this.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this issue. Download the latest version of Scout-App. If the problem still exists create a new issue.

* [Scout-App.io](http://scout-app.io)
