### ISSUE TITLE
Compile speed hits crawl with over 1k lines in scss file

### ISSUE THREAD

**Issue by Badgerswork** [scout-app/scout-app#128]
I have just got to over 1050 lines in my main css file and now the compile speed has really slowed down - was taking about 5 secs, now takes about 3 mins to compile every time

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Scout-App 2 is considerably faster than Scout-App Classic. Download the latest version. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-app.io)
