### ISSUE TITLE
Support for Sass source maps?

### ISSUE THREAD

**Issue by brainmonger** [scout-app/scout-app#129]
I tried to activate source maps for debugging Sass but it looks like I'm missing a way to add the debug flag in Scout. Any ideas?

http://snugug.com/musings/debugging-sass-source-maps

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
