### ISSUE TITLE
Change order or projects

### ISSUE THREAD

**Issue by iSpaceGitHub** [scout-app/scout-app#130]
Not really an issue, but a feature request:
It would be nice if it were possible to change the order of the projects configured in ScoutApp (running it on Windows 7). Could this be added in a future version?
Thanks for the great app, use it every day!

**Comment by TheJaredWilcurt** [comment]
This feature request has been added to the [Project Road Map](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance) for future versions of Scout-App.

**Comment by TheJaredWilcurt** [comment]
I've added this in the latest master branch. It will be in the next release.

**Comment by TheJaredWilcurt** [comment]
@iSpaceGitHub

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
