### ISSUE TITLE
load File.join not working (sencha touch config)

### ISSUE THREAD

**Issue by Tjorriemorrie** [scout-app/scout-app#131]
The Sencha Touch config:
````
# Get the directory that this configuration file exists in
dir = File.dirname(__FILE__)

# Load the sencha-touch framework automatically.
load File.join(dir, '..', '..', 'touch', 'resources', 'themes')

# Compass configurations
sass_path = dir
css_path = File.join(dir, "..", "css")

# Require any additional compass plugins here.
images_dir = File.join(dir, "..", "images")
output_style = :expanded
environment = :development
````

In Scout the Stylesheet Directories are empty and the Config file above is set. It doesn't matter what the Input Folder is; the path of the error stays the same.

It' gives the error: 
> Compass::Error on line 61 of C: File not found or cannot be read: C:\xampp\htdocs\myapp/stylesheets/fonts/pictos/pictos-web.woff

Which is located here:
![scout](https://f.cloud.github.com/assets/1099093/687529/aa0f9230-da7e-11e2-93b3-03f3974ead1c.png)

I'm not sure why it doesn't load the files: seem to be this command in the config:
````
load File.join(dir, '..', '..', 'touch', 'resources', 'themes')
````

**Comment by TheJaredWilcurt** [comment]
Closing this issue. Scout-App no longer relies on Ruby. Only Compass mixins are supported in Scout-App 2.

* [Scout-App.io](http://scout-app.io)
