### ISSUE TITLE
@import scss files always errors

### ISSUE THREAD

**Issue by griffinbyron** [scout-app/scout-app#134]
does anyone have an idea why i cant import any other files into a scss file? For example;

@import "compass/reset";
@import "compass/css3";
@import "myFonts.scss";
@import "myColors.scss"; 

keeps saying "error styles.scss (Line 34: File to import not found or unreadable: compass/myFonts.scss."

the sass files are all in the same folder and im sure ive set up the Configure correctly in the Scout project..

Please help!!!!!

**Comment by TheJaredWilcurt** [comment]
Closing this issue. Download the latest version of Scout-App. If the problem still exists create a new issue.

* [Scout-App.io](http://scout-app.io)

**Comment by viniciusnevescosta** [comment]
> 

Hi

I did the exact same thing and the error persists.

Scout-App:
![image](https://user-images.githubusercontent.com/66970818/152427062-b8d57563-8fd6-4b38-916e-bfc88a0ef2df.png)

VS Code:
![image](https://user-images.githubusercontent.com/66970818/152427202-117f57bd-9458-430a-a345-f4019641d103.png)

Any suggestion?
