### ISSUE TITLE
error with import....

### ISSUE THREAD

**Issue by griffinbyron** [scout-app/scout-app#135]
does anyone know what the issue is with this error;

error styles.scss (Line 17 of _shared.scss: Properties are only allowed within rules, directives, mixin includes, or other properties.)

I'm using the flexbox mixins from https://gist.github.com/ericam/4462761 but cant get them working....

any ideas?

**Comment by TheJaredWilcurt** [comment]
Closing this issue. Download the latest version of Scout-App. If the problem still exists create a new issue.

* [Scout-App.io](http://scout-app.io)
