### ISSUE TITLE
Errno::EACCES on line 441 of org/jruby/RubyFile.java: Permission denied

### ISSUE THREAD

**Issue by jonuday** [scout-app/scout-app#136]
Scout is unable to compile and this error is logged. Looking for suggestions on ruby permissions and scout. Thanks.

**Comment by AndreaBlick** [comment]
Ditto - I've tried updating with the various Java Updates, e.g. http://support.apple.com/kb/DL1572?viewlocale=en_US&locale=en_US but no success. I've recently updated to OS X Yosemite Version 10.10.1. Colleagues have done the same and don't get that error though...

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Ruby, Java, or Air.

* [Scout-App 2](http://Scout-App.io) (2016)
