### ISSUE TITLE
Compass: "@include transition" is an undefined mixin

### ISSUE THREAD

**Issue by jassibacha** [scout-app/scout-app#138]
>>> Change detected at 16:59:52 to: app.scss
error app.scss (Line 34: Undefined mixin 'transition'.)

Line 34 is: @include transition(all 0.35s ease-in-out);

Which I used from http://stackoverflow.com/a/14301325

Is Scout not using the newest version of compass or something? Just curious, thanks!

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
