### ISSUE TITLE
String error?

### ISSUE THREAD

**Issue by blackfalcon** [scout-app/scout-app#14]
This may be a bit wonkey, but this works in a ruby development environment.  
Sass 3.1.7 (Brainy Betty)
Haml 3.1.2 (Separated Sally)

The code:
@mixin linear_gradient_w3c ($default_color, $color_values, $prefixes: $prefix_defaults) {
	// default fallback //
	background: $default_color;
	@each $prefix in $prefixes {
		background: #{$prefix}linear-gradient(top, $color_values);
	}
}

The error:
Syntax error: Not a valid color stop: Sass::Script::String: white 0%, white 40%, #f8f9f9 41%, #f8f9f9 55%, #f2f3f4 56%, #f2f3f4 100%
        on line 12 of /Desktop/test/sass/imports/gradients/_area_51.scss, in `linear_gradient_w3c'

**Comment by TheJaredWilcurt** [comment]
Issue presumed resolved. Closing this issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
