### ISSUE TITLE
How are the JavaScript and Images folders used?

### ISSUE THREAD

**Issue by gabriel-r** [scout-app/scout-app#140]
Just curious, what are the JavaScript and Images folders used for?
The documentation doesn't mention these at all.

![scoutapp___the_sass_compass_gui](https://f.cloud.github.com/assets/51084/987109/5f5cf648-08e5-11e3-89d4-6092d5055fa1.jpg)

**Comment by TheJaredWilcurt** [comment]
These 2 fields have been removed from Scout-App 2. The latest version of Scout-App only supports Compass Mixins. Compass based sprites are not supported anymore. If we ever implement a Node-based Compass-like feature into Scout-App 2+, this section may return, however in separate, more intuitive view.

Closing issue.
