### ISSUE TITLE
Decimal on Mac OSX

### ISSUE THREAD

**Issue by chatelain** [scout-app/scout-app#141]
Hi,
I'm a Mac OSX v. 10.8.4 user.

When i am trying to compil scss files containing variables with decimal value into css file, it compils this way (except the first time):

scss:
$font_large: 1.4em;
$color: rgba(#345, 0.7);

span#logo {
    font-size: $font_large;
    background-color: $color;
}

css:
span#logo {
    font-size: 1em;
    background-color: rgba(#345,0);
}

Note:
why there's no auto prefix option in kind of prefixr ?

thank you

Jérôme, Swiss based webdesigner and webdeveloper.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
