### ISSUE TITLE
output directory not sticking

### ISSUE THREAD

**Issue by jasonday** [scout-app/scout-app#143]
Issue:

create new project
select directory /dev
select input folder /dev/sass
select output folder /sass-compiled (notice sibling of /dev)

changes are not compiling to output.
Check output folder and it has changed to /dev

Thoughts?

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
