### ISSUE TITLE
Installation problem in Windows 7

### ISSUE THREAD

**Issue by kunalsh** [scout-app/scout-app#144]
When i click on the play button in the app for converting sass file in css then its shows me 
![buf](https://f.cloud.github.com/assets/5555958/1224381/f7182846-2748-11e3-8efb-6387cacd5a1f.png)

Can you help me out in this.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
