### ISSUE TITLE
Add readme.md to state dependencies

### ISSUE THREAD

**Issue by thewinterwind** [scout-app/scout-app#145]
I was getting this error:

https://github.com/mhs/scout-app/issues/19

I think it will be fixed once I have Java installed, like I do on my other machines.

The readme should state the four things that need to be installed on the machine first.

1. Java
2. Ruby
3. gem install sass
4. gem install compass

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air, Java, or Ruby.

* [Scout-App 2](http://Scout-App.io) (2016)
