### ISSUE TITLE
ArgumentEoor #3214

### ISSUE THREAD

**Issue by SpaceCase71** [scout-app/scout-app#146]
I run Win 8.1 from MSDN.  I installed Scout App.  When I try and run a project, the ADOBE AIR Introspector pops with [app:/views/production.html][16:42:27] ArgumentError: Error #3214

**Comment by PetrusMGirnus** [comment]
On Win  8:
Navigate to C:\Program Files (x86)\Scout\javascripts\app\process_interaction.js

make sure edit  security privilege so you can edit the code. On the very bottom is the function javaDir() 
go ahead make sure that the path matches the one in C:\Program Files (x86)\Java\jre1.8.0_45\bin.exe 

like so,

  if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_45\\bin\\java.exe");

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
