### ISSUE TITLE
File is not saved in output folder

### ISSUE THREAD

**Issue by satya61229** [scout-app/scout-app#147]
In Configure, I have entered Input and Output folder differently. 

Stylesheet:
Input Folder: D:\wordpress361\wp-content\themes\satyaweblog\sass\

Output Folder: D:\wordpress361\wp-content\themes\satyaweblog\

As, style.css should be in theme folder so I have given that way. But *.css file is getting generated in sass/* folder.

- - - - - - 
Also, possibly, the value does not preserve when path is entered by pasting there. I closed the app and to my surprise, I found there is no value. When I use "Choose" button to fill path then it persist. 

I am using Window 7.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
