### ISSUE TITLE
You must compile individual stylesheets from the project directory

### ISSUE THREAD

**Issue by cdCorey** [scout-app/scout-app#148]
When I try to use Scout, I get this error:

"You must compile individual stylesheets from the project directory."

Any idea why that happens or how to fix it?

**Comment by ilovemygameboy** [comment]
Same here (Mac). Did press "Remove" under Manage Project > Remove Project. Made a new config. Now working again.
![image](https://cloud.githubusercontent.com/assets/3972493/9130286/d3f20674-3ce1-11e5-80fb-f9bd18ba9f1c.png)

**Comment by krishnaDandu** [comment]
fchristant and ilovemygameboy are right and you solved my issue in a few second where am creaking my where is mistake i have done?, Thanks to you both.
Just add new config to same/new location in scout it will work.

**Comment by DeeMacD** [comment]
I removed the project from scout and re-added it again. My folder name had changed, just pointing it to the new one doesn't seem to register.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
