### ISSUE TITLE
Friendlier error messages

### ISSUE THREAD

**Issue by davatron5000** [scout-app/scout-app#15]
I'm not sure how feasible this is, but a less verbose stack trace would be awesome (only the first 2 lines?).  From a frontend HTML/CSS perspective, I'll never be touching touching the `/Applications/Scout.app/Contents/Resources/vendor/gems/gems/sass-3.1.7/lib/sass/scss/parser.rb` portion of the app.

All that gobbledygook will be a major turn off to designers and impede adoption.

Thanks!

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 has friendly, user-centric error alerts and success messages.

![Screenshot](http://scout-app.io/_img/screenshots/win/22.png)

Closing this issue.

* [Scout-App.io](http://scout-app.io)
