### ISSUE TITLE
Not allowing access to networked server

### ISSUE THREAD

**Issue by mkasson** [scout-app/scout-app#150]
I click + to add a new folder. I select a folder on the LAN (//server/Mark/Sass), however when I start it running, I get "C:/Documents and Settings/Mark\\server\Mark\Sass does not exist."

Can't change it under Configure either.  Same error.

Thanks!!

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
