### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by MikeAdamowicz** [scout-app/scout-app#151]
I'm on Windows 8.1 using Sublime Text build 3047 and Scout loaded with compass. The problem I'm encountering is that after about 1/2 hour to 45 min, I continually run into an error when trying to save the .scss file.  See this image for the error details:
![error](https://f.cloud.github.com/assets/6062455/1642452/47db0da4-5884-11e3-8c83-f7503b67dd5b.jpg)

I believe that this is an issue with Scout because when I run compass on my ruby 2.0.0p247 (2013-06-27) [x64-mingw32], I can go along forever with no errors when trying to save the .scss file.

Admittedly a newbie to Github, I hope this is the correct place to list this.

Any help is much appreciated.

**Comment by bubba169** [comment]
+1

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
