### ISSUE TITLE
A lot of errors

### ISSUE THREAD

**Issue by fortarrigo** [scout-app/scout-app#152]
Hi!
If I try to compile my project, Scout show me the errors in the image.

I have the last version of java, AIR and Scout installed and Win7 Home Premium OS

What can I do to fix this problem?

Thanks in advance for your help
![scouterrors](https://f.cloud.github.com/assets/5670496/1665810/d2ebe718-5c3c-11e3-9b0b-b7006797f17e.jpg)

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
