### ISSUE TITLE
"Install Scout" can't be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by struex** [scout-app/scout-app#153]
Hi,

I downloaded the installer from your website and get the following message when trying to open it:

"Install Scout" can't be opened because it is from an unidentified developer.

Actually, I subsequently discovered that I already have the application :) but thought you should know about this issue.

Cheers,
Stephen

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App.io](http://Scout-App.io)
