### ISSUE TITLE
Values between 0 and 1 sometimes get rounded to 0

### ISSUE THREAD

**Issue by exophunk** [scout-app/scout-app#154]
I cannot reproduce this error continuously, but if I use

.item { background: rgba(white,0.5); }

it works usually, but every 5 to 10th compile with Scout, the element has no background. After removing the code and adding it again, it's there again.

So sometimes the color with opacity values get ignored...

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
