### ISSUE TITLE
Show the bash command being executed

### ISSUE THREAD

**Issue by georgestephanis** [scout-app/scout-app#157]
Issue: It's currently (I believe) impossible to find the generated bash command that the current configuration options generate.

Proposal: Add a readonly textarea that displays the bash command that the current project's settings would execute.  Alternately, display it at the top of the 'log' window when it's being run.

Gains: This would make it easier for open source projects to display the appropriate bash commands and lower the barrier of having installed Scout to contribution.  It could also make it easier and more transparent to automate, as well as potentially help with debugging (to see if something's changed in an update)

**Comment by TheJaredWilcurt** [comment]
The newest version of Scout-App (2016) is quite different than Scout-App Classic (2012). I'm not sure if your request would still be relevant.

Closing this ticket. Feel free to create a new one based on your opinions of the latest version.

* [Scout-App.io](http://scout-app.io)
