### ISSUE TITLE
@import not working with folders containing special chars 

### ISSUE THREAD

**Issue by jacksbox** [scout-app/scout-app#159]
I just encountered a bug, if the css/sass folders in your project, or the folders in the path to your project contain chars like [ ] . (I just tested this three).
If that´s the case the @import statement will throw the following error " file to import not found or unreadable: scssfilename.".

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
