### ISSUE TITLE
Sound notification on error

### ISSUE THREAD

**Issue by ryanbeymer** [scout-app/scout-app#161]
Scout is great, my typical development starts with firing all the tools up and making sure everything is good. The problem is when there is an error, I usually don't find out until I don't see my changes on the page. 

It would be great if there could be a simple beep let me know there was an error.

**Comment by TheJaredWilcurt** [comment]
I've added this to the [Project Road Map](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance) for future versions of Scout-App.

**Comment by TheJaredWilcurt** [comment]
Error and Success Alerts now have sound effects play by default, but can be disabled in the settings. This feature has been merged into the master branch and will be in the next release of Scout-App.

**Comment by TheJaredWilcurt** [comment]
@ryanbeymer @cookch10 

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
