### ISSUE TITLE
Sprite_load_path relative path error

### ISSUE THREAD

**Issue by nathasha** [scout-app/scout-app#164]
Scout is throwing an error when relative path is used for sprite_load_path.  Eg:  sprite_load_path << "../../common/img". 

When I run this on compass, it works. Any idea why? 

config.rb -
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "img"
http_generated_images_path = "/apps/testapp/img"
add_import_path  "../../common/sass"
sprite_load_path << "../../common/img"

**Comment by TheJaredWilcurt** [comment]
The latest version of Scout-App only supports Compass Mixins. Compass based sprites are not supported anymore. If we ever implement a Node-based Compass-like feature into Scout-App 2+, relative paths will most likely be supported.

Closing issue as "will not fix".
