### ISSUE TITLE
Scout white screen on Retina MBP and Latest Mavericks

### ISSUE THREAD

**Issue by netsmith** [scout-app/scout-app#166]
When installing on a new retina macbook pro, with the latest Mavericks on it. When I run scout up, the window opens but it remains blank. If I quit the app it then crashes.

I've deinstalled and reinstalled several times (AppZapping it for completeness) but always get the same symptom

Any ideas?
Chris

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App.io](http://Scout-App.io)
