### ISSUE TITLE
export project configurations

### ISSUE THREAD

**Issue by D3m1urg0** [scout-app/scout-app#167]
Hello,
i need to duplicate the projects configurations on many different machines (projects are on a cloud folder, but i cant find a "portable" scout version, so i need to just overwrite each new compass installation with the same list of preconfigurated project)

is there a file with the projects configuration i can copy and paste in the other computers?

sorry for my bad english

P.

**Comment by TheJaredWilcurt** [comment]
@D3m1urg0 

The [2016 version of Scout-App](http://Scout-App.io) is quasi-portable. There is a user-specific settings file located here:

* **Windows:** `%LOCALAPPDATA%/scout-app/scout-settings.json`
* **Linux:** `~/.config/scout-app/scout-settings.json`
* **OSX:** `~/Library/Application Support/scout-app/scout-settings.json`

Besides that file, everything else is contained in the app's folder and can be ran from anywhere and does not require installation.

So you could copy that settings file and paste it on multiple machines. However the projects in the settings file are linking to the full path of the the project folders/files. So unless the locations on each machine are identical, it wouldn't matter.

    {
        "projectID": "sa1472063939517",
        "projectFolder": "C:/Users/GLR/Documents/GitHub/UGUI-Defluff",
        "projectName": "UGUI-Defluff",
        "imageFolder": "C:/Users/GLR/Documents/GitHub/UGUI-Defluff/_img",
        "projectIcon": "C:/Users/GLR/Documents/GitHub/UGUI-Defluff/_img/logo.png",
        "inputFolder": "C:/Users/GLR/Documents/GitHub/UGUI-Defluff/_sass",
        "outputFolder": "C:/Users/GLR/Documents/GitHub/UGUI-Defluff/_style",
        "environment": "production",
        "outputStyle": "compressed"
    },

On the plus side, Scout-App 2's auto-import screen can make this process so easy you won't even need to bother with copying settings files. It will auto-guess all your project's information.
