### ISSUE TITLE
Scout App License

### ISSUE THREAD

**Issue by BandonRandon** [scout-app/scout-app#168]
What license is Scout under? As the code is available for free on github one can assume it's open-source but there are just so many to choose from. It is very important to define a license to protect yourself (and others) 

See: http://choosealicense.com/
and 
http://www.openparenthesis.org/2013/07/22/github-on-licensing

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 uses MIT.

All licenses for Scout-App and it's component parts are listed here:

* https://github.com/scout-app/scout-app/tree/master/License

Closing this issue.
