### ISSUE TITLE
Syntax Error: An @include has been found: respond includes itself

### ISSUE THREAD

**Issue by JesseGunzel** [scout-app/scout-app#170]
I receive this error as soon as I run scout from a new configuration. I have not made any changes to the scss file so I don't understand why the file is trying to be compiled anyway.
Anyone run into this issue? Is this valid scss below?

@mixin links( $l-color, $l-decor, $h-color: $l-color, $h-decor: $l-decor, $v-color: $l-color, $v-decor: $l-decor, $a-color: $h-color, $a-decor: $h-decor ) {
  &:link     { color: $l-color; text-decoration: $l-decor; }
  &:visited  { color: $v-color; text-decoration: $v-decor; }
  &:hover    { color: $h-color; text-decoration: $h-decor; }
  &:active   { color: $a-color; text-decoration: $a-decor; }
  
  @include respond(tablet) {
    &:link, 
    &:visited, 
    &:hover    { color: $l-color; text-decoration: $l-decor; }
    &:active   { color: $a-color; text-decoration: $a-decor; }
  }
  @include respond(mobile) {
    &:link, 
    &:visited, 
    &:hover    { color: $l-color; text-decoration: $l-decor; } 
    &:active   { color: $a-color; text-decoration: $a-decor; } 
  }
}

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
