### ISSUE TITLE
The application doesn't open

### ISSUE THREAD

**Issue by ghost** [scout-app/scout-app#171]
The application doesn't open with Adobe Air 13.0.

this is the exception that is throwing:

![image](https://cloud.githubusercontent.com/assets/7316858/2721928/3b5358d8-c581-11e3-973a-7f11f06e7c0b.png)

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
