### ISSUE TITLE
Scout doesn't work on Mac OS 10.10

### ISSUE THREAD

**Issue by tmaschino** [scout-app/scout-app#174]
![screen shot 2014-07-03 at 8 57 31 pm](https://cloud.githubusercontent.com/assets/4371262/3477317/624927f6-0316-11e4-8a8e-1cf537985b92.png)

Scout keeps saying that Java is not installed. I was running Java 7 update 60 earlier. I updated to the beta release of Java 8 and Scout still will not recognize that Java is installed. I've attached a screenshot of the message.

**Comment by joaorockjr** [comment]
it works

Tks
