### ISSUE TITLE
How do I use SASS?

### ISSUE THREAD

**Issue by riverleaf** [scout-app/scout-app#176]
CSS Tricks makes it sound easy, but there is no connection to real app interfaces like Scout. SASS Basics http://sass-lang.com/guide is TOTALLY NOT BASIC. Latter resource, read the Import section without knowledge of how-to, and it is gibberish. SASS is like @media WIX dumps at Envato: a plague of creepy de-liquefied liquid @margin chunkies in a bondage club. Please don't refer me to slurred speech 'Getting Started with Scout App in 2 minutes HD - YouTube' - yet more steroids and Heavens knows what! Hint for teacher: CSS Tricks (started) with a working example, but as with 99.999% of the bondage culture, sample lost in transit. btw I am happy building my boxing.css per Paul Irish 2004. SASS could be curiosity, or sincere medical concern. Can anyone in the SASS club slow down enough to explain with absolute calm sobriety, how to Scout Sass?

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App.io](http://Scout-App.io)
