### ISSUE TITLE
Have to save twice or more to livereload to update my page

### ISSUE THREAD

**Issue by hatfab** [scout-app/scout-app#177]
Hi, I meet a problem with  SCOUT+LIVERELOAD+CHROME : I have to save twice or more times in Sublime text 3 for my web brother to update my page in Chrome. The css file is well updated but the web browser don't update until I save several times. Another problème is with this commande : "background-color: rgba(red, 0.2);" it translate it en "background-color: rgba(255, 0, 0, 0);" and don't write well the a channel. Any idea of what's appening ?
Thank you
(excuse my poor english…)

**Comment by TheJaredWilcurt** [comment]
The new version of Scout-App is considerably faster than the 2012 version. Closing this ticket. Download the newest version and try it. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
