### ISSUE TITLE
Renaming projects

### ISSUE THREAD

**Issue by pelofitness** [scout-app/scout-app#179]
I've created two projects in Scout, but when I look at the listing on the left column of the app, they are both called "sass". Is there a way to rename them so I can identify the projects they are associated with?

**Comment by garypaul** [comment]
You should be able to double click on the name and rename. BOOM! done.

**Comment by TheJaredWilcurt** [comment]
This has been added to the Project Road Map for future versions of Scout-App:

* https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance

**Comment by TheJaredWilcurt** [comment]
Feature has been implemented into the master branch. Will be in the next release.

Closing this issue. I'll notify you guys when the next version of Scout-App is released.

**Comment by TheJaredWilcurt** [comment]
@pelofitness @garypaul 

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
