### ISSUE TITLE
Reading cache issue

### ISSUE THREAD

**Issue by mollycampbell14** [scout-app/scout-app#183]
I've started getting this error, any ideas?

Warning. Error encountered while reading cache /Users/mollycampbell/sites/cms/trunk/html/css/sass/.sass-cache/39ffbbb31faac60b232e0bde4e2b45ade6234e1d/vzsresponsive.scssc: load error: builtin/java/java.lang -- java.lang.OutOfMemoryError: Java heap space
JavaClass.java:834:in `installClassFields': java.lang.NullPointerException
from JavaClass.java:701:in `setupProxy' from Java.java:524:in `createProxyClass' from Java.java:453:in `getProxyClass' from Java.java:453:in `getProxyClass' from Java.java:453:in `getProxyClass' from Java.java:362:in `getInstance' from JavaUtil.java:165:in `convertJavaToUsableRubyObject' from RuntimeHelpers.java:1029:in `checkJavaException' from RuntimeHelpers.java:1053:in `isJavaExceptionHandled' from RescueNode.java:197:in `handleJavaException' from RescueNode.java:141:in `interpretWithJavaExceptions' from RescueNode.java:110:in `interpret' from BeginNode.java:83:in `interpret' from NewlineNode.java:104:in `interpret' from ASTInterpreter.java:75:in `INTERPRET_METHOD' from InterpretedMethod.java:147:in `call' from DefaultMethod.java:163:in `call' from CachingCallSite.java:292:in `cacheAndCall' from CachingCallSite.java:135:in `call' from /Applications/Scout.app/Contents/Resources/bin/compass:12:in `__file__' from /Applications/Scout.app/Contents/Resources/bin/compass:-1:in `load' from Ruby.java:671:in `runScript' from Ruby.java:575:in `runNormally' from Ruby.java:424:in `runFromMain' from Main.java:278:in `doRunFromMain' from Main.java:198:in `internalRun' from Main.java:164:in `run' from Main.java:148:in `run' from Main.java:128:in `main'

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
