### ISSUE TITLE
@for not working properly when <start> is greater than <end>

### ISSUE THREAD

**Issue by bastiantowers** [scout-app/scout-app#184]
Using a @for works great when the @for increments from <start> through <end>.
According to Sass documentation, when <start> is greater than <end> the counter will decrement instead of increment; but when you implement this on your sass project, its not generating any output when deploying with Scout.

Thanks!

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
