### ISSUE TITLE
Upgrade Compass/SCSS

### ISSUE THREAD

**Issue by mejiaj** [scout-app/scout-app#185]
Scout is still using Compass 0.12.2 and Sass 3.2.1 (August 2012!). Current version for Compass is 1.0.1 (August 2014) and Sass 3.4.5 (Sept 2014)

**Comment by TheJaredWilcurt** [comment]
@bastiantowers @garypaul @brunnopleffken 

Try out the new version of Scout-App and let us know what you think.

* [Scout-App.io](http://scout-app.io)
