### ISSUE TITLE
issue Load error

### ISSUE THREAD

**Issue by Fantazero** [scout-app/scout-app#189]
i get this message after configure scout on a win 7 machine

loadError on line 1038 of org/jruby/RubyKernel.java: no such file to load -- compass-normalize
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require' C:\wamp\www\sass\sites\all\themes\fr_sass/config.rb:44:in `parse_string' org/jruby/RubyKernel.java:1088:in `eval'
C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:24:in `parse_string' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:15:in `_parse' org/jruby/RubyIO.java:1111:in `open' org/jruby/RubyKernel.java:298:in `open' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:14:in `_parse' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:7:in `new_from_file' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/inheritance.rb:204:in `with_defaults' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:6:in `new_from_file' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:42:in `configuration_for' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:97:in `add_project_configuration' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:31:in `add_project_configuration' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:25:in `configure!' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:15:in `initialize' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/update_project.rb:37:in `initialize' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `perform!' C:/Program Files (x86)/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!' C:\Program Files (x86)\Scout\bin\compass:12:in `(root)'

can you tell me what can i do to solve the problem ?
Thanks

**Comment by TheJaredWilcurt** [comment]
@Fantazero @Dragotic @timstallmann 

Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
