### ISSUE TITLE
ArgumentError on Windows7

### ISSUE THREAD

**Issue by kahlil** [scout-app/scout-app#19]
Unfortunately Scout throws an ArgumentError when I press the "play button" to start the console.

Here the screenshot: 

![ArgumentError](http://f.cl.ly/items/3M0I1E0V0B3S2l2B3B16/Image%202011-10-14%20at%2012.37.18%20PM.png)

**Comment by Squidies** [comment]
This doesn't really seem like a fix since whenever Java updates, the path will need to be updated and changed.

**Comment by coreylewisdesign** [comment]
@Squidies Obviously it is not a permanent fix. Just a temporary solution to get up and running and not delay ones projects until future source files are appropriately updated.

**Comment by biggamejames** [comment]
I found this fix:
function javaDir() {
   path = air.File.applicationDirectory.resolvePath("C:\\ProgramData\\Oracle\\Java\\javapath\\java.exe");
   return path;
}

The path contains variables that already exist in the Scout codebase so they will automatically pick up the path the java files.

**Comment by JensNielsen81** [comment]
How do i fix this on mac?

**Comment by biggamejames** [comment]
@JensNielsen81  Did you try the fix above?

**Comment by jpswade** [comment]
If the application cannot find java.exe on windows, then it would make sense to handle it by showing a meaningful and actionable error message.

**Comment by Ubrwgn** [comment]
Receiving the Error 3214
Running Win 10, installed latest Java Runtime Environment, installed Scout, edited the path in Scout js file to match my configuration. Still get the 3214 error. Very frustrating and a huge amount of time wasted. I'm only using this program because an online class I am taking is using it in one of the chapters regarding Sass. The course is obviously two or three years old. Since I don't see any real resolution coming from the software developers, looks like I will skip this section and try to forget that I ever heard of Scout or Sass and stick with {LESS}.

**Comment by gmt-it** [comment]
Ist running fine on Windows 10, try this and take a look at the slashes. Use no backslash under Windows and it runs fine:
<pre>
function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre7/bin/java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre7/bin/java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre1.8.0_60/bin/java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }

</pre>

**Comment by Ubrwgn** [comment]
Thank you for your reply. I followed your instructions and I still get the same error. I also use a fixed name folder for Java. I don't know if it's something else that is causing the problem or not. But the forward slashes and correct path don't fix the problem for me. I have a horrible reputation of having the unexplainable happen to me when it comes to troubleshooting software. 
Thanks for your help nonetheless.

**Comment by Ubrwgn** [comment]
I managed to eliminate the 3214 error only to receive a new error. Story of my life.

     [app:/views/production.html][15:37:37] SyntaxError: Parse error

I'm about to go rummaging through the internet to find out what that means. 
In the interest of full disclosure:  the following code got rid of the 3214 error. It's a little different that what I tried before.

function javaDir() {
   if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\Program Files\Java\jre7\bin\java.exe");
  if(!path.exists){
      path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_60\bin\java.exe");
  if(!path.exists){
      path = air.File.applicationDirectory.resolvePath("C:\Program Files\Java\jre6\bin\java.exe");
  }
}
  return path;
    } else {
  return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
}

**Comment by Ubrwgn** [comment]
While searching for answers I came across this. (Which tells me that my new error is actually still my old error in disguise.
http://bobmckay.com/web/sass-css/sass-windows-tutorial-automatic-sass-compilation/

What NOT To Try on Windows
I did a fair bit of reading and saw lots of good things written about Scout (see http://mhs.github.io/scout-app/) as well as it being right up there when I did a Google search, unfortunately this simply didn’t work for me on either my Windows 7 x64 or Windows 8 x64 systems – I kept getting the error:

[app:/views/productions.html][] ArgumentError: Error #3214

I would put this down to just bad luck and say try it anyway but lots of others reported the same problem and looking at the project’s page on GitHub shows it hasn’t been updated in over two years, making it a big no for me.

**Comment by christiansita** [comment]
Hi, 

I just solved the same problem 3214. I am using Windows 10 64-bit.
I used double slashes for the path instead of one slash: 
"C:\\Program Files\\Java\\jre1.8.0_60\\bin\\java.exe"

Hope it helps someone

**Comment by aortaFX** [comment]
gmt-in's solution works
win 10 64bit here

-downloaded newest version of java.
-changed \Scout\javascripts\app process_interaction (copy to desktop, edit, and get back to original folder)

function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre7/bin/java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre7/bin/java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre1.8.0_60/bin/java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }

**Comment by Ubrwgn** [comment]
Tried every permutation of solutions that I could find. Same error. 
     [app:/views/productions.html][] ArgumentError: Error #3214
Now I can't even get the Syntax error I got before, weird. What I really can't understand is how some people got theirs to work but I can't with the same code and system.
Question: What is the difference between copying the file, editing it and then replacing the original file in the js folder and just editing the original without making a copy? I mean I kept a copy of the original file just in case, but why is it recommended to edit a copy of the file and then put it in place of the original?

**Comment by f1ss1on** [comment]
Hey guys, I just did a pull request for the latest version to detect for the latest version of Java. The default java installation folder is now java/jre1.8.0_45/java.exe. My latest fork puts this patch in.

**Comment by f1ss1on** [comment]
I am going to see about adding a patch to automatically search for Java installs to avoid this in the future. It may take me some time as my work load is crazy now. It will happen though.

**Comment by TheJaredWilcurt** [comment]
@AAverin @amandhiman987 @AndyOwl @Anos @aortaFX @bboyairwreck @biggamejames @charleslouis @christiansita @coreylewisdesign @Daynos @diggleweb @f1ss1on @francisbyrne @fredcerdeira @gmt-it @hartogsmith @inner1beauty @JensNielsen81 @josephbona @jpswade @kahlil @klauskjeldsen @lillockey @mlarcher @neerajkbharti @nuVoid @PendragonDevelopment @rmontgomery429 @rollopack @Sawtaytoes @scottdavis @scottsandersdev @shegs-a @spsaucier @Squidies @thewinterwind @Ubrwgn @waqar-alamgir @wellstudio @yizhak

That's a lot of people.

I've got good news! Scout-App 2 no longer relies on Adobe Air or Java.

Marking this issue as resolved and closing it.

* Download **Scout-App 2** (2016) at **[Scout-App.io](http://Scout-App.io)**
