### ISSUE TITLE
Doesn't recognize that I've installed Java

### ISSUE THREAD

**Issue by avrame** [scout-app/scout-app#190]
I keep getting the message: "No Java runtime present, requesting install." in the log when I attempt to run Scout on my project even though I've installed the latest Java runtime.  I'm on OS X 10.10.1 Yosemite.

**Comment by jmaple4** [comment]
Thanks @chrismllr, your links completely fixed my issue. Cheers.

**Comment by joaorockjr** [comment]
http://support.apple.com/kb/DL1572?viewlocale=en_US&locale=en_US solved

**Comment by AndrewSepic** [comment]
Thank you @chrismllr

**Comment by TheJaredWilcurt** [comment]
For those on Windows, go here to get the correct version:

* http://ninite.com/air-java7

Java is up to version 8 now, but Scout App 0.X.X requires Java 6 or 7 be installed. You can have Java 4, 5, 6, 7, 8 all installed simultaneously, they don't conflict with each other. So just get a copy of Java 7 and Adobe Air and it should run. If you get any other error messages come back and search the issues page.

**Comment by adewalegeorge** [comment]
Thanks @lauraeagin that was a life saving http://support.apple.com/kb/DL1572

**Comment by dv2** [comment]
Download and install - https://support.apple.com/kb/DL1572?locale=en_US

**Comment by zornfett** [comment]
thanx @lauraeagin!

**Comment by TheJaredWilcurt** [comment]
@zornfett @dv2 @adewalegeorge @AndrewSepic @joaorockjr @jmaple4 @lauraeagin @joewesemann @chrismllr @e5an @avrame 

Scout-App 2 no longer relies on Java or Adobe Air.

### **[Scout-App.io](http://scout-app.io)**

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Java.

* [Scout-App 2](http://Scout-App.io) (2016)
