### ISSUE TITLE
scout confrigration run time error.. plz help

### ISSUE THREAD

**Issue by multicomak** [scout-app/scout-app#191]
![untitled2](https://cloud.githubusercontent.com/assets/3851406/5216605/f842a01c-765b-11e4-9b62-dfa608661aad.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/3851406/5216606/f849b0be-765b-11e4-802f-71d112556c5e.jpg)

**Comment by HarmOo** [comment]
Have the same problem.
and i manifested itself after i updated to Java 8

I checked comment nr 19, The line numbres have changed to 106 and down,
I notice that it checks for JRE7 and JRE 6, but nt for JRE 8

So i Added some lines to the javadir function

  function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre7\\bin\\java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre7\\bin\\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre6\\bin\\java.exe");
		  if(!path.exists){
			  path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre1.8.0_31\\bin\\java.exe");
		  }
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }

Works like a charm

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
