### ISSUE TITLE
Video sound quality

### ISSUE THREAD

**Issue by YScuba** [scout-app/scout-app#192]
I appreciate your effort with the setup video tutorial on Youtube.  The sound quality, however, is very poor.  It sounds as though you are at the bottom of a well.  Please consider re-recording using a better mic.  Thanks.

**Comment by TheJaredWilcurt** [comment]
@YScuba 

I just uploaded a new video for Scout-App 2, I'm not super happy with the audio quality. If you have any advice, let me know:

* https://www.youtube.com/watch?v=6zA78zMsH9w
