### ISSUE TITLE
Need more and better info on Scout-app web page

### ISSUE THREAD

**Issue by empulsetech** [scout-app/scout-app#193]
The home page for this app is sorely lacking in information.  I have installed it but am not sure how to use it.  SASS, SCSS, COMPASS are all new to me although I have been developing web apps. both front end and back end, since 1996 (And have been programming professionally in multiple languages since 1980).  A basic step by step beginning tutorial with examples (one or two selectors) would be very useful and save a lot of time for those of us trying to grok this thing. How does the input file need to be formatted or does it matter?

 I have read everything on the home page and followed all the links, but there are still many unanswered questions that could be easily answered with a decent intro page.  For example:  You have nothing about system requirements.  Does this run on Windows? (What versions)?, Linux? (particular distros?), Mac?.  What additional software, if any, needs to be installed? Java? Ruby? You have a link to Compass, but no indication as to whether that needs to be installed separately or if that is included.

**Comment by maryjos** [comment]
I have to agree on this, I was looking at using Scout but the completely lack of information makes it immediately unfeasible. Just something as simple as figuring out how to configure it to create both dev and production CSS files when it builds has me stumped.

**Comment by TheJaredWilcurt** [comment]
Technically you need Java 7. Scout wasn't designed with the latest version, Java 8, in mind.

**Comment by TheJaredWilcurt** [comment]
In the latest version of Scout-App, prerequisites (like Java) are no longer required.

@empulsetech I hope you can check out the new website and new version of Scout-App and let me know if there's things that can be improved, especially around making things easier for those new to Sass.

* [Scout-App.io](http://scout-app.io)

Closing this ticket. Feel free to create a new one if you have feedback on the site or app.
