### ISSUE TITLE
Link to download the app is broken

### ISSUE THREAD

**Issue by theartofpeople** [scout-app/scout-app#195]
Hi there - the links to download Scout (both Win and Mac versions) from http://mhs.github.io/scout-app/ seem to be broken today if I try to use the links from either Chrome or Firefox on Windows.

The downloads work using Safari on Mac. 

Maybe this is a temporary issue with Github itself?

**Comment by ArtbyArjan** [comment]
I download the Windows version today, and yesterday, and had no problems. Maybe it was just a hick-up on Github.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
