### ISSUE TITLE
RGBA issue

### ISSUE THREAD

**Issue by PELock** [scout-app/scout-app#197]
I have entries in my .scss files

background-color:rgba(255,255,255, 0.1);

and they are compiled to

  background-color: rgba(255, 255, 255, 0);

**Comment by douglasduartetb** [comment]
I have same problem , just waiting solve .

**Comment by nilovelez** [comment]
I have the same error, but it happens intermitently to me.
If I modify the file and Scout runs again, the file compiles fine.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
