### ISSUE TITLE
@each support

### ISSUE THREAD

**Issue by tadywankenobi** [scout-app/scout-app#198]
Any indication when Scout will be updated to support most recent version of SASS (3.4.13 at time of writing) to support loops like @each?

**Comment by TheJaredWilcurt** [comment]
The current version of Scout is likely to be the last version that uses Adobe AIR and Java for it's run-time environments and will likely never get any more updates. There is however talks of creating a Scout 2.0 using different technology, such as [nw.js](http://nwjs.io) (formerly node-webkit).

* [A discussion on Scout App 2](https://github.com/mhs/scout-app/issues/186)

**Comment by TheJaredWilcurt** [comment]
Latest version of Scout-App supports this. Closing this issue.

* http://Scout-App.io
