### ISSUE TITLE
Can't get Scout to work

### ISSUE THREAD

**Issue by cc39** [scout-app/scout-app#199]
Hi guys,
This is going to sound silly, I know, but I just can't get Scout to work: I'm typing v. simple css into the scss page (eg body {color:red;} and I'm getting the following error message back on the Scout log:

 "This selector doesn't have any properties and will not be rendered. error boilerplate.sass (Line 1: Invalid CSS after "body ": expected selector, was "{")
identical boilerplate.css "

And "Syntax error: Invalid CSS after "body ": expected selector, was "{" " on the css page.

I've tried this in both notepad++ and Brackets with identical results.
Any help would be appreciated.

**Comment by TheJaredWilcurt** [comment]
If I had to guess, the `error boilerplate.sass` leads me to believe you're using a .sass file with the wrong syntax.

Watch this video, it should clear up a lot:

* https://www.youtube.com/watch?v=CV2fdPMdkn0

**Comment by cc39** [comment]
hi Jared* and thanks for getting back on my query - I'll have a look at the
video you attached. I finally got Scout to work by starting again -
following a different tutorial - the first one just said "download
RubyGems", the second vid also walked you through initializing and
installing the Ruby DK which seemed to make a difference - plus I think I
was using, as you say, the wrong syntax etc - also seems to help if you are
working on the same drive (C:\) as the Scout/Ruby/dk.
Anyway, off to view Sass the Easies!
thanks,
chris

**Comment by TheJaredWilcurt** [comment]
@cc39 There is a newer and even easier version of Scout-App out. Give it a try.

* http://Scout-App.io

Closing this issue.
