### ISSUE TITLE
CSS not updating - FSSM error

### ISSUE THREAD

**Issue by Cyndi206** [scout-app/scout-app#200]
The app seems to have stopped working and is posting this message: "Dear developers making use of FSSM in your projects, be taking place in the new shared guard/listen project. Please let us know if you need help transitioning! ^_^b - Travis Tilley >>> Compass is polling for changes. Press Ctrl-C to Stop."

I see this message in a few other threads, but no fix for it.

Thanks

**Comment by TheJaredWilcurt** [comment]
This video should make getting started a little easier and discusses that message you're getting. It's normal. If it isn't working, just stop and restart it. It can take a little while to get up and running, but once it is, it should detect your change and update within 2-3 seconds of saving a sass file in your input directory. If not you probably need to update Java 7 (not 8) and Air. http://youtu.be/CV2fdPMdkn0

**Comment by Nishant-Rana** [comment]
Same Here please fix this
Dear developers making use of FSSM in your projects, be taking place in the new shared guard/listen project. Please let us know if you need help transitioning! ^_^b
- Travis Tilley >>> Compass is polling for changes. Press Ctrl-C to Stop.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. Issue resolved.

* [Scout-App.io](http://Scout-App.io)
