### ISSUE TITLE
Argument Error #3214 with an updated Adobe Air

### ISSUE THREAD

**Issue by xlsmile** [scout-app/scout-app#201]
With an updated Adobe Air, the Scout started giving an ArgumentError: Error #3214 on Windows. So, nothing compiles anymore.

**Comment by stantonl33** [comment]
I'm getting the same error as well:

[error][app:/views/production.html][09:25:03]: ArgumentError: Error #3214
![adobe air error](https://cloud.githubusercontent.com/assets/2967946/7320835/6cce4612-ea64-11e4-9916-8577c467e927.jpg)

**Comment by xlsmile** [comment]
I have resolved it on Windows 8.1 by going to Java folder, locating the "process_interaction.js" file and changing the Java version to the updated one (basically updating the "jre1.8.0_25"). 

function javaDir() {
if(air.Capabilities.os.match(/Windows/)) {
path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_25\bin\java.exe");
if(!path.exists){

**Comment by stantonl33** [comment]
I have added this change as well although I have java version 8 update 45 and Windows 7 sp1 and it still throws the same error.

**Comment by blindthief10** [comment]
I have the same problem. 

When i am going to the JS file on the installScoutDir and try to edit, i just cannot save these changes and keep getting message "Save Failed, Please check if this file is opened in another program".

So Scout does not see the newest configurations and keep showing error.

What should i do?

**Comment by TypicalNoob** [comment]
can some one explain how to fix this issue, what am i supposed to do with that line of code posted above? using windows 7. my project is stalled until i can get scout back working!

**Comment by xlsmile** [comment]
To TypicalNoob.

Not sure about Win7, but on Win8 you go to your Java folder (C:\Program Files\Java) and check what version of Java Runtime you have (in my case "jre1.8.0_45").

Then locate your Scout app (C:\Program Files (x86)\Scout), and go to your "javascripts -> app" folder (C:\Program Files (x86)\Scout\javascripts\app). In this folder there should be a "process_interaction.js" file. Open it either in a code editor or a plain notepad. Then find "javaDir();" function ("function javaDir()"). In this function change the version/-s of your Java Runtime to the appropriate one (in my case it's "jre1.8.0_45"). So, your whole function should look smth like this:

 function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_45\\bin\\java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:\\Program Files (x86)\\Java\\jre1.8.0_45\\bin\\java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\Program Files\\Java\\jre1.8.0_45\\bin\\java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }


Done.

**Comment by TypicalNoob** [comment]
xlsmile, thanks for that step by step guide, it was an identical process for windows 7. 
I had the same issue as blindthief10 where it  refused to save. i fixed that problem by changing the permissions in the properties panel.

right click the filename and choose properties, open the security tab and click advanced, change permissions, then select your username, press edit and tick the Full control checkbox press apply and then you should be able to save the file.

thanks again for your quick response :)

**Comment by xlsmile** [comment]
TypicalNoob, no probs. Glad, it worked for you :o).

**Comment by vote539** [comment]
@xlsmile's solution worked for me, also on Windows 8.1.  The file I needed to edit was:

*C:\Program Files (x86)\Scout\javascripts\app\process_interaction.js*

In order to save the file I needed to open Nodepad++ in Administrator mode.

**Comment by scotia4444** [comment]
xsmile's tip worked for me too.

**Comment by artifishall** [comment]
I had trouble with this too, so I dug around in window to figure out where it links to Java. Here is a more permanent fix.

if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:\\ProgramData\\Oracle\\Java\\javapath\\java.exe");
        }

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
