### ISSUE TITLE
Color Syntax on the console

### ISSUE THREAD

**Issue by fjacot** [scout-app/scout-app#202]
Hi,

I wanted to know how to configure the solor syntax for the Console. Because now, the background is black, but all the text is white, event if there's an error.
On the Scout website, there is color syntax.

I'm working on Windows 7

Thanks

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. There are many preset themes to choose from, or you can create your own by making your own CSS stylesheet and placing it in the `scout-files\_themes` directory of the app.

* [Scout-App.io](http://Scout-App.io)
