### ISSUE TITLE
How to use scout on localhost or live server?

### ISSUE THREAD

**Issue by rob7harris** [scout-app/scout-app#205]
Hi, im just starting out with scout/sass and am currently compiling my css on my desktop, but in terms of the stylesheet directories, what path would it need to be for input folder if my structure is localhost/dropbox/bootstrap/css/sass - when I try using this I get the following error 
"You must compile individual stylesheets from the project directory."

thanks

**Comment by mejiaj** [comment]
You should run scout locally and then update the CSS on your server. That way if you mess something up locally your production site should still be OK.

**Comment by TheJaredWilcurt** [comment]
Been a year with no response. Issue presumed resolved. Closing.

Worth noting, the latest version of Scout-App should guess your input/output folders automatically. As long as they are named something sensible like `sass` and `css`.

* [Scout-App.io](http://Scout-App.io)
