### ISSUE TITLE
Scout 0.7.1 throws error on valid @each code (OSX 10.10.3)

### ISSUE THREAD

**Issue by adrianbw** [scout-app/scout-app#207]
It seems that Scout fails to parse correctly formatted @each formulas. For example, this code from the sass reference (http://sass-lang.com/documentation/file.SASS_REFERENCE.html):

```
@each $animal, $color, $cursor in (puma, black, default),
                                  (sea-slug, blue, pointer),
                                  (egret, white, move) {
  .#{$animal}-icon {
    background-image: url('/images/#{$animal}.png');
    border: 2px solid $color;
    cursor: $cursor;
  }
}
```

Yields this error message:

error base.scss (Line 3 of _palette.scss: Invalid CSS after "@each $animal": expected "in", was ", $color, $curs...")

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
