### ISSUE TITLE
All my ruby compass shows as ok but Scout says its installation wizard needs, see below

### ISSUE THREAD

**Issue by brianran** [scout-app/scout-app#208]
I check that all programms show installed ok, but scout will not work as it keeps asking for a 40 character alphanumeric key displayed on the account page. Can,t discover what and where to find
It says enter the key from where???

**Comment by TheJaredWilcurt** [comment]
This issue is not relevant to the latest version of Scout-App.

Closing this ticket. Download the latest version at [Scout-App.io](http://Scout-App.io).
