### ISSUE TITLE
i can't work with scout how can i fix this message

### ISSUE THREAD

**Issue by ahmed3eraqi** [scout-app/scout-app#209]
![image](https://cloud.githubusercontent.com/assets/9159804/8273739/30e6a470-187a-11e5-83ac-c1f4101a307b.png)

**Comment by TheJaredWilcurt** [comment]
What OS are you on?

If it's Windows, try running this to update Scout's dependencies:

* http://ninite.com/air-java7

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Java.

* [Scout-App 2](http://Scout-App.io) (2016)
