### ISSUE TITLE
Double dash won't compile

### ISSUE THREAD

**Issue by beshur** [scout-app/scout-app#210]
Hi.

I use sort of BEM-method, and I need classes of `.b_logo--big` format. But double dash seems not to be supported by the current version of Scout (0.7.1). Is it correct?

`Invalid CSS after "	&-": expected number or function, was "-header {"`

Code
```
.b_logo {
	&--header {
		
	}
}
```
This type of extending parent class was introduced in around SaSS v.3.3.

**Comment by TheJaredWilcurt** [comment]
Unfortunately, the current version of Scout is from 2012 and thus uses an older version of Sass. There is a new planned version in the works that will be easier to maintain and use a newer version of Sass. For now you can look for a Scout alternative or make do without the double-dash. Sorry for the bad news.

**Comment by beshur** [comment]
Ok. Do you need help with that new version? But I can't do anything but javascript.

**Comment by TheJaredWilcurt** [comment]
@beshur If you would like to contribute to Scout-App 2:

* https://github.com/scout-app/scout-app/blob/master/documentation/contributing.md

* * *
Issue resolved. Closing this ticket.

* [Scout-App.io](http://Scout-App.io)
