### ISSUE TITLE
Message: No Java runtime present, requesting install.

### ISSUE THREAD

**Issue by PowerStudio** [scout-app/scout-app#212]
I installed the latest Java Runtime and I still get the message "No Java runtime present, requesting install."... I'm using OSX 10.10.4

Help please!

**Comment by TheJaredWilcurt** [comment]
**Duplicate issue:**

* https://github.com/mhs/scout-app/issues/190

**Comment by Jojokats** [comment]
I have the same problem

**Comment by caspergrl** [comment]
Same here...

**Comment by juliancoates** [comment]
Me too.

**Comment by TheJaredWilcurt** [comment]
@PowerStudio @Jojokats @caspergrl @juliancoates 

Try out the new Scout-App 2 Beta

* https://github.com/TheJaredWilcurt/scout-app/releases

**Comment by juliancoates** [comment]
got it working, downloading the jdk fixed it.

**Comment by elkbrsathuji** [comment]
installing jdk fixed the problem (with a price of 500MB)

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Java.

* [Scout-App 2](http://Scout-App.io) (2016)
