### ISSUE TITLE
Error 3214

### ISSUE THREAD

**Issue by Nifty62** [scout-app/scout-app#213]
I have been using Scout for a while and it's invaluable to me.

I recently formatted my computer and now when I try to hit the "play" button on a project it gives me a 3214 error.

I do indeed have Java installed and up to date. Also, it is in the correct location as far as I know.

C:\Program Files (x86)\Java\jre1.8.0_60

I'd appreciate any help that can be offered. I'm a web designer and this is really a bad thing to be going on atm.

**Comment by Nifty62** [comment]
Oh, and I already tried the edit of the process_interaction file. My current function looks like this:

function javaDir() {
if(air.Capabilities.os.match(/Windows/)) {
path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_45\bin\java.exe");
if(!path.exists){
path = air.File.applicationDirectory.resolvePath("C:\Program Files (x86)\Java\jre1.8.0_45\bin\java.exe");
if(!path.exists){
path = air.File.applicationDirectory.resolvePath("C:\Program Files\Java\jre1.8.0_45\bin\java.exe");
}
}
return path;
} else {
return air.File.applicationDirectory.resolvePath("/usr/bin/java");
}
}

**Comment by gmt-it** [comment]
You should use slash ( / ) instead of backslash. Works without Problems on WIN 10.

<pre>
function javaDir() {
    if(air.Capabilities.os.match(/Windows/)) {
      path = air.File.applicationDirectory.resolvePath("C:/Program Files/Java/jre7/bin/java.exe");
      if(!path.exists){
        path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre7/bin/java.exe");
        if(!path.exists){
          path = air.File.applicationDirectory.resolvePath("C:/Program Files (x86)/Java/jre1.8.0_60/bin/java.exe");
        }
      }
      return path;
    } else {
      return air.File.applicationDirectory.resolvePath("/usr/bin/java");
    }
  }
</pre>

**Comment by Nifty62** [comment]
You are my hero!

I'm back on track! Thanks man!

**Comment by gmt-it** [comment]
You are wellcome! ;-)

**Comment by TheJaredWilcurt** [comment]
Duplicate issue: https://github.com/mhs/scout-app/issues/187

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 does not rely on Java.

* [Scout-App 2](http://Scout-App.io) (2016)
