### ISSUE TITLE
Can't save without restarting project 

### ISSUE THREAD

**Issue by FranckSCTV** [scout-app/scout-app#214]
Hi,

I've been using Scout during a couple of years already, but recently,  I got the following issue :
When I save the SCSS file, I get an error message saying "Error saving file : .....".
Thus, the SCSS file can't be saved and the CSS file can't be updated.

But, if I stop and restart the project listener (by clicking twice on the "start/stop" icon next to the project name), then I can save again but only once or twice before the error message comes again.

I work on the following system : 
Windows 7 (x86)
jre1.8.0_51
I edit the SCSS files on PSPAD

I've tried the following : 
Start Scout as an Admin
Uninstall/Reinstall Scout
... but nothing seems to solve the issue.

Any idea what it could be?
 
Thanks!

**Comment by TheJaredWilcurt** [comment]
So if you have an project set up like this:

    project/
     └ sass/
        ├ _header.sass
        ├ _footer.sass
        └ style.scss

The first 2 files have an underscore, meaning scout ignores them and doesn't produce a .css file with a matching name in the output folder. The 3rd file presumably imports those other two files in. That file is currently being accessed by Scout/Adobe Air, thus, via a limitation in Windows, it can't be altered by other processes as it is in use. So basically, if you intend on editing files while Scout is running, make sure they have an underscore at the beginning. If you need to edit a file that doesn't have an underscore, then unfortunately, you'll need to stop Scout. This is a limitation of the OS and the runtime environment used to communicate with the OS.

The new version of Scout is being designed now and won't be using Air/Java anymore so potentially this won't be a problem in the future. Thanks for using Scout, hope that explains what's going on.

If your having problems saving files that begin with an underscore I could give more advice on steps to try to remedy the issue, though I've not experienced it and would just be describing the things I'd try first.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App 2](http://Scout-App.io) (2016)
