### ISSUE TITLE
Scout error existing Zen install

### ISSUE THREAD

**Issue by PivotJason** [scout-app/scout-app#215]
When I make a change to my scss, Scout throws this error:
>>> Change detected at 18:11:16 to: styles.scss
error styles.scss (Line 36 of _variables.scss: Invalid CSS after " 'chrome'": expected ")", was ": null,")
identical styles.css

If I remove the above code from _variables.scss, it throws another error further down in the same file. Some Googling shows it might be a Java version issue, but I can't seem to tell if that is true OR downgrade, on Mac Yosemite...

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 does not rely on Java.

* [Scout-App 2](http://Scout-App.io) (2016)
