### ISSUE TITLE
Scout stops compiling after one run after Air update

### ISSUE THREAD

**Issue by macbetty** [scout-app/scout-app#216]
I used Scout successfully for almost a year before this started happening.  After I updated Adobe Air, it only compiles my sass files if I stop it and start it again, if it doesn't stop on its own.  

![scout](https://cloud.githubusercontent.com/assets/9685081/9665397/09bfc324-523e-11e5-99a8-f4f27e322a30.JPG)

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App 2](http://Scout-App.io) (2016)
