### ISSUE TITLE
Scout App Argument Error - Error 3214 

### ISSUE THREAD

**Issue by nXception** [scout-app/scout-app#218]
I know it has something to do with scout not being able to locate Java. I went into C:\Program Files(x86)\Scout\javascripts\app\process_interaction and I'm trying to edit it to go to the right folder, but I'm unable to edit process_interaction. It won't let me save any changes I make to it. I turned off scout, and made sure it wasn't running in the background. Is there any other way to fix error 3214?

**Comment by gmt-it** [comment]
Hello,

you have to have admin rights to save the file. Copy the file to Desktop, edit it and copy it back to the folder. Or start your Editor with admin rights.

**Comment by f1ss1on** [comment]
Please check my latest proposed commit for proper code edit

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App 2](http://Scout-App.io) (2016)
