### ISSUE TITLE
Scout stops running | org.jruby.Main.main (Main.java:128)

### ISSUE THREAD

**Issue by Jeroendeb33r** [scout-app/scout-app#219]
I installed Scout and it was running perfect at the beginning. Since yesterday when I start my project, it runs for a few seconds, than it stops. 

-I have java 7 and 8 installed.
-run ruby 2.2.3p173
*** LOCAL GEMS ***
bigdecimal (1.2.6)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
sass (3.4.19)
test-unit (3.0.8)

This is the log in Scout:
![scoutlog](https://cloud.githubusercontent.com/assets/15195661/10578394/32831196-7672-11e5-999f-01a62cf1d4f0.PNG)
Sorry, do not have permission to upload a log in a text file.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App 2](http://Scout-App.io) (2016)
