### ISSUE TITLE
Inconsistent/Erroneous rgba() opacity-decimal parsing

### ISSUE THREAD

**Issue by isNaN** [scout-app/scout-app#22]
An opacity value like this: rgba( 0, 0, 0, 0.66 ) is often returned as rgba( 0, 0, 0, 0 ). This behavior is very inconsistent. 

Usually the "last saved file" in a project parses correctly, but having 8-9 imports with ~350 lines of SCSS in each, at least one of those files always fail.

**Comment by nakrill** [comment]
//* scss-compile-options: --precision 8

**Comment by marcofugaro** [comment]
I've come across the same issue recently, here's how to reproduce it:

Compile box-shadow: 0 0 10px rgba(0, 0, 0, 0.1) the first time and it works normally, then change any other thing in the scss file or any other partial file and compile, it now compiles to box-shadow: 0 0 10px rgba(0, 0, 0, 0)

System: Windows 7 64bit
Version: 0.7.1

**Comment by gheiler** [comment]
@mgrodzicki workaround works great, thanks!

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing ticket. Download latest version of Scout-App. If problem still exists, create a new issue.

* [Scout-App 2](http://scout-app.io) (2016)
