### ISSUE TITLE
Variable list throws syntax error

### ISSUE THREAD

**Issue by skids89** [scout-app/scout-app#222]
I am using 0.7.1 on OSX10.10.5.
$breakpoints: (
  'phone': 320px,
  'tablet': 768px,
  'desktop': 1024px
) !default;

throws the following error.
"Syntax error: Invalid CSS after \" 'phone'\": expected selector or at-rule, was \": 320px,\"\A on line 35 of /Users/nate/Documents/SproutAg/YieldConf16site/Sass/_responsive.scss\A from line 3 of /Users/nate/Documents/SproutAg/YieldConf16site/Sass/style.scss"

I cant seem to use the variable list for my media queries. I cant figure out the syntax change needed, and I pulled this from css tricks and it works good for them. Though clearly they aren't using an app to compile css.

**Comment by skids89** [comment]
Is this due to the fact that scout has not been updated since 2012?

**Comment by TheJaredWilcurt** [comment]
Closing this ticket.

* [Scout-App 2](http://Scout-App.io) (2016)

If the problem exists in the latest version of Scout-App, create a new issue.
