### ISSUE TITLE
Can Scout use @extend to include Bootstrap elements

### ISSUE THREAD

**Issue by wdavid62** [scout-app/scout-app#225]
I've seen some examples of folks doing things like @extend .btn in Sass.
This doesn't seem to work in Scout. 
Can this be done?

**Comment by TheJaredWilcurt** [comment]
Scout is using the 2012 version of Sass. It can do anything that version can.

**Comment by TheJaredWilcurt** [comment]
You can try this with [Scout-App 2](http://Scout-App.io) (2016 version).

Closing this ticket. Feel free to open a new one if the issue is present in the new version of Scout.
