### ISSUE TITLE
Log text size 

### ISSUE THREAD

**Issue by rachelreveley** [scout-app/scout-app#226]
Running in Windows 10, the text is really tiny. I have increased the default Windows font scaling but this has had no effect on Scout. I have to squint to read the output.

**Comment by TheJaredWilcurt** [comment]
@rachelreveley can you try out Scout-App 2.0.2 and let me know if the issue still occurs.

* [Scout-App 2](http://Scout-App.io) (2016)

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. If the problem still exists in the latest version of Scout-App, create a new issue.

* [Scout-App.io](http://Scout-App.io)
