### ISSUE TITLE
Installer for windows not working

### ISSUE THREAD

**Issue by bhushan2** [scout-app/scout-app#228]
I tried to download installer for windows http://mhs.github.io/scout-app/
Set up is giving error

**Comment by micalm** [comment]
Also encountering this error, something along the lines of "The installer is broken, obtain a new one".
Using Windows 10 x64, installers md5 is 885dd6786fb6ef60052d48e247a3f800.

**Comment by Slemirs** [comment]
I have same problem. Broken installer

**Comment by gpache13** [comment]
I also get an error in the installer

**Comment by TheJaredWilcurt** [comment]
Confirmed that downloading the `.exe` on Win 7 64 displays the same error message.

![air-error](https://cloud.githubusercontent.com/assets/4629794/13471368/476e9b0e-e07e-11e5-9035-40ee6a2fbaa5.png)

But I also have a backed up copy of Scout on an external HDD that I've used to install it on many machines. This is a known-good/working copy, but running it displays the same error. Meaning nothing changed int he package.

So something either changed in Adobe Air, or in a Windows Update.

**Comment by TheJaredWilcurt** [comment]
I uninstalled Air 20 (which was installed this month), and tried 19 then 14 (RTE not SDK). Neither worked. Same error. This may be Windows Update related? Though I didn't restart between installs or clean out my registry or temp or anything. So something that 20 installed might still be lingering and causing trouble. With that said, my installed version of Scout still runs with any of Air versions.

Also tried running the Scout installer in different compatibility modes and as an admin. Nothing worked.

**Comment by TheJaredWilcurt** [comment]
@bhushan2 @micalm @Slemirs @gpache13 

I need my installed copy of Scout to work, so I can't test this, but one of you could try:

1. Install 7-Zip
2. Download Scout installer
3. Right-click Scout Installer (.exe) > 7-Zip > Extract to "folder with same name"
4. Open that folder and try to install using `Install Scout.exe` or `setup.exe` or `Scout.exe`

See if one of those works.

**Comment by larpabellanosa** [comment]
@TheJaredWilcurt  I followed your instruction and when I run the Install Scout.exe it  shows the same error but when I extracted the Scout Installer.exe it creates a folder of Scout with Scout.exe or the scout application itself. Did the installer install itself when I extracted the Scout installer?

**Comment by bhushan2** [comment]
Followed your instruction. Its showing same error.

**Comment by soumyahooli** [comment]
even I followed the steps. I got the same error again

**Comment by darkdim** [comment]
Same error(
Subscribe

**Comment by andreydos** [comment]
+1 error

**Comment by TheJaredWilcurt** [comment]
@darkdim @andreydos @bhushan2 @micalm @Slemirs @gpache13 @larpabellanosa 

According to issue https://github.com/mhs/scout-app/issues/227 @soumyahooli was able to get it to work by doing the following:

1. Download [Scout App](https://github.com/downloads/mhs/scout-app/ScoutAppInstaller-0.7.1.exe)
2. Download [7-Zip](http://7-zip.org) and install it
3. Right-click `ScoutAppInstaller-0.7.1.exe` > 7-Zip > Extract to "`ScoutAppInstaller-0.7.1`"
4. Run `Scout\setup.msi`

If you are JS or Node developer and want to help out on the next version of Scout so others don't have to do this, go here:

* [Chatroom](https://gitter.im/TheJaredWilcurt/scout-app)
* [Repo](https://github.com/TheJaredWilcurt/scout-app)

**Comment by lamarti** [comment]
Having a problem:  I tryed 
Download Scout App
Download 7-Zip and install it
Right-click ScoutAppInstaller-0.7.1.exe > 7-Zip > Extract to "ScoutAppInstaller-0.7.1"
Run Scout\setup.msi
Seems many have this same problem. But still getting the same error measage. Is there a real fix for this.Or a better product?
 Seems many have this same problem.

**Comment by lokeshMobikwik** [comment]
I was facing the same problem and nothing comes up after googling alot.
Then Finally i ended up with a solution that
I have another computer where scout was previously installed. in "C:\Program Files (x86)\Scout"
Step1: I copied complete "scout" folder from that computer
Step2: And paste to same directory structure into my new system
Step3: Lastly i run the "scout.exe" . 
And everything works fine

**Comment by lokeshchadha** [comment]
I was facing the same problem and nothing comes up after googling alot.
Then Finally i ended up with a solution that
I have another computer where scout was previously installed. in "C:\Program Files (x86)\Scout"
Step1: I copied complete "scout" folder from that computer
Step2: And paste to same directory structure into my new system
Step3: Lastly i run the "scout.exe" . 
And everything works fine

**Comment by TheJaredWilcurt** [comment]
I am not spending any time fixing Scout 0.7.1. I am however working on Scout 2.0.0.

* #186 

Some solutions have been posted here and you can try them, or if you are familiar with Node based front-end development you can try out the new version while it's being made. It is semi-functional.

**Comment by TheJaredWilcurt** [comment]
@lokeshchadha @lamarti @andreydos @darkdim @soumyahooli @bhushan2 @gpache13 @Slemirs @micalm 

# **I fixed Scout 0.7.1 for Windows.**

Download and follow the instructions included.

* **[Scout-App 0.7.1 for Windows Re-Release](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10)**

**Comment by kevan-gg** [comment]
Solution for me was similar to what lamarti wrote. I just renamed the downloaded exe to zip, and then extracted the contents to a folder, then ran the setup.msi. Worked.

@lamarti wrote: 

> Download Scout App
Download 7-Zip and install it
Right-click ScoutAppInstaller-0.7.1.exe > 7-Zip > Extract to "ScoutAppInstaller-0.7.1"
Run Scout\setup.msi

**Comment by NilSagor** [comment]
I got same issue . It says error 
![scount](https://cloud.githubusercontent.com/assets/13550699/14037795/2bbdde6e-f272-11e5-8b89-92f25dc54052.jpg)

**Comment by kevan-gg** [comment]
Apologies, but this was a deal breaker for me and a real hassle. The idea is very good but if I can't get it to work then I have look elsewhere. I'm now running commando (command line) with sass and it's not that bad so far.

**Comment by TheJaredWilcurt** [comment]
@kevan-gg 

There is a temporary fix posted above your last post.

* [#228 (Comment) - I fixed Scout 0.7.1 for Windows.](https://github.com/mhs/scout-app/issues/228#issuecomment-195599737)

No more effort beyond that re-release will be spent on 0.7.1 by me, or my team, as we are focusing on releasing Scout-App 2 within the next month. There are currently only 4 items left on the to-do list before we are ready for beta-testing. 

* * *

# Sign up for Scout 2 Beta Testing

* [Beta Tester Sign up](https://github.com/mhs/scout-app/issues/230) - (GitHub Issue #230)

![Arrow](http://i.imgur.com/N8hJBrO.jpg)

* * *

**Comment by wichaksono** [comment]
I use 
1. Download and Install 7zip x64  (i use windows 7 ultimate x64)
2. Download "ScoutAppInstaller-0.7.1.exe" Right Click 7Zip > Extract To "ScoutAppInstaller-0.7.1\"
3. just Copy folder "Scout" to C:\Program Files or C:\Program Files (x86) if using windows 64 bit
4. Double Click "Scout.exe"

**Comment by Jellygnite** [comment]
This worked for me:
1. Download Scout App
2. Download 7-Zip and install it
3. Right-click ScoutAppInstaller-0.7.1.exe > 7-Zip > Extract to "ScoutAppInstaller-0.7.1"
4. Open a command window and enter the following remembering to replace PATH_TO_SCOUT with the actual folder you extracted the files to.

`msiexec /i "PATH_TO_SCOUT\setup.msi" TARGETDIR="C:\Program Files\Scout" /qb`

I found if you didn't enter a TARGETDIR it just installed to the root C:/ drive.

**Comment by TheJaredWilcurt** [comment]
@Jellygnite Great find. I updated the re-release to include those instructions.

**Comment by mohit7189** [comment]
Installing adobe air and extracting the installation package by 7zip and then installing the application worked for me

**Comment by Shiponkormoker** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/16864443/16302057/ce07ba52-396a-11e6-8da6-97a0f73342e8.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/16864443/16302066/de70b132-396a-11e6-8e06-39fe219eb812.png)

**Comment by TheJaredWilcurt** [comment]
# BEFORE POSTING READ THIS

1. If you want to use the 2012 version, [Try the Re-Release](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10)
2. If you want to use the 2016 version, [Try the Beta Release](https://github.com/TheJaredWilcurt/scout-app/releases)

**Comment by ActiveRecord** [comment]
Get The latest version "Scout-App 2". Available in all OS including Windows 10

http://scout-app.io/

![scout-app - sass without hassle](https://cloud.githubusercontent.com/assets/5427346/17353964/22c4619e-593c-11e6-9459-3143d2b08432.jpg)
![scout-app - sass without hassle 1](https://cloud.githubusercontent.com/assets/5427346/17353965/22c4c85a-593c-11e6-9e84-d2c21c547e8d.jpg)

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
