### ISSUE TITLE
Nothing to compile. If you're trying to start a new project, you have left off the directory argument

### ISSUE THREAD

**Issue by nickkessler** [scout-app/scout-app#231]
Scout is giving me this error after I try to compile:
"Nothing to compile. If you're trying to start a new project, you have left off the directory argument."

I have a index.html with this inside 

`<!DOCTYPE html>`
`<html>`
	`head>`
		`<title>My Sass Project</title>`
		`<link rel="stylesheet" href="css/main.css">`
	`</head>`
	`<body>`
	
	`</body>`
`</html>`

a "sccs" folder with a "main.scss "file
the "index.html" file is inside a folder along with my "css" "img" "scss" and "js" folder

I've set the scout input folder to sccs
Output to css
javascript to js
images to img

I've tried both:
href="scss/main.scss"
href="scss/main.css"
href="css/main.scss"
href="css/main.css"

and I still get the same error

**Comment by TheJaredWilcurt** [comment]
Try following this video to see if it helps you:

* https://www.youtube.com/watch?v=CV2fdPMdkn0&t=1m19s

If it does, let me know where you got stuck, I'm working on the next version of scout and would like to know how to make it better/easier.

**Comment by TheJaredWilcurt** [comment]
Issue presumed resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
