### ISSUE TITLE
Undefined-mixin 'animation' in Scout-app but works from console

### ISSUE THREAD

**Issue by matpulis** [scout-app/scout-app#232]
Hi guys, I have a weird problem. If I cd into the directory and execute compass watch from the terminal the scss compiles successfully, but when I try to run scout on the same directory an error is thrown where it can't find certain compass mixins like animation. I do have the include "compass/css3" in the begining of my file. Any ideas please ? I am running Mac OSX Yosemite

**Comment by TheJaredWilcurt** [comment]
Scout 0.7.1 was created in 2012 and has not been updated since. So if you are referencing anything newer than that, it won't work.

Scout-App 2 is in the works and should be released for beta testing soon.

You can sign up here: 

https://github.com/mhs/scout-app/issues/230

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
