### ISSUE TITLE
Installing windows error

### ISSUE THREAD

**Issue by Tanisha0494** [scout-app/scout-app#233]
When I try to run to set up I get an error that there's something wrong with the file or it is damaged.

**Comment by TheJaredWilcurt** [comment]
Scout-App 0.7.1 has issues install on Windows. You can either use this re-release of it and follow the instructions to use it, or try the new Scout-App 2 which is in Beta:

* [Scout-App 0.7.1 Re-release](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10)
* [Scout-App 2.0.0 Beta](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v2.0.0-beta1)

Be sure to mark this ticket as closed.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
