### ISSUE TITLE
Since the last update, Scout stops, after a while running, checking for changes to compile.

### ISSUE THREAD

**Issue by DerExilant** [scout-app/scout-app#234]
I think the headline says everything.
Since the last AIR Update Scout shows some annoying behaviour. Working fine for a undetermined time and suddently scout stops checking for changes and nothing I do will make Scout start checking for changes again.. only a restart works.

**Comment by TheJaredWilcurt** [comment]
You can try out the Scout-App 2 Beta.

* https://github.com/TheJaredWilcurt/scout-app/releases

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
