### ISSUE TITLE
Installer crashes

### ISSUE THREAD

**Issue by roberthoog** [scout-app/scout-app#236]
I'm running Windows 10 and when clicking the the installer nothing seems to happen. But after several minutes or so I get this screen saying the installation could not continue since the installation file is damaged. 

I have tried downloading it again twice but no results.

**Comment by TheJaredWilcurt** [comment]
This is a known issue. If you want to use the 2012 version (0.7.1) there is a re-release for it that works. Or you can use the soon-to-be released Scout-App 2.

* [Scout-App 0.7.1 (2012)](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10)
* [Scout-App 2.0.2 Beta (2016)](https://github.com/TheJaredWilcurt/scout-app/releases)

Please close this issue if one of those downloads works for you.

**Comment by roberthoog** [comment]
*Thank you*, I will try this instead.

**Comment by TheJaredWilcurt** [comment]
Issue presumed resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
