### ISSUE TITLE
Unable to install Scout (Current Version) in my system

### ISSUE THREAD

**Issue by lokicl** [scout-app/scout-app#237]
Adobe Air as prequisite is installed

**Comment by TheJaredWilcurt** [comment]
This is a known issue for the 2012 version of Scout-App. You can download the re-release of it or the latest 2016 version (currently in beta, soon to be released).

Both are here:

* http://github.com/TheJaredWilcurt/scout-app/releases

If that works, you can close this issue.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
