### ISSUE TITLE
Compile children's folders

### ISSUE THREAD

**Issue by noemaug** [scout-app/scout-app#241]
Isn't it possible to compile children's folders on Scout-App 2 Beta 2 ?

Input Folder: /project/themes/theme-name/sass
and I have 3 others folders in /sass with many files.scss 

Thanks

**Comment by Maikkiczk** [comment]
I really wait an answer to this post too :)

**Comment by TheJaredWilcurt** [comment]
Recursive folder checking wasn't part of the beta, working on it now.

**Comment by TheJaredWilcurt** [comment]
@noemaug @Maikkiczk 

This feature has been implemented in the latest Scout-App-2-Dev branch. I will likely not be doing a new release of the final version until [the website](http://TheJaredWilcurt.github.io/scout-app) that is in development is complete.

If you are familiar with Node and would like to use the latest version, you can run these commands:

```shell
git clone https://github.com/TheJaredWilcurt/scout-app.git
git checkout Scout-App-2-Dev
git pull origin Scout-App-2-Dev
npm install
npm start
```

This ticket can be closed now.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
