### ISSUE TITLE
Scout Compiler Slow over VPN

### ISSUE THREAD

**Issue by WaxMikhail** [scout-app/scout-app#244]
Howdy folks,

I work from home connecting to our work server over VPN. All our SCSS files are there and I have projects for each of them. When my laptop is in the studio and I'm connected to the server just over WiFi, compiling from changes is almost instantaneous. Currently connected via VPN, changes take **30 to 40 seconds** to be compiled (for me to get the 'overwrite' message).

Any suggestions for how to speed up my compiling over VPN?

**Comment by TheJaredWilcurt** [comment]
@WaxMikhail 

Which version are you using? 

* [2012](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10) (0.7.1)
* [2016](https://TheJaredWilcurt.github.io/scout-app) (2.0.1-Beta)

If it's the 2012 version, try the 2016 beta.

**Comment by WaxMikhail** [comment]
I am on 0.7.1, I will give the beta a shot!

**Comment by TheJaredWilcurt** [comment]
Issue presumed resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
