### ISSUE TITLE
Problem in UI (FTUX)

### ISSUE THREAD

**Issue by madvik** [scout-app/scout-app#246]
OS: WIndows 8.1
Version: utilise node-sass (Node-Sass v3.8.0 / LibSass v3.3.3) et chokidar v1.6.0.
Information from Dev Tools: 
When I select a folder of a project :
![scout-1](https://cloud.githubusercontent.com/assets/3822529/17131962/f538130a-531f-11e6-9fdb-fd6efb9c90a8.GIF)

**Comment by TheJaredWilcurt** [comment]
Are you on the latest 2.0.2 or an earlier beta?

Can you give me steps to reproduce this. I've tried but am unable.

![screenshot](https://cloud.githubusercontent.com/assets/4629794/17159072/8928a5b4-5368-11e6-9225-1c9bac7a57b0.png)

If you are on an earlier version, download the latest from here:

* http://scout-app.io

**Comment by TheJaredWilcurt** [comment]
@madvik 

There is a new release of Scout-App available for download. I've never been able to reproduce this bug so I'm closing this issue until someone else posts a similar bug or until instructions on how to reproduce it are posted.

* [Scout-App.io](http://scout-app.io)
* [Release Notes](https://github.com/scout-app/scout-app/releases)

**Comment by madvik** [comment]
Sorry, I have not re-use your app.
I test an other day ;-)
Thanks
