### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yuvak1986** [scout-app/scout-app#247]
When i trying to install scout app then its saying - >
The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author.

what can i do now ?

**Comment by echymas** [comment]
Having the same issue here. Please advise.

**Comment by yuvak1986** [comment]
download this latest version, I am working on it.

http://scout-app.io/

**Comment by TheJaredWilcurt** [comment]
You can download **Scout-App 2 (2016)** from:

* http://Scout-App.io

or you can download the **Scout-App 0.7.1 (2012)** re-release for Windows which fixes the install bug, here:

* https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10

**Comment by apolloinfinity** [comment]
![screenshot 2016-08-17 17 18 14](https://cloud.githubusercontent.com/assets/9621870/17757953/2005c744-64a0-11e6-9f92-d7fc4c9a967b.png)


Similiar error to everyone else.

**Comment by TheJaredWilcurt** [comment]
@apolloinfinity 

We are in a [transition](https://github.com/mhs/scout-app/issues/186#issuecomment-240531061) between 0.7.1 and 2.0.2. The state of the 2012 site will be improved shortly. In the mean time:

* [Download 2016 Scout-App](http://scout-app.io)
* [Download 2012 Scout-App](https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10) (re-release for Windows)

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
