### ISSUE TITLE
as of 8/08/2016 Scout cannot install on my machine tells me the installation file is damaged

### ISSUE THREAD

**Issue by peter284** [scout-app/scout-app#248]

**Comment by TheJaredWilcurt** [comment]
https://github.com/mhs/scout-app/issues/247#issuecomment-237836615

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
