### ISSUE TITLE
Error when running Scout App

### ISSUE THREAD

**Issue by Wordius** [scout-app/scout-app#25]
I've set up input and output folders. I moved my style.css file to the input folder and renamed it style.scss. When I run the compiler I get the following message and no output:

TypeError on line 3414 of org/jruby/RubyString.java: no implicit conversion from nil to integer
Run with --trace to see the full backtrace

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this issue. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
