### ISSUE TITLE
Installer file damaged

### ISSUE THREAD

**Issue by drnanjo** [scout-app/scout-app#250]
I am also having this issue with the Windows download (on 8/11).

**Comment by jimmygyeltshen** [comment]
file that I download is damaged.I could not install it.Will any one help me

**Comment by TheJaredWilcurt** [comment]
@drnanjo  @jimmygyeltshen 

The 2012 version of Scout-App (v0.7.1) has been re-released here:

* https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10

Or you can use the 2016 version of Scout-App (v2.0.2) here:

* http://Scout-App.io

* * *

Please close this ticket if one of those works for you.

**Comment by kunleAdeyinka** [comment]
Hi I am also having issues with the Windows download (on 8/12). I also tried the Scout-App.io and that didn't work was as well

**Comment by jimmygyeltshen** [comment]
The 2012 version of Scout-App (v0.7.1) has been re-released here:

https://github.com/TheJaredWilcurt/scout-app/releases/tag/v0.7.1_2016-03-10
Or you can use the 2016 version of Scout-App (v2.0.2) here:

http://Scout-App.io

**Comment by TheJaredWilcurt** [comment]
@kunleAdeyinka 

What issues did you have with Scout-App.io or Scout-App 2.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket.

* [Scout-App Classic](http://Scout-App.io/classic) (2012)
* [Scout-App 2](http://Scout-App.io) (2016)
