### ISSUE TITLE
Compiler generates unexpected CSS by duplicating selector in .not()

### ISSUE THREAD

**Issue by geoidesic** [scout-app/scout-app#254]
v2.0.2
=====
This SCSS:
```
.tooltip, .question-brown {
    &:not(.cog):after {
        font-family: arial;
    }
}
```
Compiles to:
```
.tooltip:not(.cog, .cog):after, .question-brown:not(.cog, .cog):after {
  font-family: arial;
}
```
Note the duplicated selector `(.cog, .cog)` which is unexpected.
It's expected to compile to:
```
.tooltip:not(.cog):after, .question-brown:not(.cog):after {
  font-family: arial;
}
```

**Comment by TheJaredWilcurt** [comment]
That is super weird. I'm looking into it.

**Comment by TheJaredWilcurt** [comment]
Turns out it was a bug in the LibSass Node Bindings. I've updated the master branch to have the latest bindings. Issue resolved.

Closing this issue. I'll notify you when the next Scout-App version with this fix is released.

**Comment by TheJaredWilcurt** [comment]
@geoidesic 

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
* [Release Notes](https://github.com/scout-app/scout-app/releases)
