### ISSUE TITLE
Translated Scout-App to Danish

### ISSUE THREAD

**Issue by phpgeek** [scout-app/scout-app#255]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
> Katten skriger 'NEEEJ!'

Thanks so much for the Danish translation. There are 4 translation keys I wanted to verify with you `Status`, `Output style`, `Nested`, `Expanded`. From what I can tell, there are no native Danish words for these. Is it okay to use the English versions, or should they be modified to convey the same meaning using a native word?

Is there a culturally relevant image you'd like used for Danish in the preferences. A reference that people from Denmark would get.

We used SATW for Dutch. If you can't think of anything we can do the same thing for [Denmark](http://satwcomic.com/the-world/denmark).

So far we've been adding some text with a reference to Sass somewhere in it. For example, the following says "Do you think my Sass file is too large? ...that is literally a whale"

![](https://github.com/scout-app/scout-app/raw/master/scout-files/cultures/nl.jpg)

or this, Hank Hill's catch phrase is "I Sell Propane and Propane Accessories"

![](https://github.com/scout-app/scout-app/raw/master/scout-files/cultures/en.jpg)

**Comment by TheJaredWilcurt** [comment]
If I don't get a response by the time I'm ready to release the next version, I'll proceed to pick an image and add some text as best I can to make sure this language makes it into the next version.

**Comment by phpgeek** [comment]
Ah sorry - totally got out of my head because of a lot of deadlines :) 

 Output style i just renamed to "Output stil". Actually you are can use "uddata" instead of output - but really would found it crazy if anyone did.

Expanded and Nested are translatable too... but the danish words really is not used as a term when developers/frontenders etc. are talking about it... still think it best to leave it in english.

"Status" is a danish word :)  

I think Hank Hill will be the best choice for the danes :)

**Comment by TheJaredWilcurt** [comment]
But we're already using Hank Hill for America. Is there any famous TV, Movie, Musicians or something that Danes would recognize?

* USA - King of the Hill - Hank Hill in front of an American flag
* Russia - Vinni Puhk - Famous Russian kids cartoon based on Winnie the Pooh
* France - Daft Punk - French electronic music group
* Netherlands - Scandinavia and the World - webcomic featuring cartoon version of Netherlands
* Denmark - ???

**Comment by TheJaredWilcurt** [comment]
@phpgeek 

There is a new release of Scout-App available for download. It has the King of The Hill Danish flag and the best translations I could do. If you see anything that needs corrected it will go into the next version.

* [Scout-App.io](http://scout-app.io)
* [Release Notes](https://github.com/scout-app/scout-app/releases)
