### ISSUE TITLE
Replicate scout in command line

### ISSUE THREAD

**Issue by szepeviktor** [scout-app/scout-app#258]
Good morning!

I have a sitebuilder who is using Scout.
Could you provide a sass command line to do exactly the same?

Thank you.

**Comment by szepeviktor** [comment]
Or is there a debug mode that reveals sass options?

**Comment by TheJaredWilcurt** [comment]
In Scout-App 2 you can go to `View > Dev Tools > Console Tab` and type in the following: 

```javascript
console.table(scout.projects);
```

You'll find in there a listing of your projects. Including their Project Name and Project ID.

![example](https://cloud.githubusercontent.com/assets/4629794/18273980/24d7cf92-740e-11e6-910b-3986b229bdd5.png)

In a future version of Scout-App, You will be able to run it from the command line passing in project ID's. It will auto-launch the application (the GUI) and start running the projects that were passed in. Like so:

```sh
Scout-App.exe sa1472325910871,sa1472063939517,sa1472646123304
```

I'm still trying to figure out a better way of giving access to these Project ID's in the UI, so users of Scout-App's CLI features won't be required to open the dev tools.

For more powerful command line tools related to Sass, you can install [Node](http://nodejs.org) and the Node module [Node-Sass](https://www.npmjs.com/package/node-sass), or simply follow some Gulp tutorials on how to set up Sass with Gulp. Scout-App is a GUI for Node-Sass which is command line based. So it wouldn't make sense for us to build a versatile command line system on top of a GUI that's built on top of an existing command line tool. Just use the existing command line tool.

* * *

**See:** Issue https://github.com/scout-app/scout-app/issues/172

**Comment by TheJaredWilcurt** [comment]
Added this to the [Project Road Map](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance) for future versions of Scout-App.

* [Scout-App.io](http://scout-app.io)

**Comment by szepeviktor** [comment]
@TheJaredWilcurt Thank you.

Now I reveal my secret.
The sitebuilder uses Scout on Windows, I use npm/sass and our output CSS is different.

Could you help me to determine Scouts sass parameters so I can enter it on the command line as
`sass --this --line-numbers --that --etc style.scss style.css`

**Comment by TheJaredWilcurt** [comment]
The code isn't minified in the app. So [download it](http://scout-app.io/#downloads-and-video), use the same settings as your designer, and then put a break point around line 115 in `scout-files\_scripts\app.js`:

* https://github.com/scout-app/scout-app/blob/master/scout-files/_scripts/app.js#L115

You'll see exactly what options are being passed to Node-Sass when you run your project.

It would look something like this:

```
{
    'file': 'D:\GitHub\scout-app.github.io\_sass\style.scss',
    'indentedSyntax': true,
    'outfile': false,
    'outputStyle': 'compressed',
    'sourceComments': false,
    'sourceMap': false,
    'sourceMapContents': false
}
```

However you should verify that your designer is using Scout-App 2.0.2 (latest stable). If they are using 2.0.0 or 2.0.1, they should upgrade (those are beta releases). If they are using 0.7.1 or below, that is Scout-App Classic (2012). I didn't work on it, so I won't be of much help.

* [Scout-App.io](http://scout-app.io)

**Comment by szepeviktor** [comment]
Thank you very much!

**Comment by szepeviktor** [comment]
For googlers:
```bash
sass --style expanded --line-numbers style.scss  styleV.css
```
