### ISSUE TITLE
App crashing after adding variables

### ISSUE THREAD

**Issue by EldrikKellsy** [scout-app/scout-app#265]
Works just fine with mixins, but if I try to add some variables it starts crashing after pressing "play" button.

OS: Windows 10

**Comment by EldrikKellsy** [comment]
So, I just reinstalled the app and its working now! =)

**Comment by TheJaredWilcurt** [comment]
Are you using the [Scout-App v2.0.2](http://scout-app.io) (2016)?

No installation should be required. Just unzip/double-click. It's a portable app.
