### ISSUE TITLE
Translated Scout-App to Spanish

### ISSUE THREAD

**Issue by ireneml-fr** [scout-app/scout-app#268]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
Thanks so much! This is awesome. Spanish will be in the next release of Scout-App.

What culturally relevant image do you want used for the Spanish meme. Something that native speakers would recognize. Here are some examples:

* https://github.com/scout-app/scout-app/tree/master/scout-files/cultures#memes

**Comment by ireneml-fr** [comment]
You are Welcome!!. Thank you for your scout app.


I think this image is culturally relevant for Spanish meme and it is labeled for reuse. All native speakers would recongnize it for sure ;).




Best Regards.

Ireneml.fr






________________________________
De: The Jared Wilcurt <notifications@github.com>
Enviado: miércoles, 5 de octubre de 2016 15:40
Para: scout-app/scout-app
Cc: ireneml-fr; Author
Asunto: Re: [scout-app/scout-app] Translated Scout-App (#268)


Thanks so much! This is awesome. Spanish will be in the next release of Scout-App.

What culturally relevant image do you want used for the Spanish meme. Something that native speakers would recognize. Here are some examples:

  *   https://github.com/scout-app/scout-app/tree/master/scout-files/cultures#memes

-

**Comment by TheJaredWilcurt** [comment]
@ireneml-fr 

No image was attached. Can you upload it here:

https://github.com/scout-app/scout-app/issues/268

**Comment by TheJaredWilcurt** [comment]
Also what is the Alt text for it, for those with screen readers. It would go under `"TRANSLATOR_MEME": "` in the [Google Sheet](https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing).

**Comment by ireneml-fr** [comment]
Irene ml ha compartido un archivo de OneDrive con usted. Para verlo, haga clic en el vínculo siguiente.


<https://1drv.ms/u/s!ApKrtzAAPsMOg3UyTG4txofOkyoP>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://1drv.ms/u/s!ApKrtzAAPsMOg3UyTG4txofOkyoP>

188px-Bandera_de_España_con_Don_Quijote_y_el_Molino_de_viento.png<https://1drv.ms/u/s!ApKrtzAAPsMOg3UyTG4txofOkyoP>




I have uploaded the image, but I´m not sure if I have made it in the correct place. The image is free for reuse and modifications.



________________________________
De: The Jared Wilcurt <notifications@github.com>
Enviado: miércoles, 5 de octubre de 2016 16:41
Para: scout-app/scout-app
Cc: ireneml-fr; Mention
Asunto: Re: [scout-app/scout-app] Translated Scout-App to Spanish (#268)


@ireneml-fr<https://github.com/ireneml-fr>

No image was attached. Can you upload it here:

#268<https://github.com/scout-app/scout-app/issues/268>

-

**Comment by TheJaredWilcurt** [comment]
![Don Quixote](https://cloud.githubusercontent.com/assets/4629794/19122766/f00e66ec-8af9-11e6-8a4b-cee4ed5a4ae9.png)

Is there any text you'd like placed on the image. The other ones all have something Sass or CSS related.

Maybe something like this:

![Quote](https://cloud.githubusercontent.com/assets/4629794/19122996/f20cd0ea-8afa-11e6-8697-f86625df0984.jpg)

but changed to something like this (but in Spanish)

> Too much CSS may be madness. And maddest of all, to see CSS as it is and not as it should be.

**Comment by ireneml-fr** [comment]
That text is excellent for the meme.


"DEMASIADO CSS PUEDE SER LA PEOR DE LAS LOCURAS.
VER CSS COMO ES Y NO COMO DEBERÍA SER."



________________________________
De: The Jared Wilcurt <notifications@github.com>
Enviado: miércoles, 5 de octubre de 2016 19:00
Para: scout-app/scout-app
Cc: ireneml-fr; Mention
Asunto: Re: [scout-app/scout-app] Translated Scout-App to Spanish (#268)


[Don Quixote]<https://cloud.githubusercontent.com/assets/4629794/19122766/f00e66ec-8af9-11e6-8a4b-cee4ed5a4ae9.png>

[https://cloud.githubusercontent.com/assets/4629794/19122766/f00e66ec-8af9-11e6-8a4b-cee4ed5a4ae9.png]

Is there any text you'd like placed on the image. The other ones all have something Sass or CSS related.

Maybe something like this:

[Quote]<https://cloud.githubusercontent.com/assets/4629794/19122996/f20cd0ea-8afa-11e6-8697-f86625df0984.jpg>

[https://cloud.githubusercontent.com/assets/4629794/19122996/f20cd0ea-8afa-11e6-8697-f86625df0984.jpg]

but changed to something like this (but in Spanish)

Too much CSS may be madness. And maddest of all, to see CSS as it is and not as it should be.

-

**Comment by TheJaredWilcurt** [comment]
This has been [merged into the master branch](https://github.com/scout-app/scout-app/commit/21e973c202b916edb4ea712d52f786402075d8d0). It will be in the next version of Scout-App.

![es](https://cloud.githubusercontent.com/assets/4629794/19130993/9b4879dc-8b1b-11e6-811e-a702bef01ebb.png)

I'll notify you when the next version is released. ¡Gracias de nuevo!

**Comment by ireneml-fr** [comment]
It has been a pleasure working with you. If you need me for another English-Spanish translation you can count on me.


Ireneml.fr



________________________________
De: The Jared Wilcurt <notifications@github.com>
Enviado: miércoles, 5 de octubre de 2016 22:50
Para: scout-app/scout-app
Cc: ireneml-fr; Mention
Asunto: Re: [scout-app/scout-app] Translated Scout-App to Spanish (#268)


This has been merged into the master branch<https://github.com/scout-app/scout-app/commit/21e973c202b916edb4ea712d52f786402075d8d0>. It will be in the next version of Scout-App.

[es]<https://cloud.githubusercontent.com/assets/4629794/19130993/9b4879dc-8b1b-11e6-811e-a702bef01ebb.png>

I'll notify you when the next version is released. ¡Gracias de nuevo!

-

**Comment by TheJaredWilcurt** [comment]
@ireneml-fr 

This is in the latest release of Scout-App.

* [Scout-App.io](http://scout-app.io)
