### ISSUE TITLE
Translated Scout-App into French

### ISSUE THREAD

**Issue by AnotherJavaCoder** [scout-app/scout-app#271]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
Thanks so much for improving the French translation of Scout-App. I've [merged the changes](https://github.com/scout-app/scout-app/commit/94bd04ec10884b93830e7a7f0b24545f856d05c6) into the master branch.

It will be in the next release of Scout-App. I'll notify you when it's out.

**Comment by TheJaredWilcurt** [comment]
@AnotherJavaCoder 

This is in the latest release of Scout-App.

* [Scout-App.io](http://scout-app.io)
