### ISSUE TITLE
Multiple outputs in one project

### ISSUE THREAD

**Issue by merfire** [scout-app/scout-app#277]
Hi,
Great app really love it. 
A question or a feature request, is there a option to add multiple outputs in one project ?
Kind of like this:
input: sass/style.sass
output1: css/style.css
output2: css/style.min.css
One for normal css, two for compressed?
Thanks :)

**Comment by TheJaredWilcurt** [comment]
@merfire 

You can do this, though it's a bit of a workaround. Here's a short video explaining how to set this up.

* https://youtu.be/a-DDCOjXcGs

**Comment by merfire** [comment]
Thank you very much for such fast response and the video, that's exactly what I needed. Thanks, you are the best!!!
