### ISSUE TITLE
Tray icon/Minimize to tray

### ISSUE THREAD

**Issue by TheJaredWilcurt** [scout-app/scout-app#278]
Rather than show the full-width application open in the task bar, allow it to hide away in the system tray next to the clock so people can leave it running, monitoring for changes and displaying alerts as needed.

**Feature status:** Planned, low priority, will accept PR's

**Comment by jaumesegarra** [comment]
Please check my fork: https://github.com/jaumesegarra/scout-app Implemented this!

**Comment by TheJaredWilcurt** [comment]
Feature is in current `master` branch and will be in next version of Scout-App.

**Comment by TheJaredWilcurt** [comment]
@jaumesegarra 

Closing ticket. This has been released in [Scout-App 2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16).
