### ISSUE TITLE
Multiple input folders..

### ISSUE THREAD

**Issue by fastmap** [scout-app/scout-app#29]
Can we specify multiple input folders? I also noticed that navigating the input folders text box is very slow. Has anyone else experienced this?

**Comment by TheJaredWilcurt** [comment]
@fastmap 

The latest version of Scout-App is considerably faster than Scout-App Classic. You cannot however have multiple input folders. This is an intended limitation for the purposes of making the interface as intuitive and easy to understand as possible. You can however run multiple projects at the same time and have each project have a different input folder but the same output folder.

Closing this issue as "will not fix".

* [Scout-App.io](http://Scout-App.io)
