### ISSUE TITLE
Translated Scout-App to Vietnamese

### ISSUE THREAD

**Issue by baivong** [scout-app/scout-app#290]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

![sass... sass everywhere](https://cloud.githubusercontent.com/assets/5460915/20680534/01c6cae8-b5d2-11e6-833e-edb1828b9689.jpg)

**Comment by TheJaredWilcurt** [comment]
Thanks so much!

The next version of Scout-App will have a few more lines of text that will need translated. We are finalizing the language for them now. I'll keep you informed of when the text is updated, should be soon.

**Comment by baivong** [comment]
I've updated translations for the new text.

**Comment by TheJaredWilcurt** [comment]
This has been updated in the master branch and will be in the next version of Scout-App. I'll let you know when it comes out.

**Comment by TheJaredWilcurt** [comment]
The new version of Scout-App 2 is out and contains your translations. Thank you so much for making Scout-App accessible to more people.

* https://github.com/scout-app/scout-app/releases/tag/v2.12.12

You are listed as a contributor on the website, let me know if you want your name or URL changed on the website.

* http://scout-app.io/#contributors
