### ISSUE TITLE
Translation for Traditional Chinese (zh-CHT)

### ISSUE THREAD

**Issue by shiaoshin** [scout-app/scout-app#291]
I can create a new column for simplified Chinese version (zh-CN) too but some of the technical jargons might not be a 100% match.
https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit#gid=1819360077

**Comment by TheJaredWilcurt** [comment]
@shiaoshin 

Is there a culturally relevant image you want used with this translation:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by shiaoshin** [comment]
Looking for a meme...

**Comment by shiaoshin** [comment]
Here's the image:
![zh-cht](https://cloud.githubusercontent.com/assets/6443835/20844696/b5730366-b886-11e6-89e7-08f59767668c.jpg)

**Comment by TheJaredWilcurt** [comment]
is it `zh-CHT` or `zh-TW`

and are these the correct characters in the image: `CSS 鄙礻見金連`

**Comment by shiaoshin** [comment]
Sorry for the confusion here. It should be zh-CHT as it contains multiple region specific culture codes (TW, HK and MO)
the Character in the image is "CSS 鄙視鏈", I've updated the google doc as well.

**Comment by TheJaredWilcurt** [comment]
![zh-cht](https://cloud.githubusercontent.com/assets/4629794/20871889/0c336898-ba68-11e6-9f1d-1abbf5d2080e.jpg)

The low resolution was bugging me, so I just redrew the image.

All the latest translations are in master branch and will be in the next release of Scout-App. I'll let you know when it comes out.

**Comment by shiaoshin** [comment]
That's awesome, thank you!

**Comment by shiaoshin** [comment]
Awesome, thanks a lot!

**Comment by TheJaredWilcurt** [comment]
The new version of Scout-App 2 is out and contains your translations. Thank you so much for making Scout-App accessible to more people.

* https://github.com/scout-app/scout-app/releases/tag/v2.12.12

You are listed as a contributor on the website, let me know if you want your name or URL changed on the website.

* http://scout-app.io/#contributors
