### ISSUE TITLE
Spanish Translation updates

### ISSUE THREAD

**Issue by ireneml-fr** [scout-app/scout-app#294]
New translation corrected and turned it black can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
Changes have been committed to the master branch and will be in the next release of Scout-App. I'll let you know when it comes out.
