### ISSUE TITLE
Hungarian Translation updates

### ISSUE THREAD

**Issue by w3suli** [scout-app/scout-app#295]
**Hungarian translation updated.**

New hungarian translation can be found at:

* [https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing)

**Comment by TheJaredWilcurt** [comment]
The localization file has been updated and is in the master branch. This will be in the next release of Scout-App. I'll let you know when it comes out.

**Comment by TheJaredWilcurt** [comment]
The new version of Scout-App 2 is out and contains your translations. Thank you so much for making Scout-App accessible to more people.

* https://github.com/scout-app/scout-app/releases/tag/v2.12.12

You are listed as a contributor on the website, let me know if you want your name or URL changed on the website.

* http://scout-app.io/#contributors
