### ISSUE TITLE
Translated Scout-App to Finnish

### ISSUE THREAD

**Issue by httpsterio** [scout-app/scout-app#306]
Yo, I just translated Scout-App to Finnish.

New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@httpsterio 

Thanks! Do you have a culturally relevant image and CSS/Sass related text to go with it for Finnish?

This will explain more of what I mean:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by TheJaredWilcurt** [comment]
@httpsterio

**Comment by httpsterio** [comment]
Oh god sorry for the late response. I don't actually know any local memes. I can try to think of one and i'll get back to you today :)

**Comment by TheJaredWilcurt** [comment]
@httpsterio cool, let me know what you come up with

**Comment by TheJaredWilcurt** [comment]
@httpsterio 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
