### ISSUE TITLE
Translated Scout-App to Hebrew (he)

### ISSUE THREAD

**Issue by Wootness** [scout-app/scout-app#310]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

Added translations for every row in the 'he' column in the shared spread sheet.
Some fields were already present but their notes included 'Based on google translate'. I changed the incorrect ones and left those which were correct as-is.

Some tweaking might be needed for sentences containing both Hebrew and English since Hebrew is RTL and that might mess up the order of word in the sentence.

**Comment by TheJaredWilcurt** [comment]
@Wootness 

Thanks! Do you have a culturally relevant image and CSS/Sass related text to go with it?

For example:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by Wootness** [comment]
Yeah sure, here's the image:
![zjshcds](https://cloud.githubusercontent.com/assets/10898152/21471916/c1638e64-cacb-11e6-918a-33aa14741a71.png)

The text is a play on words based on the song 'Badad' by the Israeli artist Zohar Argov (shown in the image).
The word Badad (בדד) in hebrew means "alone" and when trying to write the word but with Caps Lock activated it comes out as "CSS" so replacing the words in the chorus give us:
"CSS I shell go, without even a prayer,
CSS, without a future, without hope, without a dream"

It works better in Hebrew as the song is a classic.

**Comment by TheJaredWilcurt** [comment]
Awesome, I've added it to the app. When testing I noticed this:

![Error Message](https://cloud.githubusercontent.com/assets/4629794/21511294/ee7b9426-cc6c-11e6-994b-5e5178b85ed0.png)

The formatting should look like this:

![Error Message](https://cloud.githubusercontent.com/assets/4629794/21511342/be126084-cc6d-11e6-9dfe-1cad5ad42c4d.png)

`(0x01)` is an error code.

**Comment by Wootness** [comment]
Yeah I see the problem.
Seems like the middle part of the text, where is says 'Error (0x01)' started from right to left but then switched to left to right at the 'x'
![image](https://cloud.githubusercontent.com/assets/10898152/21517268/3e63ed66-cce6-11e6-8e18-c348ad294dc0.png)

If you could set the direction of this line to RTL for Hebrew it might fix it
Otherwise, maybe you can split the "Error" text and the error code into 2 different divs?

**Comment by TheJaredWilcurt** [comment]
I created a new class, `.rtl { direction: rtl; }`. Before displaying the alert, we check to see if the culture code equals `he` or `fa`, and if so, apply that class to it.

Now it looks like this:

![RTL error](https://cloud.githubusercontent.com/assets/4629794/21522286/4405465c-ccd2-11e6-9851-8c7b1586fba4.png)

Can you run the app locally and check for any more bugs like that. I have not worked with RTL before, so I'll need to do more research on how best to implement a dynamic solution for switching between LTR and RTL on the fly.

**To run locally the first time:**

1. Download and Install Node.js (v4 or higher) - http://nodejs.org
1. Download and Install Git - http://git-scm.com
1. In your command line or terminal, `cd` to where you want to store your copy of Scout-App's source code.
1. Run `git clone https://github.com/scout-app/scout-app.git`
1. Run `npm install`
1. Run `npm start`

If you have any issues running locally, you can view the documentation:

* https://github.com/scout-app/scout-app/blob/master/documentation/contributing.md#running-scout-app-locally-for-development

**To run locally subsequent times:**

1. In your terminal/command line `cd` into the folder with Scout-App's source code
1. Run `git checkout master` (Makes sure you are on the right branch)
1. Run `git pull origin master` (updates the branch)
1. Run `git pull origin` (updates the version tags)
1. Run `npm install` (updates dependencies)
1. Run `npm start` (starts Scout-App)

**Comment by Wootness** [comment]
Well there are a couple of big steps everyone must pass when adapting a LTR ui for RTL languages.
You could choose to do the minimum for convenience or to go out of your way to line up every single element.
A few Examples:
![image](https://cloud.githubusercontent.com/assets/10898152/21522951/8d06faf4-cd12-11e6-85db-6eec99f7ed4d.png)
Those titles do not show properly.
The more problematic issue is that the colon is to the right of the words, it should be at the left:
![image](https://cloud.githubusercontent.com/assets/10898152/21523000/ef7f9d9e-cd12-11e6-816b-1db93a7ecc7b.png)
Next thing to do would be move the icons to the right of the words, just like they are to the left in English:
![image](https://cloud.githubusercontent.com/assets/10898152/21523073/76492282-cd13-11e6-9dea-b402807dde80.png)

Another something which seems a little off is:
![image](https://cloud.githubusercontent.com/assets/10898152/21523217/d4968518-cd14-11e6-96b3-087d913bda55.png)
The checkboxes should be to the right of the text:
![image](https://cloud.githubusercontent.com/assets/10898152/21523241/03eb4ae2-cd15-11e6-80d8-582c17d1e2ae.png)

This as you can see RTL text in must be taken into account in multiple areas in the code. which might add 'noise' to your current codebase (depends on how you take it).

There are a more like those. How do you want to tackle them?

**Comment by TheJaredWilcurt** [comment]
I'm for this, I just need to find some time to work on it to see how best to implement it.

**Comment by TheJaredWilcurt** [comment]
Well, it took a few months, but I've got a good functioning `rtl` branch that I'll be merging into master soon.

**Comment by DarienSpencer65** [comment]
Good to hear! Tell me when it's merged if you need help verifying everything's in place

**Comment by Wootness** [comment]
Hey there!
I've updated the spreadsheet again, new strings were added and translated using Google Translate
Some of them were a little off.

**Comment by TheJaredWilcurt** [comment]
@Wootness 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
