### ISSUE TITLE
Translated Scout-App to Polish!

### ISSUE THREAD

**Issue by gr0hiik** [scout-app/scout-app#311]
Hi guys!

A new translation to Polish language can be found at:

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

Cheers!

**Comment by TheJaredWilcurt** [comment]
@gr0hiik 

Thanks! Do you have a culturally relevant image and CSS/Sass related text to go with it?

For example:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by gr0hiik** [comment]
Sure - you can find it here:

http://i.imgur.com/Cpos3C9.png

**Comment by TheJaredWilcurt** [comment]
Awesome! It's been updated and merged into the master branch. Polish will be in the next version of Scout-App. I'll notify you of when it's released.

**Comment by TheJaredWilcurt** [comment]
@gr0hiik 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
