### ISSUE TITLE
Hungarian translation updated.

### ISSUE THREAD

**Issue by w3suli** [scout-app/scout-app#312]
**Hungarian translation updated.**

Updated translation can be found at:

* [https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing)

* https://github.com/w3suli/scout-app-hungarian-translated

**Comment by TheJaredWilcurt** [comment]
Cool, the latest version has been added to the master branch. It will be in the next release, I'll let you know when the next version is released.

**Comment by TheJaredWilcurt** [comment]
@w3suli 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
