### ISSUE TITLE
w3suli.com theme updated.

### ISSUE THREAD

**Issue by w3suli** [scout-app/scout-app#313]
Hamburger lines menu disabled.

Theme file:
https://github.com/w3suli/scout-app-w3suli-theme

**Comment by TheJaredWilcurt** [comment]
I've added the updated file to the master branch. It will be in the next version. I'll let you know when it is released.

**Comment by TheJaredWilcurt** [comment]
Closing ticket. This has been released in [Scout-App 2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16).
