### ISSUE TITLE
Bulgarian translation for Scout-App

### ISSUE THREAD

**Issue by ReXTaN** [scout-app/scout-app#314]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@ReXTaN 

Thanks! Do you have a culturally relevant image and CSS/Sass related text to go with it?

For example:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by ReXTaN** [comment]
@TheJaredWilcurt 

Sorry! Right now I don't have any good relevant image. :/
Is it necessary? Or maybe I'll find/create one in the future when I get the "inspiration" for that.

**Comment by ReXTaN** [comment]
Today I saw that some of them were in red maybe because I missed them. So I corrected them.

**Comment by TheJaredWilcurt** [comment]
Cool. Just try to find something culturally relevant. A reference Bulgarian people would get.

**Comment by TheJaredWilcurt** [comment]
@ReXTaN 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
