### ISSUE TITLE
Translated Scout-App (German de-de)

### ISSUE THREAD

**Issue by SirTobey1337** [scout-app/scout-app#315]
New translation of German can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
Thanks so much for translating the app.

Most of the German was already done by Google translate. Can you verify that anything that was machine translated was correct and if so, remove the "Google Translated" note from it. And of course, if it isn't correct, then modify it.

Do you have a site you want your name to link to? I've added your GitHub URL currently.

What image do you want to go with you `Fischers Fritze fischt frische Fische` text?

**Comment by ThomasJanotta** [comment]
Hi, I updated the German version again. As TheJaredWilcurt said, the 'Google Translated' can be removed.

**Comment by TheJaredWilcurt** [comment]
@ThomasJanotta 

What image do you want shown for German, here are examples:

https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by ThomasJanotta** [comment]
Hi, what about a fish tangram :-)
![sass-fish-german](https://cloud.githubusercontent.com/assets/8110641/21795141/6202a702-d700-11e6-87b9-1c5b5cdccd43.jpg)

**Comment by TheJaredWilcurt** [comment]
The fish is cool, but you don't have to put the Hank Hill text under it. That's just what the American version says because there is a picture of Hank Hill.

Can you come up with a version of `Fischers Fritze fischt frische Fische` that has something to do with Sass or CSS? If not, just putting `Fischers Fritze fischt frische Fische` is still better than the unlrelated `Ich verarbeite Sass und Sass Mixins`.

**Comment by ThomasJanotta** [comment]
Ah yes, I got the point :-). I don't watch Hank. By the way there is a german tv cook (in the north programmes) called Rainer Sass. So I use it:
Peter Piper picked a peck of pickled pepper, prepared by Sass. How about that?
![sass-fish-german1](https://cloud.githubusercontent.com/assets/8110641/21795719/4d6a7bfe-d704-11e6-868a-4ead7368d7e4.jpg)

**Comment by SirTobey1337** [comment]
@ThomasJanotta Nicely made, I'll second that one!

@TheJaredWilcurt Excuse the delay, as Thomas already said, the Google versions I didn't touch were just fine.

**Comment by TheJaredWilcurt** [comment]
lol, I totally didn't realize that Thomas wasn't the original poster of this issue. I have been talking to two different people without realizing it.

@SirTobey1337 if you did the bulk of German cleanup, then you can choose the picture and text for it. Let me know if you want it changed.

**Comment by SirTobey1337** [comment]
@TheJaredWilcurt I'm totally fine with Thomas image. The text 'Fischers Fritze fischt frische Fische' was originally written by me. I didn't know there was a German cook with that name, but if so, this is an excellent linking to Sass. So +1 to migrate to Thomas version/image.

**Comment by TheJaredWilcurt** [comment]
@ThomasJanotta @SirTobey1337 

Great! The latest translations and the image have been added to the `master` branch. They will be in the next version of Scout-App. I'll let you know when it is released.

For the time being if you would like to use the translations in the already released Scout-App v2.12.12, you can manually download the `dictionary.json` and `de.jpg` from here:

* https://github.com/scout-app/scout-app/tree/master/scout-files/cultures

Then place them in your Scout-App folder under: `Scout-App/scout-files/cultures`.

**Comment by TheJaredWilcurt** [comment]
@SirTobey1337 @ThomasJanotta 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
