### ISSUE TITLE
New on Scout : no mixin named output-rhythm

### ISSUE THREAD

**Issue by webmasterpf** [scout-app/scout-app#325]
Hi,
I usually use compas on a LAMP server in command line, but,  I don't have LAMP local server anymore. So I use Scout (2.6.8) to compile my sass code.
But, this last, say "no mixin named output-rhythm" for my normalize.scss and doesn't to go on, my code isn't compile so.
Never had this issue witch command line compilation on LAMP.
An idea to fix this ?

Thanks

**Comment by TheJaredWilcurt** [comment]
@webmasterpf 

Scout-App 2 no longer relies on Java, Adobe Air, or Ruby to run. Compass (no longer maintained) only works with the Ruby version of Sass (maintenance planned to end in less than a year). Scout-App 2 uses Node-Sass instead. So full Compass support is not planned, however the Compass mixin library ships with Scout-App 2, as do many other popular mixin libraries.

The particular mixin you are referencing, `output-rhythm`, does not come from Compass. I did find a library that [does have this mixin](https://github.com/zellwk/vertical-rhythms-without-compass/blob/master/vertical-rhythms/_vertical-rhythms.scss#L73) built in. You can download this other mixin library yourself and manually import it into your Sass:

* https://github.com/zellwk/vertical-rhythms-without-compass

**Comment by webmasterpf** [comment]
My scss file come from there : https://github.com/JohnAlbin/normalize-scss
Seem there is an update to avoid the compass issue. I will to try to replace my normalize.scss file by the updated one.

Thanks to put me on the path.

**Comment by webmasterpf** [comment]
Last version 6 seem to work,but I have another errors about compass components like breakpoint.I go to update or replace them, one by one.
