### ISSUE TITLE
Updated Dutch Translations for Scout-App

### ISSUE THREAD

**Issue by yowkah** [scout-app/scout-app#328]
* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

quick note.
Biggest change i made is the word group which i translate to the word "verzameling"  instead of "groep".
This is because "verzameling" is the equivalent of a collection in dutch, where as a "groep" implies it's a group of people. not just a group of anything. 

other updates were primarily just replacements of google translates ( or just accepting them)

**Comment by TheJaredWilcurt** [comment]
@yowkah 

Thanks so much. This will be in the next release of Scout-App. I'll let you know when that comes out.

Feel free to update the `TRANSLATOR` and `TRANSLATOR_URL` to add a comma space then your info. See the French versions of these keys for an example.

**Comment by TheJaredWilcurt** [comment]
@yowkah 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
