### ISSUE TITLE
Translated Scout-App :: French

### ISSUE THREAD

**Issue by ghost** [scout-app/scout-app#329]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
Thanks, merged into current master branch. Will be in the next release.

**Comment by TheJaredWilcurt** [comment]
@ghost

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
