### ISSUE TITLE
Scout App 2 writes blank scss.scss file

### ISSUE THREAD

**Issue by decombs12** [scout-app/scout-app#331]
OS: Windows 7 SP1
Scout-App Version: 2.12.12
Information from Dev Tools: Using Sublime Text 3, Brackets 1.9, Chrome 57.0.2987.133

(Attach screenshot below)
This is all I have from Scout to show that it wrote to scss.scss
5:22:55 PM scss\scss.scss
I was trying to get it to write to style.css (but Scout took it upon itself to write to the above scss file) after importing a bootstrap stylesheet.
Like so - @import 'vendors/_bootstrap.scss';

When opening scss.scss I find a blank page. Zip, zero, nada.

Any help would be greatly appreciated.

**Comment by TheJaredWilcurt** [comment]
Scout-App doesn't write to any files. It scans the contents of the input directory, if an item in the input is a file that does not start with `_` and ends with either `.scss` or `.sass`, then it's file path will be passed in to Node-Sass along with a matching output filepath. If an item in the input is a folder, then Scout-App will scan the contents of that folder in the same way and create a matching subfolder in the output directory.

So if your input directory is `C:\projects\repo\sass` and your output is `C:\projects\repo\css`, then the filepaths passed to Node-Sass will look something like:

```
Input: C:\projects\repo\sass\file.sass
Output: C:\projects\repo\css\file.css
```

You can actually see the function that handles this process:

* https://github.com/scout-app/scout-app/blob/master/scout-files/_scripts/app.js#L91

At no point does Scout-App ever touch any of the files in the input folder, it only gets the file names and gives the paths to Node-Sass to read the contents and produce an output.

Scout-App only knows the file path to the file, it never reads/writes to them. Node-Sass (inside of Scout-App), only ever *reads* from the input folder, and only *writes* to the output folder.

It's possible that there could be a conflict with another program if Node-Sass is accessing the file at the same time another program is accessing it. But I don't know why that would cause the file written over with a blank file.

* [I was unable to reproduce this issue](https://youtu.be/tJVhZRzpRw0)

**Comment by decombs12** [comment]
I appreciate your explaining who is doing what within Scout App. Naturally I only wanted the app to work for me. It now does. I include the following for the sake of anyone who comes across this in the future.

I simply erased the files within the CSS folder, leaving only the bootstrap.css file, and opened up Scout App again and hit "play." Node-Sass wrote a 120 kb file in little time and I'm back to work with the next lesson.

I even erased the whole project and started all over again so I could an "expanded" version of the file (now a chubby 144 kb) and it worked a treat.

So, it really wasn't a problem after all. Just a hiccup for some reason, operator error.

Thanks chief!
