### ISSUE TITLE
Translated Scout-App: Arabic

### ISSUE THREAD

**Issue by mrg0lden** [scout-app/scout-app#332]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@mrg0lden 

Hey, that's awesome! Arabic will be in the next release of Scout-App (after I work in a system to handle RTL).

What culturally relevant image would you like to see in the app that Arabic speakers would understand. Here are examples:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md

**Comment by mrg0lden** [comment]
Sorry, I forgot about it.

**Comment by TheJaredWilcurt** [comment]
@mrg0lden 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
