### ISSUE TITLE
Merge compiled CSS

### ISSUE THREAD

**Issue by lordcatalien** [scout-app/scout-app#335]
Is there a way to merge individual compiled CSS files into one or two, like "vendor.css" and "app.css"?

**Comment by TheJaredWilcurt** [comment]
You can import `.sass`, `.scss`, and `.css` files into your `.sass`/`.scss` file.

`example.scss`
```sass
@import "_vendor.sass";
@import "_header.scss";
```
Starting a filename with an `_` will cause it to be skipped/not processed to CSS.

When importing files you can leave off the `_` and the `.sass`, `.scss`, or `.css` and the Sass processor will still know which file to import.

```sass
@import "vendor";
@import "header";
```
If you import a CSS file without the extension it will pull in all the contents and put it in the output file. If you import it with the extension then the import line will remain in the output and it will cause a network request in the browser to download the other file.

Here is a sample file for how to best organize and import your files into your main Sass file:

* https://gist.github.com/TheJaredWilcurt/fe38f814d73edbce2610fdaef7dc3391

**Comment by vvratnas** [comment]
Hi, I am trying to merge different scss files into one, does this below entries work:
<link rel="stylesheet" href="${URLUtils.staticURL('/scss/global.scss')}" />
<link rel="stylesheet" href="${URLUtils.staticURL('/scss/global.scss')}" />
<link rel="stylesheet" media="print" href="${URLUtils.staticURL('/scss/skin/skin.scss')}" />
<link rel="stylesheet" href="${URLUtils.staticURL('/scss/homePage.scss')}" />
