### ISSUE TITLE
Translated Scout-App :: Turkish

### ISSUE THREAD

**Issue by cemaltaskiran** [scout-app/scout-app#338]
I translated for Turkish New translation can be found at

*https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@cemaltaskiran 

Thanks so much, what culturally relevant image would you like for Turkish.

* [Examples](https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md)

**Comment by cemaltaskiran** [comment]
http://i.imgur.com/VaBYyRj.jpg

**Comment by TheJaredWilcurt** [comment]
@cemaltaskiran 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
