### ISSUE TITLE
Translated Scout-App :: zh-CN(Simplified) 简体中文

### ISSUE THREAD

**Issue by alafly** [scout-app/scout-app#339]
New zh-CN(Simplified) 简体中文 translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by alafly** [comment]
![developer](https://user-images.githubusercontent.com/29738416/27617375-e1e0df72-5b83-11e7-8898-c812956240c1.jpg)

**Comment by alafly** [comment]
^
culturally relevant image     |

**Comment by TheJaredWilcurt** [comment]
@alafly 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
