### ISSUE TITLE
Output Modes

### ISSUE THREAD

**Issue by fredcerdeira** [scout-app/scout-app#34]
I choose the output Style "compressed" but every time that a make a change in the .scss file, the output renders a random between compressed, nested, compact and extended. 

I would like to have the same style in every save, any ideas about this issue?

tks

**Comment by TheJaredWilcurt** [comment]
@fredcerdeira @impressivewebs @winghouchan

Scout-App is being maintained again and has a new version.

Issue is resolved. Closing issue. Download the latest version of Scout-App.

* [Scout-App 2](http://Scout-App.io) (2016)

**Comment by impressivewebs** [comment]
Good to know, thanks for letting us know. Glad it's being worked on again.

**Comment by TheJaredWilcurt** [comment]
@impressivewebs oh hey, you're quoted on the site

* http://scout-app.io/#quotes

That section is actually currently being redesigned by @kimmihack

* http://i.imgur.com/gpEGWaK.jpg

**Comment by impressivewebs** [comment]
@TheJaredWilcurt Nice, thanks for letting me know about that, I hadn't seen that.

FYI - I do a newsletter called [Web Tools Weekly](http://webtoolsweekly.com/), so I'll be sure to include the new version in an upcoming issue.

**Comment by TheJaredWilcurt** [comment]
@impressivewebs Awesome, let me know when it comes out, I've been checking the [archive on the site](http://webtoolsweekly.com/#archive).

**Comment by TheJaredWilcurt** [comment]
yay! http://webtoolsweekly.com/archives/issue-163

**Comment by impressivewebs** [comment]
Haha, yeah, I just happened to have enough links for a "Sass" list, so it worked out. :)
