### ISSUE TITLE
Translated Scout-App es-AR

### ISSUE THREAD

**Issue by wadiJay** [scout-app/scout-app#340]
Hey, guys, added an Argentinean Spanish variation for Scout-App:
* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

Here's the culturally relevant image:
![cx5vqf](https://user-images.githubusercontent.com/19226919/27837097-c5f1ad02-60b8-11e7-8a3e-1f4826795f2d.jpg)

He's from an old Mexican sitcom (1970-90s) that was incredibly popular throughout Latin America.
He had a tag line whenever he was excited or happy that sounded like "Sas", hence the image.

**Comment by TheJaredWilcurt** [comment]
@wadiJay 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
