### ISSUE TITLE
Translated Scout-App (Brazilian Portuguese)

### ISSUE THREAD

**Issue by thiagomallet** [scout-app/scout-app#342]
Hi,
I reviewed and improved the Scout-App's brazilian portuguese translation.

I'd like to know how to send you the customized language image for the "Preferences" page.

New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@thiagomallet 

Thanks so much for the translation, you can attach the image in a response to this issue.

Examples:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md#memes

**Comment by thiagomallet** [comment]
You're welcome. 

The image is the Iguaçu Falls, one of the most splendid waterfalls in the world, situated in the southern Brazil-Argentina border. So the puns Cascade/Cascading Styles/Sensational/SASSational make sense.

I updated the Alt Text for the meme in the Google Spreadsheet.

![iguacu-falls](https://user-images.githubusercontent.com/19553943/28140811-4241b3e8-6730-11e7-82d9-4dd2f08d4903.jpg)

**Comment by TheJaredWilcurt** [comment]
@thiagomallet 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
