### ISSUE TITLE
Why does it close itself each time I launch the compilation of a project

### ISSUE THREAD

**Issue by Yistine** [scout-app/scout-app#348]
Each time I click on the "Play" button of my project, it compiles and then the app is closed.

I have to re-launch the Scout each time I save my SASS file. So annoying...

Why does this happen while it worked perfectly before (automatic compilation)?

**Comment by TheJaredWilcurt** [comment]
@Yistine looks like you figured it out and closed the issue. If there's any instructions you can leave here for how you solved it, in case someone else has the problem too, that would be helpful.
