### ISSUE TITLE
grid-template-columns: [ name ] throws a syntax error

### ISSUE THREAD

**Issue by benjamenhogben** [scout-app/scout-app#350]
Hi all,

Just been trying to figure out an error Scout was throwing out when saving:

grid-template-columns: [start] 23% 23% 23% 23% [end];

It seems like it might be an error with scout?

Desperate to get this fixed! Thanks all.

Related: https://github.com/sass/sass/issues/1963

**Comment by TheJaredWilcurt** [comment]
@benjamenhogben 
The last release of Scout-App was in December 2016 and came with LibSass v3.3.6. The changes you want are in 3.5. I've updated the codebase to be using the new version of LibSass 3.5.0-beta2. It will be in the next release of Scout-App.

**Comment by benjamenhogben** [comment]
@TheJaredWilcurt Awesome. Any idea of eta?

**Comment by TheJaredWilcurt** [comment]
As soon as https://github.com/scout-app/scout-app/issues/333 is fixed.

**Comment by TheJaredWilcurt** [comment]
@benjamenhogben 

Closing issue. New release of Scout-App comes with v4.11.0 of LibSass bindings.

* **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
