### ISSUE TITLE
Translated Scout-App, Norwegian

### ISSUE THREAD

**Issue by ludicrumedia** [scout-app/scout-app#351]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

Complete translation into Norwegian by Marius Akerbæk at Ludicrumedia AS :)

**Comment by TheJaredWilcurt** [comment]
Awesome! Thanks so much for that.

What culturally relevant image should we use for native Norwegian speakers.

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md#memes

**Comment by ludicrumedia** [comment]
Appologies, I should have included that as well. I attach an illustration of fellow Norwegian Håkon Wium-Lie, regarded as the inventor of CSS on top of the Norwegian flag 
![no](https://user-images.githubusercontent.com/26259401/30109175-ac1a70ba-9305-11e7-93f1-282d9807a7cb.jpg)
:)

**Comment by TheJaredWilcurt** [comment]
@ludicrumedia 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
