### ISSUE TITLE
Translated Scout-App, PT-BR

### ISSUE THREAD

**Issue by claudemircasa** [scout-app/scout-app#352]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

I wrote the translation for pt-BR

**Comment by TheJaredWilcurt** [comment]
@lyonmarks 

Thanks for the translation, but there is a slight problem. You are the 3rd person to do a `pt-br` translation.

I've renamed your translations to `pt-br-temp` and colored them red. Can you compare yours to the existing translations and use whichever is better, so there is only one `pt-br` column.

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@claudemircasa 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
