### ISSUE TITLE
Translated Scout-App (Japanese)

### ISSUE THREAD

**Issue by tonextone** [scout-app/scout-app#357]
I added Japanese translation:

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit#gid=1510538720&range=AX:AX

**Comment by TheJaredWilcurt** [comment]
@tonextone 

Thanks for translating Scout-App. We need a culturally relevant image to show in the app. Here are some examples:

* https://github.com/scout-app/scout-app/tree/master/scout-files/cultures#memes

What image would make sense for Japan?

**Comment by tonextone** [comment]
よろしくお願いします。
![sass](https://user-images.githubusercontent.com/236499/33058726-5ce9b072-ced4-11e7-98a5-f44af2819f1b.png)

**Comment by TheJaredWilcurt** [comment]
<p align="center"><img alt="John Cusack wink" src="https://user-images.githubusercontent.com/4629794/33075733-787aa31e-ce98-11e7-97aa-0c5918fa3a77.gif"></p>

**Comment by TheJaredWilcurt** [comment]
@tonextone 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
