### ISSUE TITLE
Translated Scout-App, PT-BR

### ISSUE THREAD

**Issue by victorlucss** [scout-app/scout-app#358]
Translation to brazilian portuguese

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@victoorlucas 

Thanks for taking the time, but there was already a PT-BR translation. I've renamed yours to `pt-br2` and moved it to be next to the existing one. I removed deleted your translations that matched the existing ones.

If you see any improvements that can be made in the existing PT-BR translation you can make them. When you're done delete the `pt-br2` and `pt-br2 notes` columns.

**Comment by victoorlucas** [comment]
There's okay. I'm grateful to help.

**Comment by TheJaredWilcurt** [comment]
@victorlucss 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
