### ISSUE TITLE
Translated Scout-App (Albanian)

### ISSUE THREAD

**Issue by dajanvulaj** [scout-app/scout-app#362]
New translation to Albanian (Shqip) language can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
Thanks so much for translating the app. What culturally relevant image should be shown with the language?

**Examples:**

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md#memes

**Comment by TheJaredWilcurt** [comment]
@dajanvulaj 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
