### ISSUE TITLE
Doesn't auto-compile, only when start/stopped

### ISSUE THREAD

**Issue by warjat** [scout-app/scout-app#369]
First install of the app, it detects the writes to the scss file, but the "error" sound plays, and no message is displayed in the app (despite the settings being set to show desktop messages as well as in the app).
When I stop the service and start it again, everything compiles fine.
Obviously, having to press start/stop every time I write to the scss file defeats the purpose of such an app.

OS: 
Scout-App Version: 
Information from Dev Tools: 

(Attach screenshot below)

**Comment by TheJaredWilcurt** [comment]
@warjat 

Closing this as duplicate, see:

* https://github.com/scout-app/scout-app/issues/333#issuecomment-346405112

Follow instructions mentioned there to see if issue is resolved and report back on that issue.
