### ISSUE TITLE
--debug-info for firesass

### ISSUE THREAD

**Issue by LaurenceG** [scout-app/scout-app#37]
In order to use firesass(firefox/firebug plugin https://addons.mozilla.org/en-US/firefox/addon/firesass-for-firebug) I edited process_interaction.js to add on line 36:
if(data.project.environment==='development'){
  processArgs.push("--debug-info");
}

This is working for me with scout-app 0.6.0

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 supports "Development" environment mode that will output a Sass map. This should be equivalent to what you're requesting, since FireSass for Firebug no longer exists.

Closing this ticket as resolved.

* [Scout-App 2](http://scout-app.io) (2016)
