### ISSUE TITLE
Translated Scout-app (Indonesian:id)

### ISSUE THREAD

**Issue by dhanyn10** [scout-app/scout-app#371]
new translation Scout-app to Indonesian
let me know if there's any mistake for the document
https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit#gid=1510538720

**Comment by dhanyn10** [comment]
translating is in process

**Comment by TheJaredWilcurt** [comment]
I've moved it to be alphabetical. It is now in Column **Z**. I've also Google translated all of the empty spots. These should be verified and turned from red to black and have the "google translate" note removed.

**Comment by dhanyn10** [comment]
I need some time to adjust the results to be easy to understand. thanks for helping

**Comment by dhanyn10** [comment]
translation is done

**Comment by TheJaredWilcurt** [comment]
@dhanyn10 

Thanks, what culturally relevant image do you want displayed for Indonesian.

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md#memes

**Comment by dhanyn10** [comment]
now i'm creating for memes

**Comment by dhanyn10** [comment]
image for Indonesian
![bali](https://user-images.githubusercontent.com/11478316/35191628-70612938-feb2-11e7-8f1d-f069fd9f5905.png)

**Comment by TheJaredWilcurt** [comment]
@dhanyn10 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
