### ISSUE TITLE
Infinite Changes Detected with pCloud

### ISSUE THREAD

**Issue by WaxMikhail** [scout-app/scout-app#372]
Howdy,

Our company just switched to pCloud for our shared server. We use (and love) Scout for SCSS. When pressing "play" and watching a folder within our shared pCloud account, Scout gives the "changes detected" alert about every half second, when no changes are being made to the file. I am guessing this is an issue with pCloud, somehow or another, changing the file or updating it or syncing it somehow. This consumes a harmful amount of CPU power and also is obviously not ideal or very useful.

I'm not sure what to do, but don't experience this issue with Dropbox (which also syncs stuff). 

Thanks for the help!

**Comment by TheJaredWilcurt** [comment]
@WaxMikhail 

I'm not familiar with pCloud or what it could be doing to cause that. Internally Scout-App uses "Chokidar" to monitor for file changes.

You can try out the latest code in the `master` branch to see if it still occurs. There is a new chokidar specific setting inside of Scout-App to adjust atomic save delays. You could try setting it to different values (0ms-700ms) to see if it has any effect.

To run the latest code you need to do the following:

1. Install [Node.js](https://nodejs.org).
2. Download the [master branch](https://github.com/scout-app/scout-app/archive/master.zip).
3. Open that `master.zip` and extract the `scout-app-master` folder.
4. In your command prompt/terminal `cd` into the `scout-app-master` folder.
5. Run the command `npm install`. This may take a few minutes.
6. Run the command `npm start`. This should launch the latest version of Scout-App.

**Comment by WaxMikhail** [comment]
Howdy Jared, 

While I think that's a great solution the issue is really with pCloud instead of Scout itself (we're not going with pCloud after all because of this issue). I am gonna go ahead and mark this as closed.
