### ISSUE TITLE
Translated Scout-App Swedish (sv)

### ISSUE THREAD

**Issue by jimmiecarlsson** [scout-app/scout-app#374]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

<labels>Translation</labels>

**Comment by TheJaredWilcurt** [comment]
@ibookjim 
Thanks so much for that, it will be in the next release of Scout-App.

What culturally relevant image do you want for Sweden

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md#memes

**Comment by ibookjim** [comment]
No problem. I have to think about which picture would fit.

**Comment by TheJaredWilcurt** [comment]
@jimmiecarlsson 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
