### ISSUE TITLE
German Corrections

### ISSUE THREAD

**Issue by mhorstmann** [scout-app/scout-app#375]
Edited translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

de (German)

**Comment by TheJaredWilcurt** [comment]
@mhorstmann 
Thanks for the corrections. This has been pulled into the master branch and will be in the next release.

**Comment by TheJaredWilcurt** [comment]
@mhorstmann 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
