### ISSUE TITLE
Translated Scout-App in Romanian

### ISSUE THREAD

**Issue by TrescoNet** [scout-app/scout-app#376]
New translation in Romanian can be found at

https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit#gid=1510538720

**Comment by TheJaredWilcurt** [comment]
@TrescoNet 
Thanks for the corrections. I've made a few changes back

* American [Redneck](https://i.imgur.com/u1B9H4H.jpg) - so as not to be confused with [English](http://i.imgur.com/hWp9cuC.jpg)
* Name/link of previous Translator. We can support multiple names

What culturally relevant image would you like to use for Romania? Examples:

* https://github.com/scout-app/scout-app/blob/master/scout-files/cultures/README.md#memes

**Comment by TheJaredWilcurt** [comment]
@TrescoNet 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
