### ISSUE TITLE
Translated Scout-App, PT-BR

### ISSUE THREAD

**Issue by paulo-santana** [scout-app/scout-app#377]
Updated PT-BR translation with some minor changes in old strings, replaced some pt-br by pt-br2 strings and corrected and black-labeled google translated entries since the last full translated version.

Now pt-br is full translated again. Deleted pt-br2 and notes columns.

New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@paulo-santana 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
