### ISSUE TITLE
Russian Corrections

### ISSUE THREAD

**Issue by Alex-Sidorchenko** [scout-app/scout-app#383]
Edited translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit#gid=1510538720

ru (Russian)

**Comment by TheJaredWilcurt** [comment]
@Alex-Sidorchenko 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
