### ISSUE TITLE
Changes to partials dont trigger compile

### ISSUE THREAD

**Issue by ryanfurtner** [scout-app/scout-app#384]
```
@import "../bourbon/bourbon";
@import "../theme/theme_variables";
@import "../assets/bootstrap4";
@import "../understrap/understrap";
@import "../assets/owl-carousel2";
@import url('https://fonts.googleapis.com/css?family=Montserrat');

@import "../theme/theme";
```

This is what my main file looks like. If i make changes to this file it triggers a compile, but not if I make changes to any of the partials above. All the partials have a leading underscore. Is there something im doing wrong?

Using V2.12.12 on win 10

Thanks

**Comment by TheJaredWilcurt** [comment]
@ryanfurtner 

Are the partials in the input folder? Only the input folder is monitored for changes. If a `.sass` or `.scss` file in the input folder emits a file system change, Chokidar detects it and triggers Node-Sass to re-run processing all `.sass` and `.scss` files that do not start with an `_` in the input folder, or the sub-directories of the input folder.

**Comment by ryanfurtner** [comment]
Hey Jared,

Yeah all the files (that I make changes to)  are in the input folder, but they're each in subdirectories. I might be able to try moving them all out into the 1 input folder root if I get a chance this morning.

**Comment by TheJaredWilcurt** [comment]
if you can zip up an example that has this issue I can fix it

**Comment by ryanfurtner** [comment]
I ended up moving all the files i regularly edit into the root of the input folder. That plus making sure all partials were correctly prefixed with an underscore makes everything work perfectly.

Heres the folder structure that gave me the issues anyway, incase you wanted to take a look.
[scoutapp.zip](https://github.com/scout-app/scout-app/files/1839375/scoutapp.zip)

Thanks 👍
