### ISSUE TITLE
Translated Scout-App [PT-BR] 100% Complete

### ISSUE THREAD

**Issue by Dennissiq** [scout-app/scout-app#386]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@Dennissiq 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
