### ISSUE TITLE
Internal Error: File to read not found or unreadable

### ISSUE THREAD

**Issue by andrealansp** [scout-app/scout-app#387]
OS: Windows 10
Scout-App Version: 2.12.12
Information from Dev Tools:
message: "File to read not found or unreadable: C:/wamp/www/espacolondrina/res/assets/estilos/scss/estilo.scss"

(Attach screenshot below)
![image](https://user-images.githubusercontent.com/14852457/39832297-36435452-539d-11e8-9447-b2921b195c1f.png)

**Comment by TheJaredWilcurt** [comment]
@andrealansp 

There is a new release of **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**. Try adjusting the atomic Saves setting in the new version. Closing this issue for now. If the issue still exists in latest version then this can be reopened.
