### ISSUE TITLE
Percent sign not recognized as expression

### ISSUE THREAD

**Issue by Syphontwo** [scout-app/scout-app#389]
OS:  Windows 7
Scout-App Version:  v1.6.1.
Information from Dev Tools:  
```
Error {status: 1, file: "C:/Users/[USERNAME]/Documents/GitHub/[PROJECTPATH]/scss/styles.scss", line: 53, column: 45, message: "Invalid CSS after "...0}% #{50 - $i}%": expected expression (e.g. 1px, bold), was ";""…}
column: 45
file: "C:/Users/[USERNAME]/Documents/GitHub/[PROJECTPATH]/scss/styles.scss"
formatted: "Error: Invalid CSS after "...0}% #{50 - $i}%": expected expression (e.g. 1px, bold), was ";"↵        on line 53 of ../../Users/[USERNAME]/Documents/GitHub/[PROJECTPATH]/scss/styles.scss↵>> 		transform-origin: #{$i + 50}% #{50 - $i}%;↵   ------------------------------------------^↵"
line: 53
message: "Invalid CSS after "...0}% #{50 - $i}%": expected expression (e.g. 1px, bold), was ";""
```

(Attach screenshot below)
![capture](https://user-images.githubusercontent.com/24842713/41375964-44fe7a9e-6f1d-11e8-8919-d2590caf317f.PNG)

Code causing error:
```
@for $i from 1 through 4 {
 &:nth-of-type(#{$i}) {
  animation-delay: -#{$i * 0.15}s;
  animation-duration: #{$i + 10}s;
  transform-origin: #{$i + 50}% #{50 - $i}%;
 }
}
```

The code will be accepted if I change from `%` to another unit type such as `px`.  This is what has led me to report it as bug.

**Comment by TheJaredWilcurt** [comment]
@Syphontwo 

I tried the code out in [SassMeister](https://www.sassmeister.com) and it does not work there either. I made a slight change and got it to work:

```scss
.thing {
  @for $i from 1 through 4 {
    &:nth-of-type(#{$i}) {
      animation-delay: -#{$i * 0.15}s;
      animation-duration: #{$i + 10}s;
      transform-origin: #{$i + 50%} #{50% - $i};
    }
  }
}
```
By attaching the percent to the number that math is occurring on the rendered version will be produced using that unit.

* https://www.sassmeister.com/gist/39edfa8162628e9185ddeb8ec0a01bfc

**Comment by TheJaredWilcurt** [comment]
Tested the code snippet I showed in 2.12.12 and `master`. Both worked. Closing issue.
