### ISSUE TITLE
Box Drive error when creating project: "The folder "___" can't be used. Please choose another folder"

### ISSUE THREAD

**Issue by WaxMikhail** [scout-app/scout-app#391]
Howdy folks, 

Our company uses Box cloud storage to sync all our site files, and we compile them locally right in the Box Drive software. We've been working this way about a 6 months now. 

Recently, (as in, today) when creating a new project, scout pops up the little folder navigator. When I click on the Box folder (which is the Box Drives locally synced files folder) it displays the message "The folder Box can't be used. Please choose another folder" and doesn't let me drill down into the folders. 

Weirdly, I can copy and paste file paths that are in Box Drive and put them into the input and output fields, and it compiles just fine. But selecting from the "add project" menu doesn't let me set anything inside box. 

I think this is not a Scout issue, rather a Box one, but just in case I thought I'd get it up on here if anyone else had the same issue or knew any solutions. Thanks!

**Comment by TheJaredWilcurt** [comment]
@WaxMikhail 

Browsing for files and folders is handled natively by the OS. Scout-App just launches the dialog and waits for it to return a path. If you are having issues with this, it is on the OS level. It may be that Box is using some type of shortcut, symbolic link, or junction point, which is not a valid path for the dialog box. The easiest work around is what you have already done, type the path in directly to the app, that is why that option is available.
