### ISSUE TITLE
Translated Scout-App into Ukrainian (uk)

### ISSUE THREAD

**Issue by faradzhev** [scout-app/scout-app#393]
New translation can be found at

* https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing

**Comment by TheJaredWilcurt** [comment]
@faradzhev 

Closing issue. This has been released in **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.
