### ISSUE TITLE
Add ability to change output filename

### ISSUE THREAD

**Issue by kevindeleon** [scout-app/scout-app#396]
I feel like this might be a helpful feature. For example, I work in some projects where the output file might be "main.css" or "styles.css" instead of "style.css"

It would be helpful to be able to specify the name in the output field.

**Comment by TheJaredWilcurt** [comment]
**How Scout-App works:**

1. Scan all files/folders/subfolders in the input folder
1. Create matching folder/subfolder structure in the output folder
1. Produce CSS files with matching filenames in the same folders/subfolders as input in the output for all `.sass` or `.scss` files that do not start with an `_`.

We do not handle just a single input file, but all files in the input folder. To allow renaming of any file arbitrarily would be overly complex. I don't think this feature justifies the added complexity to the app's interface and usability.

Following the [cardinal rules](https://github.com/scout-app/scout-app/blob/master/documentation/ux.md#the-cardinal-rules-of-scout-apps-development) (specifically 5 and 6) I'm going to close this issue.
