### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [scout-app/scout-app#400]
i've downloaded Version '2.12.12' but when selecting it in the Finder and using 'Get Info' it claims to be Version '41.0.2272.76'

the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are wrong

**Comment by TheJaredWilcurt** [comment]
@core-code 

There is a new release, can you check to see if the issue still occurs.

* **[Scout-App v2.18.16](https://github.com/scout-app/scout-app/releases/tag/v2.18.16)**.

**Comment by core-code** [comment]
thanks, i can confirm its solved.
