### ISSUE TITLE
file to import not found or unreadable compass/css3

### ISSUE THREAD

**Issue by msqueeg** [scout-app/scout-app#408]
sorry, I'm not sure if this is a bug or just something misconfigured on my end. I recently migrated an existing SCSS project to a new computer and I'm getting this error when I try to run Scout-App on the project. I've been using Scout-App with this same project for nearly a year on another Windows 10 machine and never ran into this. Is Compass/Css3 not included in Scout? Or is there a file path issue?

**OS:** Windows 10
**Scout-App Version:** 2.18.16
**Information from Dev Tools:**

```
column: 1
file: "C:/etc/20-29-dev/22.cv3/cv3-hh-2018/store/files_docs/developer/HHW HTML/assets/sass/main.scss"
formatted: "Error: File to import not found or unreadable: compass/css3.
        on line 6 of ../../../../../etc/20-29-dev/22.cv3/cv3-hh-2018/store/files_docs/developer/HHW HTML/assets/sass/main.scss
>> @import "compass/css3";
   ^
"line: 6
message: "File to import not found or unreadable: compass/css3."
```

**Comment by TheJaredWilcurt** [comment]
@msqueeg 

All built in mixins are found here:
* https://scout-app.io/#mixins

Including `@import "compass"`, which uses [compass-mixins](https://github.com/Igosuki/compass-mixins).

You can either import that library into your own project to point directly at the `_css3.scss` file, or if you want it to be globally available to all projects in Scout-App, then you can add a file pointing to it into Scout-App's mixins folder.

* `Scout-App\scout-files\mixins\_css3.sass`

and in that file put:

```sass
@import '../../node_modules/compass-mixins/lib/compass/_css3.scss'
```

Then any projects ran in your copy of Scout-App that have an `@import "css3";` will work.

**Comment by rainb3rry** [comment]
You're rocks <3
