### ISSUE TITLE
Inconsistent/Erroneous rgba() opacity-decimal parsing (part 2)

### ISSUE THREAD

**Issue by isNaN** [scout-app/scout-app#41]
An opacity value like this: rgba( 0, 0, 0, 0.66 ) is often returned as rgba( 0, 0, 0, 0 ). This behavior is very inconsistent.

Usually the "last saved file" in a project parses correctly, but having 8-9 imports with ~350 lines of SCSS in each, at least one of those files always fail.

---

The issue persists in 0.6.0 RC1.

If I put all my code into one scss file, it never fails. But when using several imports it gets to a point where Scout more or less always returns a failed parsed file with no decimals.

---

This issue was reported here: https://github.com/mhs/scout-app/issues/22
But it got closed before I had a chance to comment back after you asked us to check if the issue persisted.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
