### ISSUE TITLE
File to import not found or unreadable: 

### ISSUE THREAD

**Issue by Grahamhoare** [scout-app/scout-app#410]
I have a system/site that i have been using sass with for 5 years on latest update I get files not found/ failed to import, in my file I have these:
@import "compass/css3/opacity";
@import "compass/css3/border-radius";
@import "compass/css3/transition"; 	
@import "compass/css3/images";
@import "compass/css3/box-shadow";
@import "compass/css3/animation";

Scout tells me on initial install: File to import not found or unreadable: compass/css3/opacity.
Scout is supposed to ship with this, indeed I can see it in the App's folder 'node_modules' so why doesn't it import them automatically?
I also put the compass files directly into my project folder in correct place and it still doesn't work. 
If this stuff is shipped with your App surely it should work out of the box, and if my paths need to change to my compass where is the info? Why has it changed? on looking everything seems to be there?

**Comment by TheJaredWilcurt** [comment]
You can follow these instructions:

*  https://github.com/scout-app/scout-app/issues/408

Though you should also look into if you need these anymore. Unless you are supporting very old browsers you likely can remove your reliance on Compass's CSS3 mixins as all browsers support these properties now (and have for 7+ years). Compass is also deprecated.

**Comment by Grahamhoare** [comment]
Happy to get rid of compass, but what about browser prefixes and the different way different browsers implement styles? Is there a simpler library of mixins I can get into my project you'd recommend?
