### ISSUE TITLE
Do not compile dependable files :feature-request

### ISSUE THREAD

**Issue by adinan-cenci** [scout-app/scout-app#411]
I like to organize my .scss code by separating different concerns in different files and then have all of them compiled in a single .css file.

It would be nice to have a feature that, do not compile those .scss into .css but still watch for changes and triggers the compilation of the main file(s).

It could work in the form of a sub-folder form field I guess.

**Comment by TheJaredWilcurt** [comment]
@adinan-cenci What you are doing is called "partials" and it is part of the Sass spec. You just need to start your partial files with an underscore and Scout-App will skip creating a mirrored `.css` version.
