### ISSUE TITLE
Support for @import compass styles

### ISSUE THREAD

**Issue by jankout** [scout-app/scout-app#413]
Hello, 

first of all, I want to thank you for your great work. I would like to ask you to implement support for import of compass styles. 

E.g. `@import "compass/css3/text-shadow"`

That would be great. Now your app cannot do it. Unfortunately.

**Comment by TheJaredWilcurt** [comment]
Compass was deprecated many years ago. It is recommended to refactor your codebase to no longer use it.

* * *

Scout-App has a folder where it checks for imports if it can't find the reference in your project, it is located at:

   * `Scout-App\scout-files\mixins`

Scout-App ships with a copy of the `compass-mixins` library built in.

   * `Scout-App\node_modules\compass-mixins\lib\compass\css3\_text-shadow.scss`

If you wanted, you could create a file called `_compass-text-shadow.sass` in the mixins folder

   * `Scout-App\scout-files\mixins\_compass-text-shadow.sass`

With this content:

```sass
@import '../../node_modules/compass-mixins/lib/compass/css3/_text-shadow.scss'`
```

Then in any of your projects you could do:

```sass
@import 'compass-text-shadow'
```

* * *

Alternatively you can also edit the `Scout-App\scout-files\mixins\mixins.config` file and add the location of another folder for Scout-App to check for imports if it can't find the reference in your project.

```
scout-files/mixins
C:/Users/jankout/documents/my-custom-mixins
C:/folder/folder-with-sass-mixins
```

**Comment by jankout** [comment]
Thank you for your help
