### ISSUE TITLE
Argument Error #3214

### ISSUE THREAD

**Issue by cheeseheadnate** [scout-app/scout-app#415]
Scout installs properly, project setup works fine, but when you run the project it errors out immediately and gives you Argument: Errror #3214   inside a "Adobe Air Introspector". I have Adobe Air, Java, Scout etc all properly installed on my Windows 10 machine. (Screen capture attached)
![air_introspector](https://user-images.githubusercontent.com/965252/69916378-fb3f6900-141f-11ea-954a-01eb9d28ff0d.PNG)

**Comment by TheJaredWilcurt** [comment]
@cheeseheadnate 

Scout-App 0.7.1 was released in 2012. It relied on the user having specific versions of Java and Adobe Air installed. It is still available for download **but is no longer maintained**. It uses a very old (and slow), ruby-based version of Sass. It comes with Compass, but that too is **no longer maintained**.

* http://scout-app.io/classic
* https://github.com/scout-app/scout-app/releases/tag/v0.7.1_2016-03-10

* * 

Scout-App 2+ was last released in 2019. It does not rely on Java or Adobe Air. It uses a modern version of Node-Sass under the hood (much faster).

* https://Scout-App.io
* https://github.com/scout-app/scout-app/releases/tag/v2.18.16
