### ISSUE TITLE
Native Coda 2 plugin

### ISSUE THREAD

**Issue by aaronbushnell** [scout-app/scout-app#42]
Would love to have a Coda 2 plugin that compiled Sass+Compass on save events. It would be great to open up an .scss file, save it, and it gets compiled without activating a "project" in a separate app.

**Comment by TheJaredWilcurt** [comment]
Scout-App is a cross-platform desktop application. It works in conjunction with **any** text editor, but you need to have Scout-App running. When a project is running it will monitor all changes in the input folder.

* [Scout-App 2](http://scout-app.io) (2016)

Closing this issue as 'will not fix'.
