### ISSUE TITLE
App Doesn't Open After Exiting... Without Task Manager or Restart

### ISSUE THREAD

**Issue by peterslc** [scout-app/scout-app#423]
I can open the app only once—if I close it, I can't reopen it without opening task manager and ending all Scout processes or restarting my computer.

I've experienced this issue on two different machines, which is why I'm finally reporting it. Both computers were Dells running Windows 10. More details available upon request... not sure what is needed.

**Comment by TheJaredWilcurt** [comment]
Did you check if it was in the system tray by the clock. There is a setting to turn that on/off?

**Comment by peterslc** [comment]
Wow... I never knew. Thank you, sorry to waste your time.
