### ISSUE TITLE
Impossible to use ; I can't create a project.

### ISSUE THREAD

**Issue by madvik** [scout-app/scout-app#425]
I want to add a project but the windows don't want to close on when a directory is choose.

![image](https://user-images.githubusercontent.com/3822529/82710266-c26fa680-9c82-11ea-92ac-89c35f6d667e.png)

**Comment by TheJaredWilcurt** [comment]
Works fine. You are not giving me any information about the problem.

What OS. What version of Scout-App. Can you consistently reproduce the issue. Can you supply the minimum amount of files/code to reproduce the issue.

![works](https://user-images.githubusercontent.com/4629794/83430611-ef028b80-a403-11ea-914f-324ecc982dca.gif)

**Comment by madvik** [comment]
Windows 10 32 bits
The last version of scout : 2.18.16
I re-downloaded the program.
I tried it again and it actually worked.
I just don't understand it.
