### ISSUE TITLE
Is this supported / updated anymore?

### ISSUE THREAD

**Issue by morrow95** [scout-app/scout-app#444]
I am looking for alternatives to the Koala app [(link)](http://koala-app.com/) since support has dropped and will no longer be updated.  

I've looked at Scout in the past, but there were quite a few reasons why Koala was superior to me at the time (also compiles/minimizes js, has a settings file which can be directly edited, multiple input/output mappings per project, etc).  As Koala is no longer being updated I am starting to come across compilation errors with newer coding styles/methods so here I am.

For Scout I see the last release was over two years ago and there are quite a lot of open issues.  Is this even maintained/updated anymore?  Last thing I want to do is switch over to something else and get in the exact same situation as before.

**Comment by sandra-eberl** [comment]
I also would like to know :-)

**Comment by codingapple1** [comment]
use VScode extensions like 'live sass compiler'
