### ISSUE TITLE
Classic Scout app opens with a blank white screen

### ISSUE THREAD

**Issue by joevayalil** [scout-app/scout-app#459]
I tried to install the classic scout app for one of  our legacy site on my new machine (as the scout app 2 wont work with the code set up), and getting a blank screen once it opens. Appreciate any help on how to resolve this. Screenshot below:

![image](https://user-images.githubusercontent.com/7397588/224723927-ca23120b-ff88-4fa4-af58-e68c700e0b40.png)

**Comment by TheJaredWilcurt** [comment]
Make sure you have the correct version of Java (6 or 7) and Adobe Air installed, that's what Classic Scout used. Not sure how compatible it will be with newer OS's.

**Comment by joevayalil** [comment]
I've Java7 installed and it is in the location as expected by the Scout app: C:\\Program Files (x86)\\Java\\jre7\\bin\\java.exe.
OS is Windows 10;
Adobe Air is also installed, do you need any specific version of Adobe Air? 
Also the Scout application path is C:\Program Files (x86)\Scout - not sure if any issues with the application being in that path. 
We have multiple sites set up with the old way including sprites to compile into images folder etc., so the new app won't work for us.
Appreciate more help considering the above facts @TheJaredWilcurt
