### ISSUE TITLE
PB with images_dir in Config.rb

### ISSUE THREAD

**Issue by awaweb** [scout-app/scout-app#46]
Hello,
I'm using SCOUT 0.6.1 and I'm looking at the new "config file" option in SCOUT.
The generated_images_dir variable seems to work fine
but the images_dir variable has a problem...
SCOUT put a / before my variable so "../images/" becomes "/../images/".
Any solution to solve this issue ?
Thank you and bravo for Scout

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 no longer relies on Ruby. Therefore it cannot run Compass (besides mixins) or Ruby config files.

Closing this issue as "will not fix".

* [Scout-App.io](http://scout-app.io)
