### ISSUE TITLE
Error #3214 on project run, Win 7

### ISSUE THREAD

**Issue by liberalGeorge** [scout-app/scout-app#47]
I've installed Scout on Win 7 Enterprise, SP1 (further spec below). I can set up a project, but when I hit the play button a new window titled ADOBE AIR HTML/JS Application Introspector appears with the error:

[app:/views/productions.html][<timestamp>] ArgumentError: Error #3214

This is expandable with various information. The stack trace starts at startWatchingProject, line 11, app:/javascripts/app/process_interaction.js I can provide further details if needed.

Machine spec:
Intel Core2Quad 2.67GHz
8GB RAM
64 bit OS

Thanks

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Scout-App 2 no longer relies on Java or Adobe Air.

* [Scout-App 2](http://scout-app.io) (2016)


* * *

@descoderu 

Cкаут-Апп 2 теперь поддерживает русский язык (Scout-App 2 now supports Russian)
