### ISSUE TITLE
[Win] Different folder picker dialog box

### ISSUE THREAD

**Issue by bspingarn** [scout-app/scout-app#48]
Please consider switching to a different folder navigation dialog box.

The dialog box to choose project folders forces the user to navigate by clicking into sub directories. If the project folder is on a network drive or in a lot of nested folders, it can become a bit tedious to navigate to it. It would be great if we could also just type in the path to the folder to speed up navigation.

**Comment by TheJaredWilcurt** [comment]
Closing this issue. Download the latest version of Scout-App. It allows for native OS directory browsing, but also for directly typing in the field.

* [Scout-App.io](http://Scout-App.io)
