### ISSUE TITLE
wrongful identical css

### ISSUE THREAD

**Issue by mlarcher** [scout-app/scout-app#49]
I couldn't figure out a pattern yet, but sometimes I get 
>>> Change detected to: style.scss
identical style.css 
instead of
>>> Change detected to: style.scss
overwrite style.css 
when altering style.scss 

In such case, the css may or may not actually be overwritten.

When this happens, the behaviour gets quite inconsistent. It seems it takes major changes for scout to notice and act on those changes.
It is possible that this happens after a scss parsing error, but restarting scout app doesn't seem to get it back on tracks.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
