### ISSUE TITLE
Running app for development on Windows is painful

### ISSUE THREAD

**Issue by zdennis** [scout-app/scout-app#5]
Running Scout from source on windows is pretty painful. You cannot run it directly from the rake tasks unless you manually install several components like jruby, bundler, and then comment out other rake tasks when trying to run "rake" itself.

**Comment by TheJaredWilcurt** [comment]
Adobe Air, Java, and Ruby are all no longer required for Scout-App.

Scout-App 2 was developed primarily on Windows 7. It runs smoothly and happily. The pain is gone, and I do believe this is the last issue I have to clean up.

Closed.
