### ISSUE TITLE
Undefined method `deep_copy'

### ISSUE THREAD

**Issue by fnagel** [scout-app/scout-app#50]
On Win7 (latest alpha, ScoutAppInstaller-Sass-3.2.0.alpha.247.exe) Im running into following problem:

````
NoMethodError on line 94 of C: undefined method `deep_copy' for # [...]
````

Scout stops SASS when this error occurs.  Deinstall and reinstall Scout helps but only for one start.
This patch of SASS fixes the problem, so please update!

https://github.com/nex3/sass/issues/422

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
