### ISSUE TITLE
Work with blueprint

### ISSUE THREAD

**Issue by travisbotello** [scout-app/scout-app#54]
Hey guys,

first of all...scout is trully awesome. However I'd like to know if it is possible to start a SASS/COMPASS project with blueprint (http://compass-style.org/reference/blueprint/) via scout?!

Thanks in advance

**Comment by TheJaredWilcurt** [comment]
Blueprint is a fairly dated CSS framework. It has not been updated is [2011](https://github.com/joshuaclayton/blueprint-css/commits/master). I would recommend looking into a more modern framework to handle page layout/grid systems. Bootstrap, Foundation, and Bulma are all popular alternatives.

* [Scout-App.io](http://Scout-App.io)

Closing issue as "will not fix".
