### ISSUE TITLE
Scout looking for nonexistant Java Libraries

### ISSUE THREAD

**Issue by ansorensen** [scout-app/scout-app#58]
When I try to run Scout (it is currently on the E: drive, if that matters), it gives me the following error:

Error: could not open `C:\Program Files\Java\jre7\lib\i386\jvm.cfg'

 I have the latest version of Java (as of 9/3/12, double checked there is no new version), but the /jre7/lib folder doesn't have anything in it but an empty 'ext' folder.  Is there anyway I can download the i386 lib?

Thanks,
Alec

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this issue. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
