### ISSUE TITLE
Log syntax highlighting Windows 7x64

### ISSUE THREAD

**Issue by Adevade** [scout-app/scout-app#59]
Don't know if it's a bug, but on the download page of Scout there is a screenshot of the log with syntax highlighting and linebreaks. 

On my Windows machine it looks like this: 
![Scout Log](http://i.imgur.com/OAVbx.png)

Just a heads up if you didn't know :-)

**Comment by TheJaredWilcurt** [comment]
And it was! This no longer occurs in Scout-App 2. Closing this issue.

* [Scout-App 2](http://scout-app.io) (2016)
