### ISSUE TITLE
argumenterror #3214 on Win XP German

### ISSUE THREAD

**Issue by upstroke** [scout-app/scout-app#61]
Scout app throwing an argumenterror #3214 on Win XP German. 
Please note that the problem will be resolved setting the right location of the java.exe at file process_interaction.js on line 106 inside function javaDir().

The path starts with 'Program Files' which is not the standard location on a german Win XP.
Changeing Program files to Programme will resolve this issue but it's only a workaround.

The best to prevent this is to ask for the location where Scout will be installed to and take this path to build the correct pathes inside the function javaDir.

So with a german Windows XP the path variable should look like this:
path = air.File.applicationDirectory.resolvePath("C:\\Programme\\Java\\jre7\\bin\\java.exe");

Greets

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this issue. Scout-App 2 no longer relies on Adobe Air or Java. Download the latest version of Scout-App.

* [Scout-App.io](http://Scout-App.io)

* * *

@upstroke 

If you are interested in helping translate Scout-App 2 into German, [click here](http://scout-app.io/#cultures).


* * *

@guilhermemarconi

Se você gostaria de ajudar a [traduzir Scout-App](http://scout-app.io/#cultures) para Português:

1. Faça o login em sua [Conta do Google](https://accounts.google.com/login).
1. Vá para o arquivo de tradução em [planilhas do Google](https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing).
1. Há uma coluna `en` para a versão em Inglês, e uma coluna `CONTEXT` que explica o uso do texto.
1. Criar uma nova coluna para o seu idioma. (Ocultar colunas de idiomas que você não gosta.)
1. Traduza todas as frases do `en`. Adicionar outra coluna para todas as notas (`notes`) relacionadas com as suas traduções.
1. Adicione uma issue a GitHub para nos informar sobre uma atualização para o documento.
