### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by coopersita** [scout-app/scout-app#62]
Hi,

I may not be understanding the way the config options are supposed to work in compass, but in mine, I have tried changing the contents, and I don't see a difference when it gets compiled.

http_path = "/"
css_dir = "../css"
sass_dir = "./"
images_dir = "../images"
javascripts_dir = "../js"
environment = :production
relative_assets = true 
output_style = :compressed
line_comments = false
preferred_syntax = :scss

I've changed the environment, output_style, line_comments, but I see not difference in the output. Shouldn't my CSS file be formatted differently when changing the preferences, in terms of white spaces, and comments?

It's not a huge issue for me, but I though I'd bring it up.

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 no longer relies on Ruby, and thus these config files are no longer relevant.

I may consider implementing `defaults` controls if the settings become more complex in the future, but with just environment and output style, I think it's fine as it is currently.

Closing ticket.

* [Scout-App.io](http://scout-app.io)
