### ISSUE TITLE
Add right click actions on project tab

### ISSUE THREAD

**Issue by jeremywrowe** [scout-app/scout-app#65]
It would be nice to have some right click actions such as delete project on the project tab.  I find myself fumbling when trying to find the delete action :)

**Comment by TheJaredWilcurt** [comment]
Added this to the [Project Road Map](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance) for future versions of Scout-App.

* [Scout-App.io](http://scout-app.io)

**Comment by TheJaredWilcurt** [comment]
Feature has been implemented into the master branch. Will be in the next release.

Closing this issue. I'll notify you when the next version of Scout-App is released.

**Comment by TheJaredWilcurt** [comment]
@jeremywrowe 

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)

**Comment by jeremywrowe** [comment]
Thanks!
