### ISSUE TITLE
Allow people to configure their own Rubygems

### ISSUE THREAD

**Issue by zdennis** [scout-app/scout-app#66]
There's an increasing need for users of ScoutApp to be able to add rubygems they're interested in using to their ScoutApp project. Currently, all gems are bundled with ScoutApp and cannot be changed through the UI. 

In the past, I have been adding more gems to ScoutApp, and pushing new releases. This is not a good solution. The other alternative is for users to customize their local installation of ScoutApp, which is also not a good solution.

Within the current UI, I was thinking of adding a new "Gemfile" tab next to "Configure" and "Log" which would be the place where users could add their own Rubygems. Since most gems give clear instructions about what to add to a Gemfile it seems straightforward enough to have this be a big text area that would be the contents of an actual Gemfile. If users messed up the formatting the next time they would try to run Scout they should see the output from bundler about their Gemfile being malformed. At least, this could be the first step.

This may require a few things about Scout to change.

* Each project would need to track the contents of its Gemfile.

*  ScoutApp has its own Gemfile that it uses when running for a user in `src/` and this would likely no longer be able to use this as-is since each project's Gemfile could differ. This could become a template Gemfile that each project starts with

* ScoutApp would either need to maintain actual Gemfiles (on disk) for each project (so it could tell bundler which Gemfile to use when starting compass) OR it could start placing them in the user's project. 

* Every time the Gemfile changed ScoutApp would need to re-bundle. ScoutApp uses its own internal `vendor/gems` directory and it should likely continue to use this for all of a user's projects. So while the Gemfile will be different for each project, all gems should be installed to the same `vendor/gems`

Those are my thoughts so far.

**Comment by TheJaredWilcurt** [comment]
The latest version of Scout-App is Node-based and no longer relies on Ruby. Since Compass and other Gems require Ruby to run, Scout-App 2 cannot use them.

Closing this issue as "will not fix".

* [Scout-App 2](http://scout-app.io) (2016)
