### ISSUE TITLE
Scout error log

### ISSUE THREAD

**Issue by vinibelmonte** [scout-app/scout-app#68]
Scout está dando erro no LOG, como resolver isso?

**Comment by TheJaredWilcurt** [comment]
>Scout is giving error in the log, how to solve this?

Fechando esta questão. Baixe a última versão do Escuteiro-App. Se o problema persistir, crie um novo issue.

Closing this issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)

Se você gostaria de ajudar a [traduzir Scout-App](http://scout-app.io/#cultures) para Português:

1. Faça o login em sua [Conta do Google](https://accounts.google.com/login).
1. Vá para o arquivo de tradução em [planilhas do Google](https://docs.google.com/spreadsheets/d/16FtHGThz0-CBz_rf_9QO4zOV7oNmNk2BlwmtvKuzAhs/edit?usp=sharing).
1. Há uma coluna `en` para a versão em Inglês, e uma coluna `CONTEXT` que explica o uso do texto.
1. Criar uma nova coluna para o seu idioma. (Ocultar colunas de idiomas que você não gosta.)
1. Traduza todas as frases do `en`. Adicionar outra coluna para todas as notas (`notes`) relacionadas com as suas traduções.
1. Adicione uma issue a GitHub para nos informar sobre uma atualização para o documento.
