### ISSUE TITLE
Overwriting fonts_dir

### ISSUE THREAD

**Issue by angeliquejw** [scout-app/scout-app#70]
New to Scout, Compass & SCSS, so this is a query not necessarily a bug:

Default assignment of fonts directory for @include font-face appears to be "stylesheets/fonts;" my fonts are actually in "includes/fonts."

I created a config.rb file, pointed Scout to it and included the following:
```
fonts_dir = "includes/fonts"
```
Now, when I compile the code, I get the following error:
```
>>> Change detected at 12:42:05 to: style.scss
error style.scss (Line 105: different prefix: "C:\\" and "C:/pathto" for `font-files')
```

What am I doing wrong and how can I set up my fonts directory as needed? All my other directories have been declared using the Scout GUI.

**Comment by TheJaredWilcurt** [comment]
Issue presumed resolved. Closing this issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
