### ISSUE TITLE
Scout fails to launch

### ISSUE THREAD

**Issue by dandelyin** [scout-app/scout-app#71]
Hi,

Just downloaded Scout. I get 'Scout.exe has stopped working' when I try to open the program.

Details:

Problem signature:
  Problem Event Name:	BEX
  Application Name:	Scout.exe
  Application Version:	0.0.0.0
  Application Timestamp:	4f4da3c6
  Fault Module Name:	StackHash_0a9e
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	00000009
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
