### ISSUE TITLE
Add a button to easily remove projects....

### ISSUE THREAD

**Issue by RobGraham** [scout-app/scout-app#72]
The UI isn't what I would call "obvious". You start it up and are given a blank screen, not very explanatory. Then after noticing a '+' button at the bottom to add a folder, it took me 10 minutes to try find a '-' button. Then i noticed the removal of a folder was in the second pane at the very bottom...

**Comment by TheJaredWilcurt** [comment]
@RobGraham 

Issue resolved. Closing issue. Try the latest version of Scout-App. If you have any feedback about the design, please create another issue.

* [Scout-App 2](http://scout-app.io) (2016)
