### ISSUE TITLE
add compass extensions

### ISSUE THREAD

**Issue by waynoss** [scout-app/scout-app#73]
Hi is it possible to add compass extensions eg. http://stitchcss.com/ ?
Cheers thanks for the great work.

**Comment by TheJaredWilcurt** [comment]
Neither of those links still work. The latest version of Scout-App is made with Node instead of Ruby. So besides Compass Mixins, no Compass features/extensions can be supported.

* [Scout-App.io](http://Scout-App.io)

Closing ticket as "will not fix".
