### ISSUE TITLE
Very BIG lag on Windows Vista and Windows 7

### ISSUE THREAD

**Issue by FDiskas** [scout-app/scout-app#74]
There is a big delay in starting up and configuration form - picking up a combo-box and so on.
I'm using latest: ScoutApp 0.7.1

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing Issue. Scout-App 2 is considerably faster than Scout-App Classic.

* [Scout-App 2](http://Scout-App.io) (2016)
