### ISSUE TITLE
Projects on network drives are not watched

### ISSUE THREAD

**Issue by freedog96150** [scout-app/scout-app#75]
I cannot seem to get Scout-App to read and watch projects located on network folders.  I feel lame that I cannot get this to work but before I dive into this issue I figured that I should ask if the app works with projects stored on network folders.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
