### ISSUE TITLE
Problem with latest windows build?

### ISSUE THREAD

**Issue by zaccety** [scout-app/scout-app#76]
Just updated to latest 0.7.1.exe and I'm getting intermittent errors where the compiler is variously complaining about %error or border ... syntax being unexpected, after a few browser refreshes it usually fixes itself but not always.

Anyone else experiencing this?

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Download the latest version of Scout-App. Closing issue.

* [Scout-App.io](http://scout-app.io)
