### ISSUE TITLE
Grammar Fix For Scout Log Message To Developers

### ISSUE THREAD

**Issue by grayghostvisuals** [scout-app/scout-app#78]
Just a small grammar issue. The portion after "in your projects" on the first line needs to be a completed thought instead of fragmented as it sounds currently. 

#### OLD  :-1: 
"Dear developers making use of FSSM in your projects, be taking place in the new shared guard/listen project. Please let us know if you need help transitioning! ^_^b - Travis Tilley >>> Compass is polling for changes. Press Ctrl-C to Stop."

#### NEW :+1:
"Special Message From Travis:
For those developers making use of FSSM in your projects &bull; All FSSM projects must be taking place in the new shared guard/listen project. Please let us know if you need help transitioning! ^_^b - Travis Tilley"

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Download the latest version of Scout-App.

* [Scout-App 2](http://scout-app.io) (2016)
