### ISSUE TITLE
Popup for compile status messages

### ISSUE THREAD

**Issue by giulianoliker** [scout-app/scout-app#79]
Just wondring if Scout could show & hide quick status message overlaid in the corner after compiling is done just to let us know if it was successful or not. I believe CodeKit app does something like that. Right now I have to switch to the Scout app to see if everything was OK before testing in browser. Popup would save us some time there.

Thanks

**Comment by TheJaredWilcurt** [comment]
This has been added to the [Project Road Map](https://github.com/scout-app/scout-app/blob/master/documentation/project-management.md#phase-5-bug-fixesadditional-featuresmaintenance) for future versions of Scout-App.

**Comment by TheJaredWilcurt** [comment]
Desktop notification settings for success and error messages have been added to the master branch. This will be in the next release of Scout-App.

**Comment by TheJaredWilcurt** [comment]
@giulianoliker

There is a new release of Scout-App available for download.

* [Scout-App.io](http://scout-app.io)
