### ISSUE TITLE
Cannot install for development on Linux

### ISSUE THREAD

**Issue by brousch** [scout-app/scout-app#8]
I'm trying to get scout-app to run on Linux, specifically Ubuntu 10.04. I am running into what looks like a hard-coded OSX path when rake tries to check the Adobe Air version (File not found: /Library/Frameworks/Adobe AIR.framework/Versions/1.0/Resources/Info.plist)

Here is the full rake trace:

rake --trace
(in /home/ben/Dropbox/Projects/scout-app)
** Invoke default (first_time)
** Invoke run:development (first_time)
** Invoke build:development (first_time)
** Execute build:development
** Invoke build (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke air:runtime:check (first_time)
** Execute air:runtime:check
rake aborted!
Could not find Adobe AIR installation. To download/install run:

  rake air:runtime:download

File not found: /Library/Frameworks/Adobe AIR.framework/Versions/1.0/Resources/Info.plist
/home/ben/Dropbox/Projects/scout-app/config/../lib/adobe/air.rb:51:in `version'
/home/ben/Dropbox/Projects/scout-app/config/../lib/adobe/air.rb:116:in `print_version_check'
/home/ben/Dropbox/Projects/scout-app/lib/tasks/air.rake:12
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/home/ben/Dropbox/Projects/scout-app/lib/tasks/build.rake:9
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28

**Comment by TheJaredWilcurt** [comment]
@brousch @explainer 

Scout-App 2 officially supports many popular Linux distros.

> **Minimum System Requirements for Linux:**
> At least **64MB** of available RAM. At least **170MB** of free space. Ubuntu 12, Ubuntu 14, Ubuntu 16, Debian 8, Zorin 9, Zorin 11. 32-Bit or 64-Bit OS (ARM not supported). Some other Linux OS's (particularly Debian based) may work, though are not officially supported.

Ubuntu 10 is not officially supported, though it will most likely work.

Also Scout-App no longer relies on Adobe Air, Java, or Ruby. It can run similarly to a portable app.

* [Scout-App.io](http://scout-app.io)

Closing this issue.

**Comment by jarrelldunson** [comment]
I downloaded both 64-bit and 32-bit on Ubuntu 18.04.1 ... and tried to run the program...and nothing happens.  How can I get the program to run?

**Comment by TheJaredWilcurt** [comment]
@jarrelldunson 
This issue is for those having difficulty trying to edit the source code of Scout-App.

It sounds like you are just trying to run Scout-App to use it.

1. Download the `.zip` package for the [latest version of Scout-App](https://github.com/scout-app/scout-app/releases)
2. Extract the `Scout-App` folder from the zip
3. Inside the folder you'll find a `Scout-App` executable.
   * In some Linux OS's you can just double-click the executable and it pops up
   * In some Linux OS's you will need to launch a terminal window and navigate to the folder containing the executable and run `./Scout-App`

32-Bit Scout-App will not run on 64-Bit Linux, and 64-Bit Scout-App will not run on 32-Bit Linux.

**Comment by jarrelldunson** [comment]
Hey, I re-download 64-bit ... and clicked it... and it didn't work.  I tried the ./Scout-App from the command line...and got:  'error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory.  I'll run updated on my Linux machine and try again

**Comment by jarrelldunson** [comment]
Hey, I ran updates... and tried again, but still have the same error 'error while loading shared libraries: libgconf-2.so.4'

**Comment by valjar** [comment]
> Hey, I ran updates... and tried again, but still have the same error 'error while loading shared libraries: libgconf-2.so.4'

Try with (if you are using Ubuntu
`sudo apt -y install libgconf2-4`
