### ISSUE TITLE
Error #3214 on Windows 8

### ISSUE THREAD

**Issue by bkbillma** [scout-app/scout-app#80]
Whenever you hit play it comes up with the error 3214

I was informed via Twitter that Windows 8 consideration hasn't been taken yet but it seems like it might not be to difficult of a fix.  The error seems to be related to path issue which might just be a difference the where it installs on win 8 vs 7 or something of the like.

Obviously just my guesses but if a fix can be found that would be greatly appreciated.  Great work so far, it works nicely on Windows 7 at work but I only have Win 8 at home now :( and I would really like to be able to use it for home projects.

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing this ticket. Scout-App 2 no longer relies on Adobe Air or Java.

* [Scout-App 2](http://Scout-App.io) (2016)
