### ISSUE TITLE
Loads of output when compiling

### ISSUE THREAD

**Issue by Vortilion** [scout-app/scout-app#81]
Hi,

I get the following output in the log when trying to compile (Windows 7 64Bit):

>>> Change detected at 15:30:58 to: styles.scss
create D:\SVNROOT\customers\vapiano\src/images/structure/ico-s66b9c6db35.png
ArgumentError on line 733 of file: different prefix: "D:\\" and "D:/SVNROOT/customers/blablacustomer/src/css"
C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb:225:in `compute_relative_path' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/sass_extensions/functions/urls.rb:163:in `generated_image_url' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/sass_extensions/functions/sprites.rb:123:in `sprite_url' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/sprite_map.rb:72:in `method_missing' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/sass_extensions/sprites/sprite_map.rb:63:in `to_s' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/script/list.rb:44:in `to_s'
org/jruby/RubyArray.java:2336:in `collect' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/script/list.rb:44:in `to_s' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:295:in `visit_prop' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children' org/jruby/RubyArray.java:2336:in `collect' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:316:in `visit_rule' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children' org/jruby/RubyArray.java:2336:in `collect' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:203:in `visit_if' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:206:in `visit_if' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `visit_import' org/jruby/RubyArray.java:2336:in `collect' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `visit_import' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `visit_import' org/jruby/RubyArray.java:2336:in `collect' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `visit_import' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children' org/jruby/RubyArray.java:2336:in `collect' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:126:in `visit_root' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit' org/jruby/RubyKernel.java:2096:in `send' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:7:in `visit' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/tree/root_node.rb:20:in `render' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/engine.rb:315:in `_render' C:/opt/Scout/vendor/gems/gems/sass-3.2.1/lib/sass/../sass/engine.rb:262:in `render' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:140:in `compile' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:126:in `timed' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:139:in `compile' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/logger.rb:45:in `red' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:138:in `compile' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:118:in `compile_if_required' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:103:in `run' org/jruby/RubyArray.java:1603:in `each' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:101:in `run' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:126:in `timed' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/compiler.rb:100:in `run' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:147:in `recompile' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:68:in `perform' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!' C:/opt/Scout/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!' C:\opt\Scout\bin\compass:12:in `(root)' 
Dear developers making use of FSSM in your projects, be taking place in the new shared guard/listen project. Please let us know if you need help transitioning! ^_^b - Travis Tilley >>> Compass is polling for changes. Press Ctrl-C to Stop.

**Comment by TheJaredWilcurt** [comment]
Issue presume resolved. Closing issue. Download the latest version of Scout-App.

* [Scout-App.io](http://Scout-App.io)
