### ISSUE TITLE
[Win] problem with copy/past in input/output

### ISSUE THREAD

**Issue by Cedric-ruiu** [scout-app/scout-app#83]
Hi,

I found a problem with copy/past in input/output folder config on Windows 7.

1. Create new project in scout
2. Past your path in input and output folder field
3. Try to lunch

If you don't use "choose" button with this bad folder dialog box, the path that you put is not considered. It choose first the folder scout project.

**Comment by TheJaredWilcurt** [comment]
Issue resolved in latest version. Closing issue. Download latest version of Scout-App.

* [Scout-App.io](http://Scout-App.io)
