### ISSUE TITLE
LoadError on line 1038 of org/jruby/RubyKernel.java: no such file to load -- susy

### ISSUE THREAD

**Issue by josephjordan** [scout-app/scout-app#84]
![Screen shot 2012-12-29 at 1 47 15 PM](https://f.cloud.github.com/assets/3149535/35392/44f05886-51e8-11e2-9ef0-ab154fd5fb91.png)
![Screen shot 2012-12-29 at 1 46 11 PM](https://f.cloud.github.com/assets/3149535/35393/590a92c8-51e8-11e2-854c-314fd1b44de2.png)

I'm using susy when I use the command line I get no such error. When I use Scout I get these errors...any help would be great!!!! see below...

LoadError on line 1038 of org/jruby/RubyKernel.java: no such file to load -- susy
/Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/data.rb:161:in `require' /Users/joej/Desktop/susy_test/config.rb:20:in `parse_string'
org/jruby/RubyKernel.java:1088:in `eval' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:24:in `parse_string' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:15:in `_parse' org/jruby/RubyIO.java:1111:in `open' org/jruby/RubyKernel.java:298:in `open' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/serialization.rb:14:in `_parse' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:7:in `new_from_file' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/inheritance.rb:204:in `with_defaults' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/file_data.rb:6:in `new_from_file' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:42:in `configuration_for' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/configuration/helpers.rb:97:in `add_project_configuration' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:31:in `add_project_configuration' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:25:in `configure!' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/project_base.rb:15:in `initialize' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/commands/update_project.rb:37:in `initialize' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:42:in `perform!' /Applications/Scout.app/Contents/Resources/vendor/gems/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!' /Applications/Scout.app/Contents/Resources/bin/compass:12:in `(root)'

**Comment by TheJaredWilcurt** [comment]
The latest version of Scout-App no longer relies on Ruby, Java, or Adobe Air. It ships with Susy mixins built in, but will not recognize Ruby Gems as it is Node-based.

* [Scout-App.io](http://Scout-App.io)

Closing issue as "will not fix".
