### ISSUE TITLE
Scout invariably crashes upon folder selection

### ISSUE THREAD

**Issue by majimekun** [scout-app/scout-app#85]
Hi,

I've been using Scout for months without problems but recently, the application crashes everytime I try to select a target folder for the CSS files both for existing projects and new projects.

I'm on Windows Vista Home Premium 32 bit and the issue remains even after the reinstallation of the latest versions of Scout, Java and Adobe Air.

Below is the detail of the error message :

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Scout.exe
  Application Version:	0.0.0.0
  Application Timestamp:	4f4da3c6
  Fault Module Name:	Adobe AIR.dll
  Fault Module Version:	3.5.0.880
  Fault Module Timestamp:	50b8721d
  Exception Code:	c0000005
  Exception Offset:	002240f0
  OS Version:	6.0.6002.2.2.0.768.3
  Locale ID:	1036
  Additional Information 1:	1acf
  Additional Information 2:	63ca67c204b6d97f1a070463434e9e24
  Additional Information 3:	e463
  Additional Information 4:	f5f224f02f38e3ccc8047000b72ef6bf

Thanks in advance for any help!

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App.io](http://Scout-App.io)
