### ISSUE TITLE
Windows 8 prevents install

### ISSUE THREAD

**Issue by adam-lynch** [scout-app/scout-app#86]
Windows 8 release preview blocks install until `More Info` -> `Run Anyway` is chosen.

Adobe Brackets has the same problem ([#1934](https://github.com/adobe/brackets/issues/1934)). Here are a couple of screenshots:

Initial popup:
![Initial](https://f.cloud.github.com/assets/1427241/36961/2e64fafe-5391-11e2-9020-1535f021faf2.PNG)

After clicking "More info":
![Run Anyway](https://f.cloud.github.com/assets/1427241/36962/348f970e-5391-11e2-8103-12c07a596aec.PNG)

**Comment by TheJaredWilcurt** [comment]
Issue presumed resolved. Closing Issue. Download the latest version of Scout-App. If the problem still exists, create a new issue.

* [Scout-App](http://scout-app.io)
