### ISSUE TITLE
Chrome Dev Tools Integration?

### ISSUE THREAD

**Issue by CalebKester** [scout-app/scout-app#87]
I'm trying to find if this has integration for Chrome Dev Tools. It would be cool to have it be an option under output methods: http://bricss.net/post/33788072565/using-sass-source-maps-in-webkit-inspector

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Scout-App's "Development" environment option will output Sass maps.

* [Scout-App 2](http://scout-app.io)
