### ISSUE TITLE
Slow Performance

### ISSUE THREAD

**Issue by JamesGeiger** [scout-app/scout-app#88]
When navigating the GUI things are laggy and slow. This has been confirmed by a few other users I asked.

Memory usage is not the major issue..it is just extremely slow when navigating the GUI for some reason.

**Comment by TheJaredWilcurt** [comment]
@JamesGeiger @multicelldesign 

Issue resolved. Closing issue. The latest version of Scout-App is considerably faster than Scout-App Classic.

* [Scout-App 2](http://scout-app.io) (2016)
