### ISSUE TITLE
Image URL path being reset

### ISSUE THREAD

**Issue by bitmanic** [scout-app/scout-app#9]
Trying to reference images via Compass's image_url() method is faulty. After setting the correct location within a project's config screen, Scout will use the desired path on the first compile only. After the first compile, the 'http_images_path' setting is either ignored or replaced with a value of "/images". No bueno.

For reference, here's a screenshot of the issue: http://cl.ly/3o0d0V370r0e3S2L0C2U. As you can see, the first reference of the image url path is correct...I had configured the project to look in "/images/interface". However, each subsequent error references "/images".

Let me know if you need any further clarification or feedback!

**Comment by TheJaredWilcurt** [comment]
Scout-App 2 is Node-based and no longer relies on Ruby. And since Compass only runs on Ruby that means (besides mixins) Scout-App 2 cannot support Compass or any other Ruby Gem.

Closing this issue as "will not fix".

* [Scout-App.io](http://scout-app.io)
