### ISSUE TITLE
Add possibility to include gems (as Susy, etc.) 

### ISSUE THREAD

**Issue by herom** [scout-app/scout-app#90]
hey there,
this is more request as an issue, but would it be possible to allow the users to include their own gems, or reload a certain amount of compass related gems and to configure their own "config.rb" file per project?

I love to work with Scout, but now I'm facing problems when I want to include the Susy gem for easy grid integration and it's a pitty that I can't use Scout for this purpose but have to go back to the command line to 'compile' my *.scss files...

**Comment by TheJaredWilcurt** [comment]
The latest version of Scout-App no longer relies on Ruby. It is instead built with Node. As such, we can no longer support Ruby Gems. Scout-App 2 does however ship with many common built in Sass mixin libraries, including Susy (susy/su/susyone).

* [Scout-App 2 Supported Mixins](http://Scout-App.io/#mixins)

Closing issue as "will not fix".
