### ISSUE TITLE
Scout Issue : TypeError on line 3414 of org/jruby/RubyString.java

### ISSUE THREAD

**Issue by bleams** [scout-app/scout-app#91]
Hello. I have already seen this issue previously closed but after trying the solutions it still doesn't work. 
I'm having the exact same problem : 
TypeError on line 3414 of org/jruby/RubyString.java: no implicit conversion from nil to integer
Run with --trace to see the full backtrace

My configurations :

Windows 7 64 bits
Java Version 7 Update 13
Adobe AIR 3.5
Scout last version 0.7.1

I am using SCSS files.

thank you for your help

Bleam

**Comment by xDanbo** [comment]
I'm experiencing the same problem. All the paths are in Latin. Where is that file exactly and should I do to fix it?

I'm on Windows 7 x64, Adobe AIR 16, Java 8, Scout 0.7.1.

**Comment by TheJaredWilcurt** [comment]
Scout requires Java 6 or 7, and will not work with 8. You can have 7 & 8 both installed though. Easiest way to install what you need:

* http://ninite.com/air-java7

**Comment by xDanbo** [comment]
No, unfortunately, installing Java 7 didn't help. Any other advice?

**Comment by TheJaredWilcurt** [comment]
@xDanbo @bleams @ooredroxoo @rednosemonkey 

The newest version of Scout-App no longer relies on Ruby, Java, or Adobe Air. Closing this issue.

Download Scout-App 2 at:

* [Scout-App.io](http://Scout-App.io)
