### ISSUE TITLE
Scout wont connect to my SASS files please help!

### ISSUE THREAD

**Issue by AlanaLeddin** [scout-app/scout-app#92]
This comes up on Scout.app when I attempt to configure my files..

Dear developers making use of FSSM in your projects, be taking place in the new shared guard/listen project. Please let us know if you need help transitioning! ^_^b - Travis Tilley >>> Compass is polling for changes. Press Ctrl-C to Stop.

What do I do?

**Comment by TheJaredWilcurt** [comment]
Issue resolved. Closing issue. Download the latest version of Scout-App.

* [Scout-App.io](http://scout-app.io)
