### ISSUE TITLE
Scout with Blueprint variant

### ISSUE THREAD

**Issue by prabuvenkat** [scout-app/scout-app#93]
How can I use Scout with say Liquid Blueprint (test: http://www.designbyfire.com/liquid_blueprint/tests/liquid.html; from http://www.ixda.org/node/15655) or my own hybrid blue-print with fixed -and- fluid columns ?

do let me know, thanx,

;-p r a b u!

**Comment by TheJaredWilcurt** [comment]
Blueprint is a fairly dated CSS framework. It has not been updated is [2011](https://github.com/joshuaclayton/blueprint-css/commits/master). I would recommend looking into a more modern framework to handle page layout/grid systems. Bootstrap, Foundation, and Bulma are all popular alternatives.

* [Scout-App.io](http://Scout-App.io)

Closing issue as "will not fix".
