### ISSUE TITLE
Support Bourbon

### ISSUE THREAD

**Issue by lehni** [scout-app/scout-app#98]
I prefer Bourbon over Compass for a while now, and was wondering if it is planned to support it out of the box?

I guess a project would have to choose either Compass or Bourbon, so there would have to be a pulldown for that in the configuration settings.

http://bourbon.io

**Comment by TheJaredWilcurt** [comment]
Bourbon, Neat, and Compass mixins come built in to Scout-App 2.

Closing issue.

* [Scout-App.io](http://scout-app.io)
* [Supported Mixins](http://scout-app.io/#mixins)
